### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by ItsM3rk** [TeamMetallurgy/Aquaculture#100]
When i try to launch the game i get this error saying it can not load a chest or something like that.
[
[latest.log](https://github.com/TeamMetallurgy/Aquaculture/files/4371480/latest.log)
](url)

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 are you using?
Please try updating Forge, if you're using Aquaculture version 2.0.12.

**Comment by ItsM3rk** [comment]
I am indeed using that version and i already tried updating forge

**Comment by GirafiStudios** [comment]
No you're not.
You're running Aquaculture 2 for 1.14.4 on Minecraft Forge for 1.15.2.
Please update to Aquaculture 2 for 1.15.2, or use Forge for 1.14.4
