### ISSUE TITLE
When using aquaculture rods to fish farm, it doesn't grab EXP.

### ISSUE THREAD

**Issue by ConnectFourGod** [TeamMetallurgy/Aquaculture#101]
Aquaculture rods don't grab exp, unsure whether or not it is grabbing items as well.

Error my server is getting:

[Server thread/ERROR] [aquaculture/]: Loot was empty in Biome: net.minecraft.world.biome.JungleBiome@5570ee6d. Please report on Github

**Comment by GirafiStudios** [comment]
First off we do not encourage or support fish farms in any way.
The "loot was empty in Biome" issue should be fixed if you're using the latest 1.15.2 version though.
