### ISSUE TITLE
Message In A Bottle

### ISSUE THREAD

**Issue by kodabeer** [TeamMetallurgy/Aquaculture#104]
![2020-03-30_20 28 01](https://user-images.githubusercontent.com/53926065/77974535-6c573600-72c5-11ea-957b-d86dafff14db.png)
Used a message in a bottle, it seems to have had a problem displaying what the message is.

**Comment by GirafiStudios** [comment]
Message in a Bottle just contains a gimmicky message, that one is just one of them. It's a joke.
