### ISSUE TITLE
Suggestion About "Fish Mount"

### ISSUE THREAD

**Issue by LokyLive** [TeamMetallurgy/Aquaculture#105]
Actually i'm enjoying to this amazing fishing mod and i try to catch everything to complete my museum of fishing ,p

Of course i'm using mount for it but i can't put frog or turtle on mount . I know they're not fish but they was so hard to catch xD 

So could you add turtle and frog to the mount list please ?

PS: a display shelf for fishing rod could be cool too xD

**Comment by GirafiStudios** [comment]
Thank you for your suggestion!
As frogs does not have a mobs, that's gonna be a no. Turtles I might consider for some point in the future though.
