### ISSUE TITLE
Neptunum Gears are too strong, please nerf or add config mode

### ISSUE THREAD

**Issue by feru4g** [TeamMetallurgy/Aquaculture#106]
Hello, I am enjoyed your MOD ver 1.14.4-2.0.7.
But I feel a little bit of problem, the Neptunum Gears are "too strong".
Total armor score is 20, equal to Diamond Gears, durability is over it, and having underwater special effects.
So please nerf the Neptunum Gears or add config mode (user setting those numbers).
If possible, I would be setting Bountry Box Drop Rate, too (more rare).
I hope you will consider this matter.

**Comment by GirafiStudios** [comment]
You can turn Neptunium armor off in the config already, or you can modify the loot table rarity with a resource pack the same way you would with a vanilla loot table.
Or you could update to 1.15.2, where it's significantly rarer.
