### ISSUE TITLE
Upgrade Aquatic compatibility

### ISSUE THREAD

**Issue by cybercatgurrl** [TeamMetallurgy/Aquaculture#107]
First off love the mod! I'd like to point out that it'd be nice if the fish that Upgrade Aquatic adds would work with the knife to make fillets.

**Comment by GirafiStudios** [comment]
They would have to add support on their end. We provide an API for them to use for that very purpose.

**Comment by cybercatgurrl** [comment]
Oh in that case I’ll ask them about it. Thanks!
