### ISSUE TITLE
Recipe Compatibility

### ISSUE THREAD

**Issue by awesomedeity** [TeamMetallurgy/Aquaculture#109]
Could you please add tags to the fillets to make them compatible with other recipes. The specific ones I'm looking for are forge:rawfish, forge:rawmeats, and forge:stock_ingredients on the raw fillets and forge:cookedfish on the cooked fillets to make it compatible with Pam's Harvestcraft 2 Food Core and Simple Farming recipes.

**Comment by GirafiStudios** [comment]
As long as Pam's Harvestcraft keep not following naming standards for tags, no support will be provided on our side.
