### ISSUE TITLE
Neptunium armor reuses diamond armor equipping sound event leading to incorrect subtitles

### ISSUE THREAD

**Issue by muzikbike** [TeamMetallurgy/Aquaculture#110]
![2020-04-24_08 51 34](https://user-images.githubusercontent.com/52297970/80188645-6248fe80-8609-11ea-99a8-bf9f63fb5fae.png)

**Comment by GirafiStudios** [comment]
Having custom sounds for everything is a very unrealistic goal. Not gonna happen.

**Comment by muzikbike** [comment]
The sound event could still point to the diamond equipping sounds, and would just have a unique subtitle.

**Comment by GirafiStudios** [comment]
It cannot, unless you add a custom sound.
