### ISSUE TITLE
Lag from expensive lootable calculation

### ISSUE THREAD

**Issue by Darkere** [TeamMetallurgy/Aquaculture#113]
https://spark.lucko.me/#BGITquS5Ke
![image](https://user-images.githubusercontent.com/4283717/81223902-1c1b7400-8fe7-11ea-9f3b-3adefad1a549.png)

Someone on our server set up 16 IF fisher. Calculating the loot table for them seems to be very expensive due to some aquaculture calculation. 

forge-31.1.63
Aquaculture-1.15.2-2.0.13

**Comment by GirafiStudios** [comment]
What exactly is an IF Fisher?

**Comment by Darkere** [comment]
Machine that generates loot from the fishing loottable every few seconds, based on a couple conditions.

**Comment by GirafiStudios** [comment]
What mod is it from?
Also could you provide me some numbers without Aquaculture 2?

**Comment by Darkere** [comment]
It is from Industrial Foregoing. 

And that is going to be difficult. After a server restart the numbers went down quite a bit to a still expensive but much more reasonable 3%. Not sure why, but I imagine that could be due to the number of cached biomes or something?

Still going to try it.

**Comment by Darkere** [comment]
With Aquaculture https://spark.lucko.me/#dpDGlC0BwO
![image](https://user-images.githubusercontent.com/4283717/81229911-e11e3e00-8ff0-11ea-8809-ed06cb6169b4.png)


Same world with Aquaculture removed https://spark.lucko.me/#Lj3BgyFQvL
![image](https://user-images.githubusercontent.com/4283717/81229988-04e18400-8ff1-11ea-8d17-83c4ee4522db.png)

**Comment by GirafiStudios** [comment]
Can you take a screenshot of the full one for Aquaculture? Since that one does not say "ms" anywhere, so does precentages doesn't really mean anything.

**Comment by Darkere** [comment]
Spark profiles the actual code execution and not each tick individually. Also, as the machines from Industrial foregoing don't evaluate loot tables every tick it's a bit difficult to get exact numbers.

Scaling from the spark report puts it at roughly 3ms per tick in my test case, or at  ~60ms on the server where the issue was discovered.

**Comment by GirafiStudios** [comment]
The whole system have been rewritten in Aquaculture 2.1.0 for Minecraft 1.16.3, which should improve performance to - so I'm closing this.
You're very welcome to open up a new issue with profiling data for 1.16.3 though!
