### ISSUE TITLE
Neptune's Bounty has unused type blockstate

### ISSUE THREAD

**Issue by muzikbike** [TeamMetallurgy/Aquaculture#115]
The block closely resembles chests, with one notable difference being that it does not connect to other adjacent blocks. However, the block does still have the "type" block state that vanilla chests have. However, it goes unused, and when a value other than single is applied to the block it takes on a glitched appearence. Either this block state should be removed, or double neptune's bounty blocks should be officially supported.

![2020-05-08_19 07 36](https://user-images.githubusercontent.com/52297970/81435303-8a834200-915f-11ea-9a32-56f7be2d07e6.png)
![2020-05-08_19 07 39](https://user-images.githubusercontent.com/52297970/81435305-8bb46f00-915f-11ea-92e6-90595479adb1.png)
![2020-05-08_19 07 44](https://user-images.githubusercontent.com/52297970/81435306-8c4d0580-915f-11ea-867b-d1c0a0e65221.png)
![2020-05-08_19 07 51](https://user-images.githubusercontent.com/52297970/81435307-8c4d0580-915f-11ea-96f6-90c0e056a6a5.png)
![2020-05-08_19 07 53](https://user-images.githubusercontent.com/52297970/81435311-8ce59c00-915f-11ea-98c6-dcba2b43bd15.png)

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 are you using?

**Comment by GirafiStudios** [comment]
Are you using commands to place them btw.?

**Comment by muzikbike** [comment]
Latest version available on curseforge to my knowledge.
