### ISSUE TITLE
Placing Neptune's Bounty chest is not using up the chest

### ISSUE THREAD

**Issue by seals55** [TeamMetallurgy/Aquaculture#116]
I'm not sure where the Neptune's Bounty chests are coming from (either Industrial Foregoing Fishery or mob farms), but I have about 750 of them currently. I tried setting up a Refined Storage constructor/destructor to empty them. This works except it never uses up the original chest, so 1 chest can be created and destroyed giving loot + empty chest infinity. 

Same issue when using an Industrial Foregoing block placer, initial loot chest stays in block placer inventory, continuously dropping loot.

Using Valhelsia 2 mod pack for MC 1.15.2
https://www.curseforge.com/minecraft/modpacks/valhelsia-2

Aquaculture-1.15.2-2.0.13

**Comment by GirafiStudios** [comment]
Thanks for the report!
I'm afraid both of those mods is the cause of the issue, as the Neptune's Bounty is no more than a reskin of a vanilla chest. It's also using vanilla loot table functions to add the loot to it - essentially the same as what a shulker box is using to keep its content.
I assume both of those mods will have the same issue when trying to open a shulker box.
