### ISSUE TITLE
Suggestion: Support for MineColonies

### ISSUE THREAD

**Issue by xenoflot** [TeamMetallurgy/Aquaculture#119]
Hi folks,

I'm playing Enigmatica 5 which includes Aquaculture 2 and MineColonies. I gave my MC fisherman a diamond rod and he ignored it. When I asked in MC discord about support for modded foods and tools, I was advised that MC does support them. 

Since the fisherman is a common choice for first food-maker in MC and Aquaculture 2 makes substantial changes to the fishing system, it'd be great if you'd work with the MC team to get it working.

Cheers

**Comment by GirafiStudios** [comment]
Aquaculture 2 fishing rods is already just vanilla fishing rod - just uses different loot tables. So their support for modded fishing rods most be broken.
