### ISSUE TITLE
Possible incompatibility with Lithium

### ISSUE THREAD

**Issue by tajemniktv** [TeamMetallurgy/Aquaculture#120]
Hello, 
I have a problem with loading both Aquaculture and Lithium. When the loading screens are over, there's some critical error. Don't know if I should post it here or on the Lithium github so I'll post on both. 
(Lithium GH jellysquid3/lithium-forge#8)

Latest: https://hasteb.in/boqegigi.md
Debug: https://hasteb.in/wafevewe.md

Greetings
TajemnikTV

**Comment by GirafiStudios** [comment]
Lithium is reducing visibility of a method that Aquaculture 2 is not even using, so I don't see how this is caused by Aquaculture 2 :)
Let me know if Jellysquid says otherwise though.
