### ISSUE TITLE
Version 2.0.14, Frogs and Turtles not being caught in swamps.

### ISSUE THREAD

**Issue by Mystara0001** [TeamMetallurgy/Aquaculture#121]
Tried fishing with vanilla and AQ2 rods and have not caught a single frog or turtle.

Also, if they have in rendered mobs, they do not spawn.

Did notice that pufferfish can be caught in swamps. (Might be because they are vanilla)

**Comment by GirafiStudios** [comment]
They're just both quite rare catches.
Turtles does have a mob entity too, but is equally as rare. Can be changed in the config.
Yea pufferfish are just vanilla - vanilla don't care about biomes for the fish, only for bambo for some reason.

**Comment by Mystara0001** [comment]
What setting do I need to change in the config? Please provide a sample of the code I'm looking for,
