### ISSUE TITLE
Frogs and Turtles not being caught

### ISSUE THREAD

**Issue by Mystara0001** [TeamMetallurgy/Aquaculture#122]
Frogs and turtles are not being caught, nor are their appropriate models spawning.

Tried vanilla and Aquaculture rods all types. Have fished enough to break an iron rod. Tried different biomes, day and night.

Cannot locate code to change spawn frequency in config (complete config below). Please advise.

["basic options"]
	#Enable fish mob spawning? Weight & biomes can be modified in the Aquaculture fish loot table
	"Enable fish spawning?" = true
	"Enable weight for fish? Useful for fishing competitions" = false
	"Should fish be added as compostables for the composter/worm farm? (Based on fish, or weight if enabled)" = true
	"Enable debug mode? (Enables additional logging)" = false

["neptunium options"]
	"Enable recipes for Neptunium items?" = true
	"Enable recipes for Neptunium armor?" = true
	#Should Neptune's bounty be added as fishing loot? Very rare.
	"Add Neptune's Bounty as loot?" = true

["spawn options"]

	["spawn options".box_turtle]
		#Range: 0 ~ 64
		min = 1
		#Range: 0 ~ 64
		max = 2
		#Range: 0 ~ 100
		weight = 7
		include = ["SWAMP"]
		exclude = [""]

	["spawn options".arrau_turtle]
		#Range: 0 ~ 64
		min = 1
		#Range: 0 ~ 64
		max = 2
		#Range: 0 ~ 100
		weight = 4
		include = ["JUNGLE"]
		exclude = [""]

	["spawn options".starshell_turtle]
		#Range: 0 ~ 64
		min = 1
		#Range: 0 ~ 64
		max = 2
		#Range: 0 ~ 100
		weight = 5
		include = ["TWILIGHT"]
		exclude = [""]

**Comment by GirafiStudios** [comment]
Increase the weight for the Box Turtle (Only Swamp biomes) or Arrau Turtle (Only Jungle biomes).
Also, that's not code - that's from the config.
