### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by justcasuallyscrolling** [TeamMetallurgy/Aquaculture#124]
I found a typo: In the status of Neptune’s Bow, Neptune’s Strike is spelling wrong (Neptune’s Srike).

**Comment by GirafiStudios** [comment]
Thanks for your report!
This was actually fixed about a month ago https://github.com/TeamMetallurgy/Aquaculture/commit/3bc5eacda01dc5dcd8c7aa4b91a98e74eb35862f
No new version have been pushed to CurseForge yet though, but will be in next version :)
