### ISSUE TITLE
Gray Tropical Fish

### ISSUE THREAD

**Issue by WenXin20** [TeamMetallurgy/Aquaculture#128]
`Minecraft v1.15.2`
`Forge v31.2.31`
`Aquaculture v2.0.16`

The Tropical Fish only seems to display a gray/white fish. Is it possible to support all the random colors/models?

![2020-07-24_18 58 03](https://user-images.githubusercontent.com/12000593/88443865-c08ba600-cddf-11ea-977f-eeaca53bab41.png)

**Comment by GirafiStudios** [comment]
I still have to look into this again for 1.15.2, but I doubt it is - as it wasn't possible in 1.12.2

**Comment by GirafiStudios** [comment]
Unfortunately it's still not possible. I figured out a way to set the variant on rendering though, so it'll at least have color now.

**Comment by WenXin20** [comment]
Thanks!
