### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Camawama** [TeamMetallurgy/Aquaculture#129]
I have been working on this Vanilla Plus modpack for about a year now. In the 1.15 version, I had your mod added, but in the 1.16 version, it crashes on startup

**List of Mods:** https://pastebin.com/FKKy0UgU

**Crash Report:** 
[Aquaculture Crash Report.txt](https://github.com/TeamMetallurgy/Aquaculture/files/5037636/Aquaculture.Crash.Report.txt)

**Comment by sscards55** [comment]
Please make sure you have downloaded the right version of the mod.
The only version for 1.16.1 is this one:
https://www.curseforge.com/minecraft/mc-mods/aquaculture/files/3024910

**Comment by GirafiStudios** [comment]
Yea you're definitely loading the 1.15.2 version of Aquaculture 2 on 1.16.1, as the vanilla class it's crashing on, does not exist in 1.16.1 anymore.

**Comment by Camawama** [comment]
Twitch Launcher is trash. I clicked the Purple Install button and it installs the wrong version, wtf? Sorry to bother you
