### ISSUE TITLE
Crash when using resourcepack (1.16.1)

### ISSUE THREAD

**Issue by pa1nki113r** [TeamMetallurgy/Aquaculture#130]
Hello, I'm setting up a personal mod pack for a private server I run, and I notice the game crashes when using one of the resource packs I'm using.

`java.lang.IllegalStateException: Tag aquaculture:tooltip used before it was bound`

The resource pack I'm using is Tissou's Zombie Pack, found here: https://www.curseforge.com/minecraft/texture-packs/tissous-zombie-pack-optifine-1-7x-1-15

I'll attach the full stack trace as well:
[crash-2020-08-07_09.39.42-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/5042145/crash-2020-08-07_09.39.42-client.txt)

**Comment by GirafiStudios** [comment]
You can grab a Jenkins build with the fix here:
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.16/5/
