### ISSUE TITLE
feeding cats aquaculture fish doesn't heal them like vanilla fish

### ISSUE THREAD

**Issue by watamalon2** [TeamMetallurgy/Aquaculture#133]
my cat was damaged, and aquaculture fish doesn't heal them only normal fish

**Comment by GirafiStudios** [comment]
What version of Aquaculture are you using?

**Comment by watamalon2** [comment]
1.16.1-2.0.18

**Comment by GirafiStudios** [comment]
Testing with Aquaculture 2.0.18 for 1.16.1 I'm unable to reproduce the problem
![qtBJJLW](https://user-images.githubusercontent.com/6305377/90683917-9ce53f80-e267-11ea-8b91-7001fa3b18f7.png)
My best guess is that the fish you tried with, is not actually from Aquaculture 2.

**Comment by watamalon2** [comment]
the thing is, they eat it but their health doesn't go up

**Comment by GirafiStudios** [comment]
I didn't actually check that, I'll check it again tomorrow.
