### ISSUE TITLE
Neptunian Chest

### ISSUE THREAD

**Issue by Parck92** [TeamMetallurgy/Aquaculture#136]
Hi everyone,
I dont know if its meant to work like this but on a 1.16 Valhesia 3 server Neptunian chests are not found after hours ( at least 5 ) of industrial foregoing marine fisher.
Its a bug?

**Comment by GirafiStudios** [comment]
In 1.16 the "open waters" requirement, as vanilla have added as a requirement for getting any kind of treasure in 1.16.

**Comment by Parck92** [comment]
In reality i get every treasure except the neptunian chest.
