### ISSUE TITLE
Starshell Turtles not spawning

### ISSUE THREAD

**Issue by SamsyTheUnicorn** [TeamMetallurgy/Aquaculture#137]
Due to Twilight Forest not being available in 1.16.1, "Aquaculture 2 1.16.1-2.0.19" doesn't allow you to catch Starshell Turtles by default because the configs point to them being available in "TWILIGHT" biomes only.
Would it be possible to change the default to a vanilla biome or is the responsibility on users to change the configs to an existing biome?

**Comment by GirafiStudios** [comment]
It's only intended as support for Twilight Forest, not intended to ever appear anywhere else.
If the user wants to change the BiomeDictionary tag that it spawns in, that's up to them.
