### ISSUE TITLE
Crash Ticking entity

### ISSUE THREAD

**Issue by SurielGon** [TeamMetallurgy/Aquaculture#139]
**What is happening?**
Sometimes fishes causes ticking entity crash, which make your world crash, the crash happens during gameplay if your base is next to fishes(like next to rivers and oceans), after the crash you can just restart minecraft and enter your world, it wont fail to load.
**What is the ticking entity crash?**
As far as my searching went, I understood that it's a NullPointerException caused by an entity.
**What minecraft version and mods?**
I am playing a modpack called valhelsia 2, for minecraft 1.15.2, I am starting it from the twitch launcher with 10GB ram
**My first thoughts:**
One of the crash reports there was a mod called AI improvements that caused vanilla mobs to give Ticking entity error, I removed it and vanilla mobs never caused ticking entities again, unfortunately aquaculture fishes suffered zero changes with this, and continued to crash the game after continuous gameplay. 
**Why I am posting this here?**
The discord for the modpack didn't had a section for crash report or fixing, so I went directly on this mod page to post the error, also the entity that gives the error is from the aquacultere.
_**Below the crash report file about aquacultere**_
[crash-2020-09-20_14.32.34-server.txt](https://github.com/TeamMetallurgy/Aquaculture/files/5307778/crash-2020-09-20_14.32.34-server.txt)
[crash-2020-09-29_23.10.33-server.txt](https://github.com/TeamMetallurgy/Aquaculture/files/5307779/crash-2020-09-29_23.10.33-server.txt)

**Comment by GirafiStudios** [comment]
The crash is caused by Performant.
Something about how they try to optimize stuff must be breaking things.
