### ISSUE TITLE
[Feature] Support for other wood types in fish mounts

### ISSUE THREAD

**Issue by Mnky313** [TeamMetallurgy/Aquaculture#140]
I noticed that in the 1.16 version of the mod there doesn't appear to be crimson or warped fish mounts.

Also adding support for other mods like Enhanced Mushrooms and Quark would be awesome!

**Comment by GirafiStudios** [comment]
As Aquaculture 2 does not currently have any nether-related content, we'll not be adding Crimson & Warped fish mounts.
We're not gonna add specific mod support for other mods, but it's possible for other mods to add fishing mounts through our API. (Or making an addon for Aquaculture 2, that adds Fish Mounts for other mods wood types)
