### ISSUE TITLE
[Feature] Lava Fishing in the nether

### ISSUE THREAD

**Issue by Blugori** [TeamMetallurgy/Aquaculture#142]
That's it, fishing in lava (maybe only in nether ?)
I was wondering if you were open to suggestions. I saw that a mod for lava fishing for fabric existed, and a datapack too, but that would be a cool thing to be added in Aquaculture.
We could fish in lava in the nether, only with a netherite rod or with a neptunium rod, and could drop unique fishs, rare loot (soul speed enchantment, snout template, a new kind of junk...)

Thanks for reading !

**Comment by GirafiStudios** [comment]
Our API supports it, so it's possible for another mod to add support for it.
It was in our original plans for the initial release of Aquaculture 2 for 1.14, but unfortunately we never finished it.
We actually had art and implemented 6 nether/lava hooks, but had to remove them before releasing - as we never had any lava or nether fish/loot
