### ISSUE TITLE
Machines don't catch Aquaculture fish.

### ISSUE THREAD

**Issue by Slyklaw** [TeamMetallurgy/Aquaculture#145]
Version 1.12.2-1.6.8

I've tried both Pam's Water Trap and Cyclic Automatic Fishing Net. Neither will catch any Aquaculture fish.

**Comment by sscards55** [comment]
Pam's Water Trap has it's own set of fish that it uses.
Cyclic's Automatic Fishing Net only looks at what you can catch with the vanilla fishing rod.

**Comment by GirafiStudios** [comment]
It's indeed a issue with the mods fishing nets, as we inject it to the vanilla fishing table

**Comment by Slyklaw** [comment]
Is it intentional that vanilla rod does not fish aquaculture fish? The modpack page says otherwise. Vanilla rod does not fish aquaculture fish. https://www.curseforge.com/minecraft/mc-mods/aquaculture

**Comment by GirafiStudios** [comment]
You're on 1.12.2, which is Aquaculture 1
The information you're reading about is for Aquaculture 2 (As stated at the top of the description, with Minecraft versions)
Close to the bottom of the description there is a spoiler with information for Aquaculture 1.
I didn't notice you were on 1.12.2 when responding before - fishing nets will indeed not work with Aquaculture 1 fish, unless it has special support

**Comment by sscards55** [comment]
My response was for 1.12 I check the code for those versions of the mods.

**Comment by GirafiStudios** [comment]
Yes, but even if they did do things properly, it still wouldn't work with Aquaculture 1 at all.
(Accidentally reopened it before, oups)

**Comment by sscards55** [comment]
I'm linking the code for reference to both mods.
Pam's:
https://github.com/MatrexsVigil/harvestcraft/blob/master/src/main/java/com/pam/harvestcraft/tileentities/TileEntityWaterTrap.java#L211
Cyclic:
https://github.com/Lothrazar/Cyclic/blob/trunk/1.12/src/main/java/com/lothrazar/cyclicmagic/block/fishing/TileEntityFishing.java#L198
