### ISSUE TITLE
License Info Missing

### ISSUE THREAD

**Issue by Zombiekiller1mc** [TeamMetallurgy/Aquaculture#148]
So I downloaded it and went to run it, but says its missing the License Information

**Comment by GirafiStudios** [comment]
Sounds like you're on 1.16.1. Aquaculture 2 only works up to Forge version 32.0.88 for 1.16.1
I recommend you start using Minecraft 1.16.3, instead of 1.16.1

**Comment by Zombiekiller1mc** [comment]
yes i figured the problem was that when i downloaded latest the version was
1.16.1 but thx
