### ISSUE TITLE
[1.16.3] Excessive fish spawn rate in non-ocean biomes.

### ISSUE THREAD

**Issue by syelents** [TeamMetallurgy/Aquaculture#149]
**Minecraft Version:** 1.16.3
**Aquaculture Version:** 2.1.2
**Forge Version:** 34.1.25

**Bug:**
Fish spawn rates are insane. The longer you stay in an area, the more and more fish spawn. This doesn't seem to happen in Ocean biomes, I've tested a lot of biomes and that's the only one that this doesn't happen in.
I have no other mods installed.

![2020-10-23_02 04 53](https://user-images.githubusercontent.com/54427152/96962115-274e5780-14d4-11eb-87b8-1ae2d0ee314d.png)

**Comment by Gotolei** [comment]
I'm getting this behavior as well, in Valhelsia 3 (pre1-3.1.0; 1.16.3; mod version 2.1.2).
https://i.imgur.com/F91jOAq.png

**Comment by InflamedSebi** [comment]
Same issue. Server crashing now because of too many entities and a single tick takes over 1 minute to complete.

**Comment by V-Boy** [comment]
Can confirm as well

**Comment by drakray** [comment]
Yeah, I was happy to have squid back, but if I but that on my server, it will probably catch fire lol XD
MC 1.16.3
Forge 34.1.25
Aquaculture 2.1.2
buncha others

**Comment by GirafiStudios** [comment]
Use Aquaculture 2.1.1 for now, it's a known issue.
Will look into it as soon as I have time

**Comment by drakray** [comment]
I tried InControl, to limit Aquaculture spawn, and it seems to work, so there that 
(must have those little fishys \o/ )

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/TeamMetallurgy/Aquaculture/commit/efdc75db036ca04924da37bd06af3d99d0fe654d
Build will be available on CurseForge shortly

**Comment by Freebi85** [comment]
Hey there^^ This is happening for me again. :0

Minecraft 1.16.5
Forge 36.1.32
Aquaculture  2.1.19
