### ISSUE TITLE
Aquaculture recipes aren't sorted in the Crafting Table

### ISSUE THREAD

**Issue by BetaCarotina** [TeamMetallurgy/Aquaculture#150]
This issue isn't specific for Aquacuture, almost all mods have it. The recipes in the Crafting Table are sorted based on their Creative Inventory location. To fix this, simply add the tool items to the Tools tab, weapons and armor to Combat and Neptunium Block to Building Blocks. I don't think you need to remove them from the Aquaculture tab, though I'm not sure.

For some reason furnaces don't follow this logic, so you don't need to add food items to Food category.

**Comment by BetaCarotina** [comment]
Actually, maybe Forge should add a way to sort these recipes without having to duplicate items in Creative Inventory

**Comment by GirafiStudios** [comment]
Forge does not want any type of recipe sorting, Lex have been against it for a while.
And I don't have any interest in duplicate entries in the Creative inventory
