### ISSUE TITLE
keeping getting crashed on start up

### ISSUE THREAD

**Issue by lilmrmagoo** [TeamMetallurgy/Aquaculture#151]
latest log: https://pastebin.com/jPVuLXWX
crash: https://pastebin.com/VAvjU2ak
I have no idea why this is happening I tried using a different version of forge and it didn't fix it.

**Comment by V-Boy** [comment]
https://hatebin.com/izbzhaieay
Got this as well, its cuz of the new forge versions. Try 34.1.25

**Comment by GirafiStudios** [comment]
Should be fixed in 34.1.30 or newer, so try that. If that doesn't work, then go back to Forge version 34.1.25, as V-Boy suggested.

**Comment by BugmanBugman** [comment]
Did Forge devs add back the breaking change in 34.1.32? I'm on it rn and it still seems to be crashing.

**Comment by GirafiStudios** [comment]
Potentially. What crash are you getting? The same one again?

**Comment by BugmanBugman** [comment]
https://hatebin.com/nsczadwvmg
Looks to be the same bug i believe
[latest.log](https://github.com/TeamMetallurgy/Aquaculture/files/5442328/latest.log)

**Comment by DerHofnarr** [comment]
same for me Forge 34.1.32. Worked good with 34.1.25. After updateing Forge and Aqua2 im getting the error :"Aquaculture 2 (aquaculture) has failed to load correctly. java.lang.ExceptionInInitializerError: null" .... Help pls i love this mod!
