### ISSUE TITLE
aquaculture ticking entity error

### ISSUE THREAD

**Issue by DemgelZalvine** [TeamMetallurgy/Aquaculture#153]
### Describe your issue, what happened?
This one was just a random pop, and to be honest likely not very repeatable. Adding it since I already raised the molten glass issue, and may as well add in this one.

### To Reproduce
Unfortunately this hasn't happened again. Adding the crash log just as it exists.
Seems to have occurred at random, not sure if faulty AI behavior or..?

### Expected behavior
Fish being fish

### Crash Reports & Logs (Don't paste entire crash reports here.)
[crash-2020-10-27_23.01.09-server(1).txt](https://github.com/TeamMetallurgy/Aquaculture/files/5457837/crash-2020-10-27_23.01.09-server.1.txt)

### Affected Version
- Pack Version: 1.6.4
- On a server?: Yes.

**Comment by GirafiStudios** [comment]
As there is not really any steps to reproduce it, I can't promise that I've actually fixed it.
You can try out a build here, and see if you still get the crash: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.16/

**Comment by sscards55** [comment]
I don't think that will actually fix it, The  crash happened in the fish entity, taskOwner wasn't null. you would have to override leaveGroup (func_212808_dC), in AquaFishEntity.

**Comment by GirafiStudios** [comment]
leaveGroup is only ever called from the Goal, and if you read that line below in the crash log, that's where the crash origins.

**Comment by sscards55** [comment]
Am I missing something, because from what I saw the crash happened in the entity after being called from Goal?
