### ISSUE TITLE
Valhelsia 2, Not catching any Aquaculture fish

### ISSUE THREAD

**Issue by travisclare** [TeamMetallurgy/Aquaculture#154]
Sorry if im misunderstanding the mod somehow but im using a diamond fishing rod with a golden hood in a deep ocean biome and i havent caught a single aquaculture 2 fish out of like 40 casts, in the Valhelsia 2 modpack on a private server that i am running. Looked through the config files and couldn't find anything that may be related

**Comment by GirafiStudios** [comment]
Please update Aquaculture 2.

**Comment by travisclare** [comment]
Fixed, thank you, 

sorry i should have thought about that.

Thanks for the help. Message me your donation box and ill send  you a couple bucks for your time :)

**Comment by GirafiStudios** [comment]
> Fixed, thank you,
> 
> sorry i should have thought about that.
> 
> Thanks for the help. Message me your donation box and ill send you a couple bucks for your time :)

You're welcome :)
There is a Donate-button on Aquaculture's CurseForge page (On the right-hand side of the page), if you wish to do so :)

**Comment by travisclare** [comment]
Dont see a donation button

**Comment by travisclare** [comment]
https://imgur.com/a/1F0AWu1

**Comment by sscards55** [comment]
It's in the curseforge page not here on github.
[](https://www.curseforge.com/minecraft/mc-mods/aquaculture)

**Comment by travisclare** [comment]
sorry, derped. Was very tired
