### ISSUE TITLE
[Bug] [1.15.2-2.0.22] Neptunium fillet knife doesn't work in crafting table

### ISSUE THREAD

**Issue by radiomike** [TeamMetallurgy/Aquaculture#156]
Using Neptunium fillet knife in crafting table with relevant fish doesn't produce any result - should produce fish fillets. Recipes do appear in JEI. The other fillet knives work as expected.

Came across it in Enigmatica 5 and also tested in fresh instance with just aquaculture installed.

**Comment by GirafiStudios** [comment]
1.15.2 build will be available on CurseForge shortly.
It'll be fixed for 1.16.4, when Aquaculture 2 updates next time (In case somebody else comes to report the same issue)
