### ISSUE TITLE
Lock is no longer valid?

### ISSUE THREAD

**Issue by Tyrius1** [TeamMetallurgy/Aquaculture#157]
https://pastebin.com/2mm7ChNX

One of my testers keeps getting this crash whenever they attempt to load my wip pack.
If they remove aquaculture it launches for them but once they add it back in it will not launch.

Minecraft version 1.16.3
Forge - 34.1.42
Aquaculture - 2.1.6 and 2.1.5 - yet to test further back.

Will do more testing later

**Comment by GirafiStudios** [comment]
Thank you for reporting!
Some further information would be great, as the crash does not really say anything useful.

**Comment by GirafiStudios** [comment]
Closing as not enough information have been provided, and Aquaculture is not mentioned anywhere in the stacktrace in the crashlog

**Comment by sscards55** [comment]
This is a vanilla bug actually.
https://bugs.mojang.com/browse/MC-177491
not fixed apparently.
