### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Yarik124421** [TeamMetallurgy/Aquaculture#158]
The server crashed unexpectedly during the game. I guess the problem is with this mod.
I attach a crash report
[crash-2020-11-17_21.01.42-server.txt](https://github.com/TeamMetallurgy/Aquaculture/files/5555393/crash-2020-11-17_21.01.42-server.txt)

**Comment by GirafiStudios** [comment]
The crash is caused by Performant and/or Fast Util
