### ISSUE TITLE
Suggestions for additional config options

### ISSUE THREAD

**Issue by theJ8910** [TeamMetallurgy/Aquaculture#16]
Here are some suggestions I have for improving cross-mod compatibility, configurability, and addressing other minor issues in Aquaculture.
- Currently, fish that are caught don't stack, presumably because of mismatched "Weight" NBT. A config option to disable this or make it irrelevant to stacking (if possible) would be a nice improvement.
- Being able to configure the loot received from the Box, Lockbox, Treasure Chest, and Neptune's Bounty as a list of (ItemID:meta, weight/rarity) entries.
- Better configuration for catchable fish / junk (fishables). Something like this, with default entries for items added by the mod:

```
S:biome <
    ItemID:meta, weight/rarity
>
```

Where biome is "all", a biome name, BiomeDictionary type, or a biome group (defined elsewhere in the configuration, to reduce the number of redundant entries you'd have to make).
- Config options to enable a recipe for the Aquaculture Wooden Fishing Rod, and different recipes for the iron, gold, and diamond fishing rods (in the case Thermal Foundation or another mod that adds fishing rods with a conflicting recipe is in the user's pack)
- Alternative solution to the above problem: I'm currently solving this issue in my pack by replacing the output of the recipes for the vanilla Wooden Fishing Rod and conflicting Thermal Foundation Fishing rods, making them return Aquaculture fishing rods instead. I then add shapeless recipes that allow you to cycle between an undamaged Aquaculture fishing rod and an undamaged conflicting fishing rod.
- Config option to use Tinkers' Construct tool rods (or any oredict-compatible item) to construct Aquaculture fishing rods instead of ingots. They use oredict entries like "ironRod" and "rodIron" for tool rods.
- Config option to change the smelting recipe for a tin can to return a tin ingot or 4 tin nuggets instead of an iron ingot
- Programmatic configuration of fishables / box loot via a Java API.

(edit: Thermal Expansion -> Thermal Foundation)

**Comment by Shadowclaimer** [comment]
Going to close this but a lot of these were taken into account for future developments. Thank you for your contributions!

**Comment by theJ8910** [comment]
You're welcome, and thank you. I appreciate you taking the time to consider them, and for all the hard work you guys have put into Aquaculture and Metallurgy over the years.

**Comment by Shadowclaimer** [comment]
Thank you! Sorry it was a bit of a late reply, all your points were definitely added to my list of things to look at with configs.
