### ISSUE TITLE
Tenho esse problema

### ISSUE THREAD

**Issue by SERGIO810** [TeamMetallurgy/Aquaculture#160]
![image](https://user-images.githubusercontent.com/74707200/99644527-d1b28f80-2a2c-11eb-840e-e82456ea7837.png)

**Comment by GirafiStudios** [comment]
The lack of data fixers for the entities is not a problem.
Unfortunately there is no way to make them go away in Forge.

**Comment by SERGIO810** [comment]
Thank you very much for the reply, I am new to the community, I hope to
learn from you


Em qui., 19 de nov. de 2020 às 07:13, Girafi <notifications@github.com>
escreveu:
