### ISSUE TITLE
Crash when trying to create a single-player world

### ISSUE THREAD

**Issue by BugmanBugman** [TeamMetallurgy/Aquaculture#162]
https://hatebin.com/oopdcezfij

**Comment by sscards55** [comment]
That crash is for a mouseClicked event, which just so happened to be received as AQ was was doing it's thing, which means it's highly unlikely that AQ was involved.

Is it possible that you can reproduce this crash without JMT MCMT , OptiForge, and Optifne installed?

**Comment by GirafiStudios** [comment]
Yea, the crash is happening on nothing specific in AQ2's code. Does this happen every time you try to create a new world, or did you just try once?
Also FpsReducer is mentioned early on in the stacktrace, so if it happens everytime - it might be worth attempting without that.
