### ISSUE TITLE
[1.16.4] Interesting array of errors in log for singleplayer

### ISSUE THREAD

**Issue by Cixon** [TeamMetallurgy/Aquaculture#163]
**Reproduce:** Load a standard world up in creative and see log?

**Context:** Not sure what the story is behind these errors but I figured it should be something worth noting perhaps it could draw issues with other mods or just vanilla's stability.

I was using a assortment of mods but neither of them changed fish mechanics or anything similar.

### Line 295 - 326
[latest.log](https://github.com/TeamMetallurgy/Aquaculture/files/5578222/latest.log)

**Comment by GirafiStudios** [comment]
You're using Java 14, you should only use Java 8 for Modded Minecraft still.
