### ISSUE TITLE
[TODO] fix sound.json

### ISSUE THREAD

**Issue by sscards55** [TeamMetallurgy/Aquaculture#166]
I'm leaving this here for me to do later.

**Comment by GirafiStudios** [comment]
Aquaculture add zero custom sounds, so not sure what you're on about?

**Comment by sscards55** [comment]
Because you are simply reusing the sounds in vanilla, when a sound plays, the wrong subtitles displays on screen. I'm currently changing the sounds over to "aquaculture" sounds. This will have 2 effects:
1. The correct subtitle will display
2. The sounds can be customized with a resource pack.
