### ISSUE TITLE
Squids and other animals do not spawn.

### ISSUE THREAD

**Issue by JustaGamer0** [TeamMetallurgy/Aquaculture#170]
Vanilla 3D modeled fish and Squid do not spawn underwater, this is for 1.16.4. I have searched far and wide in the lukewarm, warm, and in general just oceans. Turtles do spawn however. I am also just wondering what set difficulty it should be.

**Comment by GirafiStudios** [comment]
Are you saying that both Vanilla and Aquaculture fish do not spawn, or just Aquaculture fish?

**Comment by JustaGamer0** [comment]
I have not seen any aquaculture fish except the swamp turtle spawn. Basically the only thing in the water is drowned and mobs like that. land animals do show up.

**Comment by JustaGamer0** [comment]
Are they more rare on hard mode?

**Comment by GirafiStudios** [comment]
They're not more rare depending on difficulty.
So vanilla fish are now spawning either?

**Comment by JustaGamer0** [comment]
I think I fixed it, it was a mob spawning rule
