### ISSUE TITLE
1.15 ticking entity errors on water mobs

### ISSUE THREAD

**Issue by Inaaca** [TeamMetallurgy/Aquaculture#174]
Regularly (roughly a couple hours or so apart on average) getting server crashes due to entity ticking errors, primarily fish.  Currently running Valhelsia 2 modpack.

**Comment by GirafiStudios** [comment]
Please update Aquaculture 2, Valhelsia 2 is using an outdated version.

**Comment by Inaaca** [comment]
> Please update Aquaculture 2, Valhelsia 2 is using an outdated version.

I just checked, and the Valhelsia 2 modpack is already running the most recent 1.15 version, Aquaculture 2.0.23, so there's nothing to update to.

**Comment by sscards55** [comment]
In that case could you provide logs?
latest.log or debug.log

**Comment by Inaaca** [comment]
@sscards55 Sure, here's the latest.log.  Hope it helps pin down the issue.

[latest.log](https://github.com/TeamMetallurgy/Aquaculture/files/5648195/latest.log)

**Comment by Inaaca** [comment]
@sscards55 Again, not sure if the timing makes a difference, but here's the log file right after the latest ticking entity crash today.

[latest.log](https://github.com/TeamMetallurgy/Aquaculture/files/5648347/latest.log)

**Comment by sscards55** [comment]
According to the second log, the crash is actually with the fastutil mod, there is no mention of Aquaculture in any part of the crash stacktrace, and since the first one is just a normal log there is no crash info there.

**Comment by Inaaca** [comment]
@sscards55 So fastutil is actually the culprit, ok.  Thanks for the help.  I was directed here when looking into the issue, but since it doesn't actually seem to be caused by your mod I'm sorry for the trouble.  Thanks again for helping to narrow down the issue, though.

**Comment by sscards55** [comment]
It might be because water entities can move from basically any point to any point, they're not restricted to the ground. Now that I think about it, I think the same thing could happen with ghasts. 
As for the pointless bugging, don't worry about it. As long as you have logs most devs will point you in the right direction, but just remember to provide logs.

**Comment by Inaaca** [comment]
@sscards55 Alright, I'll keep searching for a solution.  Thanks for the help, though.  I appreciate it.
