### ISSUE TITLE
Fishing not working on multiplayer

### ISSUE THREAD

**Issue by Squid8me** [TeamMetallurgy/Aquaculture#177]
The fishing on the latest version (1.16.4) is bugged on an aternos server. When fishing, when a fish comes towards your rod, and you right click to reel the rod in, the audio queue plays but the rod stays in the water and doesn't give any items. I am fishing with an iron fishing rod, using a double hook, a minnow as bait, orange line, and no bobber.

**Comment by sscards55** [comment]
Aternos offers (Forge + Bukkit) servers, would you happen to be using one of them for your server?

**Comment by Squid8me** [comment]
Yes I am using Forge.

**Comment by sscards55** [comment]
I'm asking if you are using a "Forge + Bukkit" server, not just a Forge server.
If it's just a Forge server, can you provide a mod list and your debug.log

**Comment by GirafiStudios** [comment]
What biome are you fishing in?

**Comment by Squid8me** [comment]
It is purely a Forge server. I am fishing in a river between a roofed forest and a planes biome. I have also tried in a river in the middle of a savannah biome with the same result.
![image](https://user-images.githubusercontent.com/75656756/101532319-39336f00-3949-11eb-82d6-eb7252c89104.png)

**Comment by Squid8me** [comment]
and here is the log https://mclo.gs/Wgjcpj6

**Comment by GirafiStudios** [comment]
The issue is caused by Fanatic Enchantment, which is causing an error in the log.
