### ISSUE TITLE
Support for Forge tags

### ISSUE THREAD

**Issue by whatusernamenottopick** [TeamMetallurgy/Aquaculture#178]
Hi, great mod! 
I'm writing this as I noticed that Aquaculture fish items have the _#minecraft:fishes_ tag on them, but not _#forge:raw_fishes_ (or _#forge:cooked_fishes_ at that). 

Adding the tag _#forge:raw_fishes_ would be **_super helpful_**, as it would allow these fish to be used in almost any recipes added by other mods, not only Pam's Harvestcraft, but also Simple Farming, Farmer's Delight, you name it!

The reason why _#minecraft:fishes_ is simply not enough, is because this tag isn't used by recipes almost anywhere, but also because this tag includes both cooked _and_ raw fish (e.g. both cooked and raw cod use this). I suppose this is why Forge mods use _#forge:raw_fishes_ tag, so please, consider this.

Thanks!

**Comment by whatusernamenottopick** [comment]
I get why it was closed, but I did expect at least a response. Nvm...

**Comment by GirafiStudios** [comment]
It was closed automatically in the commit I made to add what you suggested :) Figured that would be answer enough!

**Comment by whatusernamenottopick** [comment]
Lol, I didn't know! Thanks.
