### ISSUE TITLE
[1.16.4] Game stuck loading the world at 100%

### ISSUE THREAD

**Issue by nbrichau** [TeamMetallurgy/Aquaculture#179]
Hello, the game is stuck on loading the world at 100%.

I'm using :
- Minecraft 1.16.4
- Forge 35.1.0
- Aquaculture 1.16.4-2.1.7
- Oh The Biome You'll Go 1.1.5
- JEI 1.16.4-7.6.0.58.

So the game launch correctly but when I try to create a new world in creative, the loading phase become stuck when at 100%.  
Reading the logs it show that I connect to the world and disconnect automatically.

I tried only BYG and JEI and it worked, Aquaculture and JEI worked too but Aquaculture and BYG conflict each other.  
But I can't know if it is from your mod or BYG, sorry.

You can see debug.log and latest.log here : https://gist.github.com/nbrichau/9ddf2014a05bdd89291efd8995262702

**Comment by GirafiStudios** [comment]
Unfortunately there is not really anything useful in the logs.
I've attempted reproducing the issue with the exact versions of mods you specified, but everything worked just fine for me.

**Comment by nbrichau** [comment]
I tried again after rebooting my computer.  
On GDLauncher and MultiMC, I got the same problem, but on the new Curseforge launcher it worked.  
So that's a problem from these platform or my computer.  

Sorry for the inconvenience.

**Comment by GirafiStudios** [comment]
That's very weird!
Yea I was using the CurseForge launcher to test it too. 
Not really anything I can do about it not working on GDLauncher and MultiMC, without any errors related to it in the log unfortunately though.
