### ISSUE TITLE
[1.16.4]server background told me I should report bugs

### ISSUE THREAD

**Issue by binglingyao** [TeamMetallurgy/Aquaculture#180]
Game version: 1.16.4
Server core: forge-1.16.4-35.1.13
Mod version: Aquaculture-1.16.4-2.1.7
Issues:
- Fishing catches air!
- [18:24:32] [Server thread/ERROR] [aquaculture/]: Loot was empty in Biome: net.minecraft.world.biome.Biome@62542312. Please report on Github

Supplementary information:
- I was just fishing and found out I was catching air.So I went to the server background to check, found this paragraph error.

**Comment by GirafiStudios** [comment]
What biome mods are you using?

**Comment by binglingyao** [comment]
Two are used.
- BiomesOPlenty-1.16.4-13.0.0.425-universal
- Oh The Biomes You'll Go-1.16.4-1.1.5

**Comment by GirafiStudios** [comment]
Would the biome you tried to fish in happen to be from Oh The Biomes You'll Go?
The current latest version does not have BiomeDictionary support unfortunately, which would most likely be your issue. They have fixed it on Github, but have not yet released a new version.

**Comment by binglingyao** [comment]
Thank You, I'm really in The Biomes of Oh The Biomes You'll Go!
I'm not sure if his new version fixes the problem, but I'll give you feedback again after his new MOD is updated and tested, whether or not the problem is fixed.

**Comment by GirafiStudios** [comment]
The new version of Oh The Biomes You'll Go is unfortunately not out yet, so you'll have to wait for that.
You could use version 2.1.6 of Aquaculture 2, until they update, since that relies on another system. But that means it'll not work with a few rare BoP biomes. But might be your best bet until Oh The Biomes You'll Go updates.
