### ISSUE TITLE
[Aquaculture-1.16.4-2.1.7] Client/Server crashes

### ISSUE THREAD

**Issue by Maruhl** [TeamMetallurgy/Aquaculture#181]
Hi, thanks for this great mod. The current version crashes the client/server for me. Version 1.16.4-2.1.6 works on the other hand.

[crash-2020-12-25_12.03.55-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/5741818/crash-2020-12-25_12.03.55-client.txt)

**Comment by GirafiStudios** [comment]
Thanks for the report!
Could you try to see if this happens without the mod "Ice and Fire"?
Also you should really update your Java version, you're using the default version shipped with Minecraft - which can cause issues with mods (Unlikely that it's causing this though, just figured I would mention it)

**Comment by Maruhl** [comment]
Thanks for the quick reply. The hotfix version works.
Which Java version should I use?

**Comment by GirafiStudios** [comment]
Glad it worked! I'll release a new version on CurseForge in a moment then.
Whatever the latest version of Java 8 is :)

**Comment by drakray** [comment]
Hi there, I just got this crash with 2.1.10 when clicking on Single Player
using
W10x64
jre1.8.0_271

MC 1.16.4
Forge 35.1.28
Aquaculture 2.1.10
BunchA'Others

https://pastebin.com/MVhAXJ1r
Win10x64, jre1.8.0_271
