### ISSUE TITLE
[Question] Compatible with Fish-Trap Mod?

### ISSUE THREAD

**Issue by Maruhl** [TeamMetallurgy/Aquaculture#182]
Hi, it's more a question as a issue. I play the mc 1.16.4 with last version of aquaculture (1.16.4-2.1.8) and many many other mods.
The mod "Fish-Trap" is also included. The whole mechanic already worked in the previous versions of MC. So version 1.12.x, 1.14.x and 1.15.x. Now I wanted to try everything in version 1.16.4, I noticed that the traps do not catch any fish from Aquaculture. I am not a Java developer, but for me the code of the mod "Fish-Trap" for fishing looks plausible:

https://github.com/kylertlove/fish-traps/blob/master/forge/src/main/java/net/nerds/fishtraps/blocks/BaseTrap/BaseFishTrapTileEntity.java#L101

Or could the bug be with the mod itself?

**Comment by GirafiStudios** [comment]
It's an issue with the Fish Trap mod, as Aquaculture is just adding additional loot to the vanilla loot table.
Where as the Fish Trap mod (In the code you linked at least), are checking its own loot table within the mod itself
https://github.com/kylertlove/fish-traps/blob/master/forge/src/main/java/net/nerds/fishtraps/blocks/BaseTrap/BaseFishTrapTileEntity.java#L56

**Comment by thepriz** [comment]
Correct, I created my own loot tables for fish-traps but they are not working with the latest version of Aquaculture. I have attached the loottables for fishtraps that include aquaculture. Does anyone see anything wrong with them?


[fish-traps-aquaculture2-data-pack.zip](https://github.com/TeamMetallurgy/Aquaculture/files/5756303/fish-traps-aquaculture2-data-pack.zip)

**Comment by thepriz** [comment]
I figured out my problem. The lootTable format was changed for Aquaculture. I am upgrading my lootTables to be compliant with the new Aquaculture lootTables.

**Comment by Abbathor92** [comment]
thepriz can you upload the loot tables to make fish trap compatible with Aquaculture in 1.16.4?

**Comment by thepriz** [comment]
[fish-traps-aquaculture2-data-pack.zip](https://github.com/TeamMetallurgy/Aquaculture/files/5974149/fish-traps-aquaculture2-data-pack.zip)
