### ISSUE TITLE
Catching no fish [MC 1.16.4]

### ISSUE THREAD

**Issue by DerekM07** [TeamMetallurgy/Aquaculture#184]
I can't catch Aquaculture-specific fish (with rods; I can see them swimming about and have no trouble killing jellyfish with a sword)--it seems as though I'm fishing with the default loot table, plus Aquaculture global items (boxes, neptunium chests). The rod appears to catch nothing when it can't gen an Aquaculture fish item.

I enabled additional logging in the config file and found the following error:

[28Dec2020 11:16:00.008] [Server thread/ERROR] [aquaculture/]: Loot was empty in Biome: net.minecraft.world.biome.Biome@64947609. Please report on Github

I believe I'm only running two biome mods, which are Biomes O' Plenty and Upstream.

Is it possible to fix this or identify a mod conflict?

**Comment by GirafiStudios** [comment]
What biome are you fishing in when getting the error, and what mod is that biome from?

**Comment by DerekM07** [comment]
"Ocean", "River"--I'm going to guess it's Upstream because I've never had a conflict with BOP before and I don't appear to have any other biome mods.

I'll give fishing in some other biomes a shot. Upstream is probably just the rivers and ocean inlets. It would nice if there were a config option to include them.

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 are you using?

Also I've never heard of this "Upstream" mod and am unable to find it on CurseForge.

**Comment by DerekM07** [comment]
Sorry, I'm using the most recent--v2.1.8 and [Upstream](https://www.curseforge.com/minecraft/mc-mods/upstream) v1.0.

**Comment by GirafiStudios** [comment]
Did you check if the issue happend without Upstream?

**Comment by Akitori** [comment]
Upstream is this mod:
https://www.curseforge.com/minecraft/mc-mods/upstream

As for fishing, yes this has happened with me as well. Unsure why it is?

**Comment by Akitori** [comment]
I did more testing. Most of the Biome you will go mod areas are unsupported. (ie: freshwater lakes)

**Comment by majorlanguid** [comment]
I'm actually having the same issue! It's happened on multiple people's PCs.

The mod list we use is:

1. Aquaculture 2
2. Better Animals Plus
3. Builder's Addition
4. Citadel
5. FTB GUI Library
6. Ice and Fire
7. Just Enough Items
8. OptiFine
9. Quickhomes
10. Simple Farming
11. Simply Backpacks
12. Tumbleweed
13. Worldedit
14. Xaero's Minimap
15. Xaero's Worldmap

**Comment by GirafiStudios** [comment]
@Akitori  Yes "Oh the Biomes You'll Go" biomes are currently not working - but it's on their end. They have already fixed it on Github. You can go back to using Aquaculture 2 version 2.1.6 for now, as a workaround - until they update.

@majorlanguid What biomes are you experincing this in? Could potentially be an Ice and Fire issue, but that's just a guess.

**Comment by majorlanguid** [comment]
@GirafiStudios I'm currently testing in an Ocean biome and experiencing it. 

I will occasionally get junk I've noticed. For example, I caught two boxes earlier but then it went back to giving me nothing.

**Comment by GirafiStudios** [comment]
@majorlanguid You're totally right, I'll get a fix out at some point today!
What I said about "Oh The Biomes You'll Go" still applies though.

**Comment by majorlanguid** [comment]
@GirafiStudios Thank you so much! My friends will be happy to hear about the update, one is quite the fishing addict. 

I also just got a message in a bottle, so that's an update to me getting other items.

**Comment by GirafiStudios** [comment]
Going back to Aquaculture 2.1.7 should actually work in your case, as the issue is introduced there. I've tracked down the issue already though and working on a fix.

**Comment by DerekM07** [comment]
@majorlanguid @Akitori - Thanks for the added input, guys.

@GirafiStudios - Thanks for jumping on this so quickly. I'll update if you release a new version and it's still borked with Upstream.

**Comment by GirafiStudios** [comment]
Upstream should be all good, this issue was definetly on Aquaculture 2's side.
"Oh The Biomes You'll Go" might still not work - or maybe only work with some biomes. Until they update.
Release will be out as soon as CurseForge approves it.
