### ISSUE TITLE
[Aquaculture-1.16.4-2.1.9] World creation extremly slow (with Biom Mods)

### ISSUE THREAD

**Issue by Maruhl** [TeamMetallurgy/Aquaculture#185]
Hi, with the current version (1.16.4-2.1.9), takes the creating of a new world in combination with Biom Mods extremely long.
I have tested it together with two Biom Mods:

[BiomesOPlenty (1.16.4-13.0.0.426)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[Oh The Biomes You'll Go 1.1.5](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)

The previous version (Aquaculture-1.16.4-2.1.8), on the other hand, had no performance problems.

**Comment by GirafiStudios** [comment]
Could you try out this build? https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.16/56/
(Might still be building, if you see the reply quickly)

**Comment by Maruhl** [comment]
Yo, this version is much faster.
