### ISSUE TITLE
Game Crashing When Loading Save

### ISSUE THREAD

**Issue by CynicalShrew** [TeamMetallurgy/Aquaculture#188]
I've started having an issue where the game will crash whenever I try to load my save. I looked through the crash report, and saw that the crash was occurring due to this mod. It was working fine last night, so I'm not sure what the issue is. 

https://pastebin.com/CAPX3hVf

Edit: Did some more testing. The testing save file I use is also having the issue. It also crashes if I click "Create a new world", without bringing me to the world creation menu. If I disable Aquaculture, it no longer crashes, so I can confirm that this mod is the cause. I tried using version 2.1.8, but the game still crashes.

Edit 2: Looks like the issue is caused by an incompatibility with the latest version of the Undergarden mod. The last version worked just fine, and updating the mod is what caused the issue, so it looks like it's on their end.

**Comment by drakray** [comment]
I'm having this exact same problem, and can confirm that updating Undergarden from 0.3.8 to 0.4.0 and trying to start a Solo game crash onClick on [Menu/Singleplayer]

**Comment by GirafiStudios** [comment]
Yea it's clearly an issue with Undergarden, they must be doing something wrong with how the registry biomes or set biome registry names.
Made a build with additional null checks, to make it not crash. If one of you could try it out, that would be appreciated!
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.16/58/

**Comment by Divineaspect** [comment]
Woot, that fixed it!

**Comment by Ritzumi** [comment]
I still experiencing the issues on starting dedicated server, however.

https://pastebin.com/HdCk3WmJ

It appeared that applying the same additional check on condition line 125 would do the trick, I guess.

**Comment by quek04** [comment]
hi, Undergarden dev here. I'm not sure what I could've done to make this error happen??

**Comment by quek04** [comment]
in Undergarden 0.4.0 (the newest release) , I added my biomes to the Forge biome dictionary. Could that have something to do with it?

**Comment by GirafiStudios** [comment]
@Ritzumi, yea you're correct. If you disable the debug option in the config, that'll fix it fow now though - as that code won't get called then.

@quek04 I'm not exactly sure, I'll try taking a look though.

**Comment by GirafiStudios** [comment]
@quek04 The problem is that your biome is data pack only, so they're never added to the Forge biomes registry. It wasn't a problem before, since you didn't add your biomes the the biome dictionary - so the code on my end never got called.

I've changed over to relying on the ResourceLocation of the biome RegistryKey instead, since that'll be present for all biomes - also data pack ones.
A new build will hopefully be out sometime today.

**Comment by quek04** [comment]
cool
