### ISSUE TITLE
Infinite fish

### ISSUE THREAD

**Issue by Akitori** [TeamMetallurgy/Aquaculture#189]
https://youtu.be/3CzrjK6E61w

video says a thousand words but if you can't watch.

spam neptunium fishing rod in air 

infinite FISH/CHESTS/whatever

**Comment by sscards55** [comment]
Can you post your config file, please?

**Comment by Akitori** [comment]
wait is it the debug that's causing it?

**Comment by sscards55** [comment]
Most likely, yes.

**Comment by GirafiStudios** [comment]
It is the debug option, enabling the debug fishing for the Neptunium Rod
