### ISSUE TITLE
Crash...(don't know why)

### ISSUE THREAD

**Issue by Maxi90909** [TeamMetallurgy/Aquaculture#191]
https://pastebin.com/vaZqe3ng
Minecraft Starts up  Normal but when I go to my Already made World It Crashes

**Comment by GirafiStudios** [comment]
Please update to Aquaculture 2, version 2.1.11

**Comment by Maxi90909** [comment]
I just did that. Everything is fine now

**Comment by Maxi90909** [comment]
I did that before you said it it was the first thing that came in my mind everything is fine now 👍

Von meinem iPhone gesendet
