### ISSUE TITLE
Unable to join server

### ISSUE THREAD

**Issue by WenXin20** [TeamMetallurgy/Aquaculture#192]
`Minecraft v1.16.4`
`Forge v35.1.28`
`Aquaculture v2.1.11`
[`BYG v1.1.7-Beta-1`](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[`BOP v13.0.0.427`](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)

I am unable to join my server when Aquaculture, Biomes You'll Go, & Biomes O' Plenty is installed. If I remove any of these mods, I can join the server on my first try, but when combined, I am constantly kicked when I try to join the world. I didn't notice anything in the logs, but I am able to reproduce this with these 3 mods.
[Server Log](https://gist.github.com/WenXin20/dbcd76b7205293a97484781773f0b685)
[Client Log](https://gist.github.com/WenXin20/aed24103bce30b3d90464554924da6c7)

![2021-01-09_00 26 28](https://user-images.githubusercontent.com/12000593/104084952-6194de80-5211-11eb-839b-d460cc333719.png)

**Comment by GirafiStudios** [comment]
Thank you for setting up your issue in a very presentable way - and provide mods and version of everything you're using! Wish everybody did it like this, would save a lot of time in a lot of cases.

Tried reproducing the issue with the exact mods and version you were using, without any problems. Tried running it on both a local server and on a dedicated Linux based server (Like you're running it on).

Only thing that I really noticed from the logs, were that you were using an very old version of Java 8 - which could cause various problems. I would recommend making sure you're running the latest version of Java 8.
It could also just be simply the fact that it's taking too long to join (Can be caused by bad internet or bad ping to the server). Setting the JVM parameter "-Dfml.readTimeout=180" on both your server and client might fix it, so that's worth a try :)

**Comment by WenXin20** [comment]
Yeah, it took me a while to figure out what was causing it. I'll try updating java to see if that helps.

**Comment by WenXin20** [comment]
I've updated both java and forge, but I'm still getting disconnected. I've added the timeout to my client. The pebblehost server already has it disabled it seems.

If I remove aquaculture, I can add other mods and connect just fine to the server, but as soon as I add it back, it disconnects me again. So I'm not sure that it's a read timeout issue.

**Comment by GirafiStudios** [comment]
Have you tried using the previous version of Oh The Biomes You'll Go?

**Comment by WenXin20** [comment]
I used v1.1.6 as well, but had the same problem. I haven't tried any previous versions yet though.

**Comment by GirafiStudios** [comment]
Yea version 1.1.6 was what I meant, no reason going further back than that.

Could you try setting up a server on your own PC and see if it happens then too? I'm curious if it perhaps could be caused by the host you're using.

**Comment by WenXin20** [comment]
Just finished getting the local server set up, but it is still disconnecting me.

**Comment by GirafiStudios** [comment]
Could you try turning off fish mob spawning in the config, and see if it still happens?

**Comment by WenXin20** [comment]
Ok, I was able to login on the first try after disabling fish spawning.

**Comment by GirafiStudios** [comment]
Interesting. So it is a thing with it taking too long to load most likely then.
I noticed it says Twitch in the log. Are you still using the old Twitch Launcher, or are you using the CurseForge launcher?

**Comment by WenXin20** [comment]
I'm using the CurseForge launcher.

**Comment by GirafiStudios** [comment]
Alright, good good.
Did you set the "-Dfml.readTimeout=180" on your local server, when trying it there?

**Comment by WenXin20** [comment]
Just tried it with the same results. It only connects if fish spawning is set to false.

**Comment by GirafiStudios** [comment]
Hmm, okay.
Could you try catching a Aquaculture fish (Disabling fish spawning is fine for that). Enabling debug mode in the config and using a Neptunium Rod will allow you to get instant catches - just keep going until you get a Aquaculture fish.
Will help me track down what code exactly your setup doesn't like.

**Comment by WenXin20** [comment]
I don't see anything printed in the log when fishing, even with debug enabled in the config.
[Client Log](https://gist.github.com/WenXin20/e1d03283a879785e6f261a8529087104)
[Server Log](https://gist.github.com/WenXin20/9ac186a5008da637e3d5f20cfddb9433)

**Comment by GirafiStudios** [comment]
What I wanted you to test is if you were able to catch an Aquaculture fish - as some of the same code is used for the fish spawning.

**Comment by WenXin20** [comment]
Oh, yeah, I was able to catch fish.

**Comment by GirafiStudios** [comment]
Just noticed. You're still using the built-in version of Java on your client.
Here's how you change it:
- Press "Play" on your instance in the CurseForge launcher
- When the Minecraft Launcher opens, click "Installations" at the top
- Select the one called the same as your instance
- Select "More options"
- Under "Java Executable", click on "browse"
- Point it at your Java installation, which would most likely be somewhere like "Program Files\Java\jre1.8.0\bin\javaw.exe"

**Comment by WenXin20** [comment]
I changed it to "Program Files (x86)\Java\jre1.8.0_271\bin\javaw.exe", but it won't launch with it.

**Comment by GirafiStudios** [comment]
Does it throw any sort of error, or?

**Comment by WenXin20** [comment]
This is what pops up:
![Capture](https://user-images.githubusercontent.com/12000593/104109899-022de180-5298-11eb-9b51-7dccea4f04b4.PNG)

**Comment by GirafiStudios** [comment]
Apparently CurseForge does not save it, after you've set it.. So I guess you're forced to using an ancient version of Java atm.
But that's not the problem then, as I was using the CurseForge launcher too.

Could you try using this version? https://mega.nz/file/NAg3hSiI#TWyGSFFxr9Vubuc3XdXrRMbdgNnBdr9ffAD-pUEV62Q
With fish spawning enabled. It's not a fix, I'm just curious if that would work. If that works, that means that it's the large amount of biomes that's causing it.

**Comment by WenXin20** [comment]
Yep, that worked.

**Comment by GirafiStudios** [comment]
Alright, thanks!
I'll try to work something out. It's very difficult, as I don't a lot to go on - but at least I have some now.
If you haven't already, could you try allocating more RAM for the instance?

**Comment by WenXin20** [comment]
Cool, thanks!
And I've already given it 9GB for ram, since I usually run it with a modpack.

**Comment by GirafiStudios** [comment]
That should be more than enough yea.
I've tried moving some of the code to during load time, instead of on world join. Should help performance overall, hopefully it'll be enough to solve your issue.
https://mega.nz/file/Qcx0FZAC#yM39ABaOdSyjd8tJBRw1HiDFVR5akjBlGpzv9KVwtXY

**Comment by WenXin20** [comment]
I think that fixed it. :) 
I was able to join on the first try.

**Comment by GirafiStudios** [comment]
Really!? Perfect then!
Just to make sure, are you finding any Aquaculture fish spawns? Probably easiest in an ocean biome. If you're not quite sure if it's an Aquaculture fish or not, Middle-Click on it - if it gives you a Fish in a Bucket, it's an Aquaculture fish :)

**Comment by WenXin20** [comment]
Yep, they're spawning. It was fun using the `/tp @e WenXin2` command. :D

**Comment by GirafiStudios** [comment]
Sounds good :) Clever use of that command, never thought about it being used like that!
Thank you very much for being willing to help track down the issue!
A lot of the time people don't want to put any effort into their issue being resolved.

**Comment by WenXin20** [comment]
No problem!
