### ISSUE TITLE
made for an older version of minecraft

### ISSUE THREAD

**Issue by creepychaos99** [TeamMetallurgy/Aquaculture#193]
I'm currently running the latest version of aquaculture 2 (1.16.4-2.1.12) and every time I try to create a world I get an error message "made for an older version of Minecraft", even though I'm on version 1.16 of minecraft. I also have forge version 1.16 and im not sure if there is a problem with the mod or my minecraft or forge.

**Comment by GirafiStudios** [comment]
You're using a resourcepack that's not updated to 1.16.4
