### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by elkorsario** [TeamMetallurgy/Aquaculture#194]
Minecraft v1.16.4
Forge v35.1.36
Aquaculture v2.1.12

Hello.
When entering my server I get this message:
https://prnt.sc/wmc1vx

Here is my console clipping:
https://pastebin.com/5Mjdwcpv

please help

**Comment by sscards55** [comment]
I'm fairly certain that this is an incompatibility issue with Sponge and Forge.

**Comment by elkorsario** [comment]
Sponge is not installed

**Comment by GirafiStudios** [comment]
Could you provide your client log too, when that happens?

**Comment by elkorsario** [comment]
[latest.log](https://github.com/TeamMetallurgy/Aquaculture/files/5807956/latest.log)
@GirafiStudios

**Comment by GirafiStudios** [comment]
You're running in offline mode, which means you most likely don't have a valid account.
We do not provide any sort of support in those such cases.
