### ISSUE TITLE
Crash after loading World

### ISSUE THREAD

**Issue by Maxi90909** [TeamMetallurgy/Aquaculture#198]
When the world finished loading in the upright in a Blue box there is shown ;,world loading failed'' and when I try to join the world again, this is the crash report I get
https://pastebin.com/5KF7rJ8d

**Comment by GirafiStudios** [comment]
Update Aquaculture 2, it _should_ fix your crash.

**Comment by Maxi90909** [comment]
Bruh I am literally on version Aquaculture-1.16.4-2.1.12.jar the newest version

**Comment by Maxi90909** [comment]
Go check my crash report

**Comment by GirafiStudios** [comment]
You're on 2.1.11 in the crash report.
![image](https://user-images.githubusercontent.com/6305377/106147697-79a8af80-6178-11eb-975b-747504a73ea5.png)

**Comment by Maxi90909** [comment]
I Just updated and it still happens

**Comment by GirafiStudios** [comment]
Please Pastebin the crash with 2.1.12 then.

**Comment by Maxi90909** [comment]
I will do give me a second

**Comment by GirafiStudios** [comment]
Also if you could provide your Aquaculture config, that would be great.

**Comment by Maxi90909** [comment]
[aquaculture config.txt](https://github.com/TeamMetallurgy/Aquaculture/files/5887824/aquaculture.config.txt)
https://pastebin.com/VK24rUHQ
Sorry that this took so long my minecraft loads very long

**Comment by Maxi90909** [comment]
I think this crash is something else and not aquaculture correct me if I am wrong

**Comment by GirafiStudios** [comment]
Yea, that crash is different from the one you first reported. My best guess is that it has something to do with an issue in Forge in the 2 latest builds. Try going back to Forge version 36.0.7 or 36.0.6

**Comment by Maxi90909** [comment]
Ok thank you I also will report this to vamiprism because it might be also that. Thank you for your Support
