### ISSUE TITLE
Turtles dont spawn/config file resets 1.16.4/2.1.12

### ISSUE THREAD

**Issue by InfinitysDaughter** [TeamMetallurgy/Aquaculture#200]
The 2 turtles that spawn in vanilla Jungles and Swamps dont spawn at all. I tried changing the biome names in the config file (I used the tellme mod to get the biome names) and it saves initially but when the game starts again, the config file resets to default again.

**Comment by GirafiStudios** [comment]
The config does not support biome names, but Biome Dictionary types. Can be found here: https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L52-L102
And yes they do spawn, they're just not too common with the default values - can increase the weigh if you want them to appear more often.

**Comment by InfinitysDaughter** [comment]
Apologies, I didn't mean to come off confrontational. It might be a good idea to put the distinction between biome and biome type somewhere for future reference, I had no idea there even was a thing.

And also, apologies. I had cranked all the settings for the box turtle to max but it wouldn't spawn. I sought out a new swamp biome and flew around for 20 minutes and then they suddenly started spawning out the wazoo. Minecraft and their weird spawn system. Thank you much and wonderful mod.
