### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by timjevans** [TeamMetallurgy/Aquaculture#201]
I have a server that has all the mods 6 on it newest update, and it was really laggy and kept crashing saying a tick took 60 seconds spoke to the server host and they checked the crash log and said "The problem is with your mod aquaculture  with Boulti entity at 167.40, 54.88, 172.31 you'll want to contact the mod author about this."
I will attach the mcpaste.io [Crash log](https://mcpaste.io/8707ea47be050d96) please could you help with this

**Comment by GirafiStudios** [comment]
Removing the mod Performant, should fix your problem.
