### ISSUE TITLE
Ore Dictionary support for cross-mod compatibility

### ISSUE THREAD

**Issue by MarioSMB** [TeamMetallurgy/Aquaculture#203]
The extra fish added by this mod are not included in the ore dictionary, making it very time consuming to catch only the vanilla fish for use in other recipes (and in the case of Wyrmroost, to tame certain dragons).

**Comment by sscards55** [comment]
What version of the mod are you using? Which ore dictionary entry are you referring to? On the currently latest version of the mod (2.1.12), all of the fish that can be caught are in the "forge"raw_fish" tag list.

**Comment by MarioSMB** [comment]
Thanks for the hasty response, I'm running the latest version (2.1.12) on a 1.16.5 server. The issue appears to be that it lacks the `forge:rawmeats` tag, which Pam's HarvestCraft makes use of (vanilla fish are listed with this tag).

**Comment by GirafiStudios** [comment]
I will not add support for tags, that does not follow naming standards. Which means almost all of the Pam's Harvestcraft tags.
You can add them yourself with a resourcepack/data pack if you wish.
