### ISSUE TITLE
Neptune's Bounty not working

### ISSUE THREAD

**Issue by ItamarDenkberg** [TeamMetallurgy/Aquaculture#204]
This issue has only started today, yesterday when I got the Neptune's Bounty everything worked, and I got my reward.
Today, I got 3 Neptune's Bounties and in each one of them I got nothing.
Is it just me being very unlucky, or is it not supposed to happen?

https://user-images.githubusercontent.com/54473379/107142277-5a5b1080-6936-11eb-988c-a796d03717ba.mp4

**Comment by GirafiStudios** [comment]
Neptune's Bounty should always contain something when caught.

Have you caught it with a fishing rod, or used some kind of fishing trap/auto fisher mod?

**Comment by ItamarDenkberg** [comment]
I caught it with a diamond fishing rod from aquaculture.

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 are using?
Also, could you provide a video of you showing the tooltip of it, before placing and opening it?

**Comment by ItamarDenkberg** [comment]
The modpack I'm playing is using version Aquaculture-1.16.4-2.1.12.jar

https://user-images.githubusercontent.com/54473379/107156906-ae431500-6989-11eb-9a84-9184d37a387e.mp4

**Comment by GirafiStudios** [comment]
Thanks for the updated video!
Is the modpack publically available by any chance?

**Comment by ItamarDenkberg** [comment]
Yes, here's the link: https://www.curseforge.com/minecraft/modpacks/epsilon

**Comment by GirafiStudios** [comment]
Unable to reproduce the issue using Epsilon
![image](https://user-images.githubusercontent.com/6305377/107164278-b06b9a80-69ae-11eb-942a-c3b17fa14b3b.png)
Are you playing singleplayer or on a server?

**Comment by ItamarDenkberg** [comment]
Yes, I am playing on a server. Is the mod not working well with Mohist 1.16.5 or any of these plugins?
![image](https://user-images.githubusercontent.com/54473379/107184951-2e996280-69ea-11eb-8386-920a0f3d0458.png)

**Comment by GirafiStudios** [comment]
That's your problem then. Any of those Bukkit/Forge hybrid always causes a lot of issues, and there is never anything the mod can do about fixing the problem.
