### ISSUE TITLE
[1.16.5] Pam's Harvestcraft Compatibility

### ISSUE THREAD

**Issue by Flexico** [TeamMetallurgy/Aquaculture#205]
Could you please register your fish as "forge:rawfish" so they can be compatible with Pam's Harvestcraft recipes?

**Comment by GirafiStudios** [comment]
I'm not gonna support any of Pam's Harvestcraft horrible tags, that does in no way follow naming stantards - as stated in https://github.com/TeamMetallurgy/Aquaculture/issues?q=is%3Aissue+is%3Aclosed
We have our fish in forge:raw_fishes, which is used by other mods. https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/resources/data/forge/tags/items/raw_fishes.json

**Comment by Theworldofaffe** [comment]
is there any way to change these tags manually?

**Comment by GirafiStudios** [comment]
Yes, you can always add new ones with a Resourcepack/Datapack, like you would with any vanilla stuff

**Comment by IceflowRE** [comment]
if you use CraftTweaker
```zs
var add_tag = [<item:aquaculture:arapaima>, <item:aquaculture:atlantic_cod>, <item:aquaculture:atlantic_halibut>, <item:aquaculture:atlantic_herring>, <item:aquaculture:bayad>, <item:aquaculture:blackfish>, <item:aquaculture:bluegill>, <item:aquaculture:boulti>, <item:aquaculture:brown_shrooma>, <item:aquaculture:brown_trout>, <item:aquaculture:capitaine>, <item:aquaculture:carp>, <item:aquaculture:catfish>, <item:aquaculture:muskellunge>, <item:aquaculture:pacific_halibut>, <item:aquaculture:perch>, <item:aquaculture:pink_salmon>, <item:aquaculture:piranha>, <item:aquaculture:pollock>, <item:aquaculture:rainbow_trout>, <item:aquaculture:red_grouper>, <item:aquaculture:red_shrooma>, <item:aquaculture:smallmouth_bass>, <item:aquaculture:synodontis>, <item:aquaculture:tambaqui>, <item:aquaculture:tuna>];

for item in add_tag {
    <tag:items:forge:rawfish>.add(item);
}
```

**Comment by Flexico** [comment]
> if you use CraftTweaker
> 
> ```zenscript
> var add_tag = [<item:aquaculture:arapaima>, <item:aquaculture:atlantic_cod>, <item:aquaculture:atlantic_halibut>, <item:aquaculture:atlantic_herring>, <item:aquaculture:bayad>, <item:aquaculture:blackfish>, <item:aquaculture:bluegill>, <item:aquaculture:boulti>, <item:aquaculture:brown_shrooma>, <item:aquaculture:brown_trout>, <item:aquaculture:capitaine>, <item:aquaculture:carp>, <item:aquaculture:catfish>, <item:aquaculture:muskellunge>, <item:aquaculture:pacific_halibut>, <item:aquaculture:perch>, <item:aquaculture:pink_salmon>, <item:aquaculture:piranha>, <item:aquaculture:pollock>, <item:aquaculture:rainbow_trout>, <item:aquaculture:red_grouper>, <item:aquaculture:red_shrooma>, <item:aquaculture:smallmouth_bass>, <item:aquaculture:synodontis>, <item:aquaculture:tambaqui>, <item:aquaculture:tuna>];
> 
> for item in add_tag {
>     <tag:items:forge:rawfish>.add(item);
> }
> ```

Oh, that's exactly what I needed! Thanks a bunch~
