### ISSUE TITLE
Riptide III Trident & Depth Strider III Neptunium boots

### ISSUE THREAD

**Issue by youngchan01** [TeamMetallurgy/Aquaculture#206]
I tried using a Riptide III Trident with Neptunium Boots enchanted with Depth Strider III.
I realize you only travel around 9 blocks per Trident use with the Neptunium Boots on, but without the boots on you travel around 15 blocks of distance.
Due to how the Neptunium Boots are supposed to make you swim faster, I think this wasn't intentional.

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 are you using?

**Comment by youngchan01** [comment]
Aquaculture-1.16.4-2.1.12.jar

**Comment by GirafiStudios** [comment]
Fixed general issues with the speed modifier not working properly with Depth Strider here https://github.com/TeamMetallurgy/Aquaculture/commit/055414f6da6d36d7799860530f65bc4b2931a7f3
The issue with Depth Strider and a Trident with Riptide not working properly together seems to be a vanilla (or Forge) issue, as I'm able to reproduce it when wearing vanilla boots with the Depth Strider enchantment, so I can't really do anything about that.
