### ISSUE TITLE
[1.16.5] Unable to place leech in brewing stand

### ISSUE THREAD

**Issue by MarioSMB** [TeamMetallurgy/Aquaculture#207]
JEI lists brewing recipes with the leech (potion of healing), however it cannot actually be placed into a brewing stand.

**Comment by sscards55** [comment]
What version of Aquaculture do you have, and do you have any other mods installed (besides JEI)?

**Comment by MarioSMB** [comment]
I am using Acquaculture version 2.1.13 (we have not updated the server to the latest version yet), and I am indeed running several other mods. I'm not sure how another mod would be interferring with this recipe, but I can provide a list if needed.

**Comment by sscards55** [comment]
if you can provide a list, it would be great, and if you could also mention your version of forge. There are mods like Apotheosis and CoFH that change how potions work, it might be the case here as well.

**Comment by MarioSMB** [comment]
Funny enough, I have a list of the mods along with a crash report, a random crash during load is pointing at this mod:
https://paste.ubuntu.com/p/6cs4MVJ2H4/

**Comment by GirafiStudios** [comment]
As sscards said, it's most likely a mod messing with the brewing, as it works just fine with Aquaculture 2 on its own.
![image](https://user-images.githubusercontent.com/6305377/107511989-811f7e00-6ba6-11eb-8ab8-64ea0ad1d7f8.png)

As for that crash report, that's not related at all. Does that crash happen everytime you launch the game, or?

**Comment by MarioSMB** [comment]
The crash was a one time thing, so likely difficult to reproduce. I'm not sure which mod could possibly interfere with the recipe like that, I'd imagine it would be a very tedious process to find out....

**Comment by GirafiStudios** [comment]
Would you happen to have the modpack on the CurseForge launcher? If so, could you export the modpack and send it?

Also just to be sure - are you playing on a server?

**Comment by MarioSMB** [comment]
I am playing on a server, here is the exported pack:  
[Mario Modpack-0.2.zip](https://github.com/TeamMetallurgy/Aquaculture/files/5958698/Mario.Modpack-0.2.zip)

**Comment by GirafiStudios** [comment]
Could you try in singleplayer, and see if your issue still persists then?

**Comment by MarioSMB** [comment]
I can confirm that the issue persists in singleplayer.

**Comment by GirafiStudios** [comment]
Was able to reproduce the issue as well, with the set of mods you provided.
Tracked it down to be caused by Dungeon Gear. At least disabling just that mod fixes it.

**Comment by MarioSMB** [comment]
Thanks for the heads up, I'll report the issue there.
