### ISSUE TITLE
End fishing

### ISSUE THREAD

**Issue by GalteXx** [TeamMetallurgy/Aquaculture#208]
G' day
So, I didn't really consider this as a problem(due to many other mods doing wierd thing as well), but console asked me to report it.
"Loot was empty in Biome: minecraft:the_end. Please report on GitHub"

When i was fishing at the End, some wierd things happen. I RMB my fishing rod at a perfect time, and get nothing. However, with very same rod i can get vanilla fish(with weight modificator) and fish from "Fins and Tails" and even boxes from Aquaculture. But no fish.

(For whatever reason i will add that i have Better end, but I didn't try fishing in added biomes)

**Comment by GirafiStudios** [comment]
What fishing rod were you using?
Were there any water in the end?

**Comment by GalteXx** [comment]
1.
Lure III diamond fishing rod, yellow reel, cyan float, worm and a gold hook
2.
Man made hole 3x2x2 (top layer has only water sources) 42 blocks under ground (y : 20)

**Comment by GirafiStudios** [comment]
In vanilla you can fish normally in the end (Except stuff that requires certain biomes), the same is the case in Aquaculture 2.
The warning you were getting, means that that Aquaculture was attempting to fish some biome specific loot up but failed to do so. As it's intended that you don't get Aquaculture fish in The End, I'll change it so if you're "supposed" to catch a fish and are in the end, you'll fish up Fish Bones instead.
