### ISSUE TITLE
[1.11.2] Message In A Bottle Null Pointer Exception

### ISSUE THREAD

**Issue by Balketh** [TeamMetallurgy/Aquaculture#21]
Forge 2282, MC 1.11.2.

No crash persay, but on use of a message in a bottle, in chat it stated, for the message, 'Null Pointer Exception; Aquaculture.MessageInABottle (String) cannot be null.'

Sounds like it might not be the hardest fix, but, still worth reporting.

**Comment by Shadowclaimer** [comment]
This is actually a fake error message, its one of the joke strings that come out of a message in a bottle.

**Comment by Balketh** [comment]
Amazing! Had no idea, was very confused as to why it didn't log it or crash or anything of the like. Well played. XD
