### ISSUE TITLE
Server start crash

### ISSUE THREAD

**Issue by BaldAgent** [TeamMetallurgy/Aquaculture#211]
[crash-2021-02-16_01.06.48-fml.txt](https://github.com/TeamMetallurgy/Aquaculture/files/5984338/crash-2021-02-16_01.06.48-fml.txt)

Please help me.
When I start Minecraft Server I see this crash.
Also, there is no problem in singleplayer.

**Comment by GirafiStudios** [comment]
Honestly I have no clue why it's crashing there.
My best initial guess would be to remove Optifine and OptiForge?

**Comment by BaldAgent** [comment]
Well it's worked! Thank u so much!
