### ISSUE TITLE
[Bug] Incomplete tags

### ISSUE THREAD

**Issue by yomisimie** [TeamMetallurgy/Aquaculture#214]
I created a custom server with some mods and aquaculture 2 but when i try to connect i receive this error. I disabled all the mods and tried only with this and still getting the error.

`Incomplete set of tags received from the server.`

Minecraft: 1.16.5
Forge: 36.0.43

**Comment by GirafiStudios** [comment]
Are you using some sort of Forge/Bukkit thing to run your server?
And are you sure you have Aquaculture 2 on both your server and your client?

**Comment by yomisimie** [comment]
Yes, I am using Forge 36.0.43 on both server and client and also Aquaculture 2 on both server and client.

**Comment by yomisimie** [comment]
Tried it for the 5th time, have no ide what I did different, but no error this time. Same setup.
