### ISSUE TITLE
[1.16] Minnow does not have a fillet recipe.

### ISSUE THREAD

**Issue by ktreus** [TeamMetallurgy/Aquaculture#215]
Like the title said, issue easily reproducible

Way to reproduce: Put any fillet knife onto crafting grid together with a Minnow, you don't get the output expected.

**Comment by GirafiStudios** [comment]
Intended. Due to Minnows size, they're not suitable for filletting. However they're used for bait instead, as described on our [wiki](https://github.com/TeamMetallurgy/Aquaculture/wiki/Fish)
