### ISSUE TITLE
[Suggestion] Add a reeling minigame mechanic like many older fishing mods did.

### ISSUE THREAD

**Issue by Corvus20** [TeamMetallurgy/Aquaculture#216]
The 1.12.2 mod "better fishing", and its continuation "fishing made better" implemented a fun minigame for reeling fish in when they bite, giving it too much slack or reeling it in too fast would result in the fish getting away or the line snapping. These mods have been abandoned in 1.12.2, so there is no modern equivalent. Implementing these mechanics would give the mod something I felt like it was lacking, more engaging fishing rather than just waiting to right click when the bobber goes down.

**Comment by GirafiStudios** [comment]
Thank you for your suggestion!
That's way out of scope of what Aquaculture wants to do. We try to stay as close to vanilla as possible, which this would be very far from.
