### ISSUE TITLE
(1.16) Internal Exception

### ISSUE THREAD

**Issue by jellysplatter** [TeamMetallurgy/Aquaculture#217]
Im running a budget Bisect server to play with my friends, but everytime I activate this mod I get the same error:
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Unknown recipe serializer
aquaculture:crafting_special_fish_fillet

If you need any additional information to find the bug, lmk. Your mod is very intriguing, and I would love to use it!

![Int](https://user-images.githubusercontent.com/80235485/110271546-4b4b9a80-7f96-11eb-8cee-6a2a9ddb67f2.PNG)

**Comment by sscards55** [comment]
Do you have the mod installed on both the client and the server? Are you using a pure forge server or a Bukkit hybrid?

**Comment by jellysplatter** [comment]
Yeah, it's installed. I have other mods on the server, and they run fine. But for some reason its solely just this one that's giving me problems. I'm using a Forge 1.16.4 JAR to run the server

**Comment by GirafiStudios** [comment]
What Forge version are you using?

**Comment by jellysplatter** [comment]
Its a custom 1.16.4 jar version of Forge.

**Comment by GirafiStudios** [comment]
Could you try with this Jenkins build of Aquaculture 2? (Once it's done building, if you see this reply quickly)
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.16/78/

**Comment by jellysplatter** [comment]
I tried your build, but it came back with crash reports. Here is the output
![weird1](https://user-images.githubusercontent.com/80235485/110374359-9a3d1280-801e-11eb-9248-f7222206328b.PNG)
![weird2](https://user-images.githubusercontent.com/80235485/110374371-9c9f6c80-801e-11eb-90dd-a806a438bdd2.PNG)
![weird4](https://user-images.githubusercontent.com/80235485/110374379-9dd09980-801e-11eb-9a74-20fb0c1f3de8.PNG)
![weird5](https://user-images.githubusercontent.com/80235485/110374394-a0cb8a00-801e-11eb-813e-4e68643f1fc6.PNG)

**Comment by GirafiStudios** [comment]
The version of Forge you're using is older, than the version of Forge required to run Aquaculture 2 now.

**Comment by jellysplatter** [comment]
Should I download the 1.16.5 version of Forge?

**Comment by GirafiStudios** [comment]
Yes. We require version 36.0.42 or newer, of Forge.

**Comment by jellysplatter** [comment]
The server is working properly now and it is now compatible. Thanks for the explanation!

**Comment by GirafiStudios** [comment]
Glad you issue was resolved!
