### ISSUE TITLE
[1.12.2] No fishes

### ISSUE THREAD

**Issue by Megfogszhalsz** [TeamMetallurgy/Aquaculture#218]
Hey, I made a modpack where I use the same mods as my other modpack, the only difference is it has the Realistic Terrain Generation (RTG) as well.
Somehow fishes aren't spawning around the world, the problem is the same when I don't use the RTG world type.
Since I didn't found anything on internet about the incompatibilities of the Aquaculture 2, may I ask for known issues about incompatibility, thus I could search for the problem?

Note: the items and the fishing system remains, so I can go fishing anytime, only the entities are missing

**Comment by GirafiStudios** [comment]
Please read the CurseForge page more carefully.
Aquaculture (1) is for 1.12.2 and before, which DOES NOT have fish entities, that's a thing that got added in Aquaculture 2 (1.14+).
