### ISSUE TITLE
[1.11.2] Admin Rod doesn't reel properly

### ISSUE THREAD

**Issue by Balketh** [TeamMetallurgy/Aquaculture#22]
Forge 2282.
AQ Version 1.5.0.33

On use in water, the Admin fishing rod doesn't seem to retract at all, and requires either dropping or wielding a different item to cancel its cast. Right clicking just causes it to play the swipe animation, and it otherwise doesn't seem to respond to any kind of fish interaction.

**Comment by darthvader45** [comment]
There's a newer version out now, try that and see if the same problem occurs.
