### ISSUE TITLE
Suggestion: Config option to make Neptunium gear unbreakable

### ISSUE THREAD

**Issue by unmoving-javi** [TeamMetallurgy/Aquaculture#220]
Last time I was admittedly too vague about what I was requesting, so here's a proper write-up.

It would be nice if there was a config option to make Neptunium gear _unbreakable_ like the fillet knife is. This would be especially nice if it was toggleable per-piece of Neptunium gear, so the rod and tools could be made unbreakable but still letting the armor break as usual.

This would allow for more configuration on the side of modpacks, and while admittedly an unbreakable neptunium rod might be a bit overpowered, it'd at least be nice to have the option.

And. of course, sorry for the vague topic last time.

**Comment by sscards55** [comment]
If it's for a modpack it can be easily one with datapacks, just make it so that the recipe outputs the item with the unbreaking enchant. as for the loot it can also be done with a datapack. make the item have the unbreaking enchant in the loot stack.

**Comment by sscards55** [comment]
If you're not comfortable with messing with datapacks it can also be done with CraftTweaker, if that's easier for you.

**Comment by TopPercentageRattata** [comment]
I believe theres an unbreakable attribute you can apply to tools, so no need to add absurd levels of unbreaking enchantment

**Comment by GirafiStudios** [comment]
No plans to add an option like that, no.
Seems like you have other ways of doing it, as suggested above.
