### ISSUE TITLE
Cannot edit the config file. Reverts to settings before I edited 1.16.5

### ISSUE THREAD

**Issue by Rukia1727** [TeamMetallurgy/Aquaculture#221]
As it says, cannot edit the .toml file at all. If I change the fishing weight setting to true it reverts it to false when I load a world OR create a new world. I cannot edit the config file at all

**Comment by Rukia1727** [comment]
Also it creates a file called aquaculture-common.toml.bak

**Comment by GirafiStudios** [comment]
What Aquaculture 2 version are you on?

**Comment by GirafiStudios** [comment]
Closing, because of no response.
Make sure you're using Aquaculture 2.1.16, as it was an issue on older versions, with newer versions of Forge.
