### ISSUE TITLE
incompatible with 1.16.5

### ISSUE THREAD

**Issue by liberatingpanda** [TeamMetallurgy/Aquaculture#222]
Hi team, i recently downloaded aquaculture 2 1.16.5 but when i add to my resource packs it says that it is incompatible. am I missing something?

**Comment by GirafiStudios** [comment]
It's a problem with your resourcepack, that's not updated.
The mod is 100% functional for 1.16.5

**Comment by liberatingpanda** [comment]
> It's a problem with your resourcepack, that's not updated.
> The mod is 100% functional for 1.16.5


Aquaculture-1.16.5-2.1.16.jar ... this was the version that I dl from curseforge

**Comment by sscards55** [comment]
You need to find update your resource pack. The mod is updated but the resourcepack is not updated
