### ISSUE TITLE
Multiple rolls for loot box loot-tables are not working

### ISSUE THREAD

**Issue by DuraBrite** [TeamMetallurgy/Aquaculture#223]
Hey,
I was trying to edit the loot_tables for the different loot boxes. Therefore I injected the updated loot-table file into data/aquaculture/loot_tables/box/box.json using kubejs. Updating the items works fine. However, changing the number of rolls has no effect. Below you can see a sample loot-table I made. I expected that it would roll 3 times and give me 3 of the provided entries. Instead I only get one entry. Is there any way to change this behavior? Or am I doing something wrong?

```
{
  "pools": [
    {
      "name": "aquaculture:box_loot",
      "rolls": 3,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:stone"
        }
      ]
    }
  ]
}
```

Forge-Version: forge-36.1.2
Mod-Version: Aquaculture-1.16.5-2.1.16
Other Mods: kubejs-1605.3.6-build.177-forge, rhino-1.7.13-build.14.jar

**Comment by GirafiStudios** [comment]
You can't have additional rolls for fish loot, that's just not how vanilla works. Only works for cases such as chest loot etc.
