### ISSUE TITLE
Warn on my server

### ISSUE THREAD

**Issue by AffectAge** [TeamMetallurgy/Aquaculture#224]
[16:10:23 WARN]: defineId called for: class net.minecraft.entity.projectile.EntityFishHook from class com.teammetallurgy.aquaculture.handlers.EntityCustomFishHook

Hi. I have this warning message on my server. How i can fix that?

**Comment by GirafiStudios** [comment]
What Minecraft version are you on?

**Comment by AffectAge** [comment]
> What Minecraft version are you on?

1.12.2

**Comment by GirafiStudios** [comment]
That's not a problem then, that will always show up :)

**Comment by AffectAge** [comment]
> That's not a problem then, that will always show up :)

So i can just hide message without problem?

**Comment by GirafiStudios** [comment]
Yes.
