### ISSUE TITLE
[Feature] More Config

### ISSUE THREAD

**Issue by Camawama** [TeamMetallurgy/Aquaculture#225]
Hi, I run a modded server and have a modpack in active development. I was wondering if there was any way to modify how powerful neptunium is. It kind of just ruins progression in my modpack but I love the other features the mod has to offer. Is there a way to nerf said items?

**Comment by sscards55** [comment]
if you want to restrict an item to a player based on progression you can use mods like [Game Stages](https://www.curseforge.com/minecraft/mc-mods/game-stages) and [ReSkillable](https://www.curseforge.com/minecraft/mc-mods/reskillable) depending on the version you are on.

**Comment by GirafiStudios** [comment]
You can turn of Neptunium stuff completely in the config. You can also do as sscards suggested, if you still want it in.

**Comment by Camawama** [comment]
The thing is, I don't want to completely disable it as I already have people who have dedicated their time to acquire said loot. I just feel it is way to powerful compared to other loot in the modpack. I simply would like to nerf the damage dealt, that's all.

**Comment by GirafiStudios** [comment]
There is mods out there that modify armor/tool/weapon attributes, I can't recall their name(s) though.

**Comment by Camawama** [comment]
dang, that's unfortunate....I guess I'll start looking around after work. If you find it, please let me know!

**Comment by Camawama** [comment]
If this is the mod you were referring to, they only support 1.12 ☹️

**Comment by Camawama** [comment]
Could you please at least add a config to tweak the damage of the neptunium axe and that only? It's the only thing I feel is  "too op". Please?
