### ISSUE TITLE
[Suggestion] Fillet Knife improvements

### ISSUE THREAD

**Issue by MarioSMB** [TeamMetallurgy/Aquaculture#228]
In the spirit of consistency and reducing redundancy, I believe it would be worthwhile to remove the current tiered fillet knife setup in favour of having a single Fillet Knife item crafted with flint, for the following reasons:  
- Flint is a severely underutilised material, which is most commonly associated with the sea floor and accessible in any place one can obtain fish, making it a rather fitting material for a fillet knife
- The scope of the tiered system is quite limited in a sense; it only uses the stock tool materials (though skipping netherite), leaving some inconsistency with viable materials in modded environments, which often provide many different types of tool materials (not to mention the additional work required by other mods to provide fillet knives for their own materials, something few have bothered with, for a simple reason: fillet knives are a single-use tool like shears, there is no gameplay advantage to providing multiple material tiers)
- Tiers are very clearly an afterthought with the intended design leaning towards the material provided by this mod (Neptunium), which has all the bonuses stacked (unbreakable, extra drops), bonuses that would be more fitting as enchantments for a single tool, further integrating this mod with the base game and reducing the clutter of duplicate knife items

Additionally, the filleting of fish could be made to be more unique; the Create mod introduces sandpaper which you can equip in your off-hand and "polish" items in your main hand, this mechanic would be a great creative way to fillet fish in Aquaculture.

Thank you for your time, I hope some consideration can be made to improve this element of the mod.

**Comment by GirafiStudios** [comment]
Thank you for your suggestions!
The Fillet Knifes are working exactly as intended by design.
As for a Netherite variation, that is something we're possibly considering for the future eventually.

**Comment by MarioSMB** [comment]
Thanks for the response.  
I'm just wondering, are there any cases where the "intended" design may be altered in favour of suggested improvements? This was to be the first in a series of reports to improve the user experience, but I fear it may be halted by such quick closures.  

I appreciate the consideration otherwise, and look forward to seeing the Netherite variation in a future update.
