### ISSUE TITLE
Neptunium Hoe is not compatible with Ensorcellation

### ISSUE THREAD

**Issue by Mooncat25** [TeamMetallurgy/Aquaculture#229]
### Description
The ability of "make tilled farmland stay moist" from Neptunium Hoe is lost if Ensorcellation is installed. I've contacted Dr Lemming, the dev of Ensorcellation, and he suggested a fix on the `NeptuniumHoe` class to increase mod compatibility: https://gist.github.com/KingLemming/0b8efd67b917181bdbd131f3c24271fb

### Environment
- Forge 36.1.4
- Minecraft 1.16.5
- Aquaculture-1.16.5-2.1.16.jar
- cofh_core-1.16.4-1.2.1.jar [(link)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
- ensorcellation-1.16.4-1.2.0.jar [(link)](https://www.curseforge.com/minecraft/mc-mods/ensorcellation)

**Comment by KingLemming** [comment]
Sorry - I'm realizing in my code that it should be < 0 for the FAIL branch. Wrote that raw in the gist.

**Comment by GirafiStudios** [comment]
No worries, I should've tested it - just didn't have time.
I appreciate you letting me know, I'll get a new build out shortly :)
