### ISSUE TITLE
Cant start game with BOP latest version

### ISSUE THREAD

**Issue by PhyX-Meow** [TeamMetallurgy/Aquaculture#230]
Today I update forge to 36.1.12 and got this
![image](https://user-images.githubusercontent.com/17513581/115950057-98b2a580-a50b-11eb-85fb-f3e7bf6b792d.png)
But my BOP is: BiomesOPlenty-1.16.5-13.1.0.441-universal
Game version:1.16.5
Aquaculture mod version: Aquaculture-1.16.5-2.1.16

**Comment by GirafiStudios** [comment]
That does seem very weird, as you're using a newer version than we require.
I'll take a look later.

**Comment by GirafiStudios** [comment]
What Minecraft Forge version are you using? I think this might be caused by changes in Forge version 36.1.10, so try using 36.1.9 :)

**Comment by PhyX-Meow** [comment]
@GirafiStudios Thanks for reply. I'm using forge 36.1.12, and the game do work well in old versions.

**Comment by sscards55** [comment]
actually it is AQ fault, I thought the version was funky
https://github.com/TeamMetallurgy/Aquaculture/blob/e7ebad1824f3ba5038bff6d677994c9e608302ce/src/main/resources/META-INF/mods.toml#L27

**Comment by GirafiStudios** [comment]
@PhyX-Meow, could you try this Jenkins version, with latest version of Forge too? :)
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.16/80/

**Comment by sscards55** [comment]
You fixed it it just as I commented on it. Girafi, why are you so good at this?

**Comment by PhyX-Meow** [comment]
@GirafiStudios Wow, what a quick fix. I would try it tomorrow, now it's 00:04 in my timezone.

**Comment by PhyX-Meow** [comment]
Great! Everything works fine now.

**Comment by GirafiStudios** [comment]
Thanks for confirming that older versions do work :)
