### ISSUE TITLE
Version mismatch with Biomes o plenty due to forge change

### ISSUE THREAD

**Issue by DarkEyeDragon** [TeamMetallurgy/Aquaculture#231]
![image](https://user-images.githubusercontent.com/6131099/115973315-4ea1e200-a554-11eb-86ff-17ab7fc30ee3.png)
Due to a recent change in forge version validation its failing to load the mod.

Stacktrace: https://pastie.io/phmzme.groovy

**Comment by GirafiStudios** [comment]
Update Aquaculture 2, I released a fix a couple of hours ago.
