### ISSUE TITLE
[1.16.5] NPE from Message in a Bottle

### ISSUE THREAD

**Issue by NillerMedDild** [TeamMetallurgy/Aquaculture#232]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2118
`Aquaculture-1.16.5-2.1.18`

> **Describe the bug**
> 
> "Null Pointer Exception: Aquaculture.MessageInABottle (String) cannot be Null." in chat. The logs don't contain the stack trace, so I'm guessing that Message In A Bottle's code catches exceptions and uses their message string as the bottle's message.
> 
> **Logs**
> 
> > .....
> > [19:59:21] [Render thread/INFO]: [CHAT] Can't teleport yet! Cooldown: 1 minute and 58 seconds
> > [20:01:54] [Render thread/INFO]: [CHAT] Null Pointer Exception: Aquaculture.MessageInABottle (String) cannot be null.
> > [20:02:09] [Server thread/INFO]: Saving and pausing game...
> > ...
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/1171633/117387374-08c71100-aea6-11eb-8f6d-f1f46d3946a7.png)

**Comment by sscards55** [comment]
Intentional message.

**Comment by sscards55** [comment]
See [here](https://github.com/TeamMetallurgy/Aquaculture/blob/77ece709bc2a57f5cb704655c14fee7ca9bb1198/src/main/resources/assets/aquaculture/lang/en_us.json#L219).

**Comment by NillerMedDild** [comment]
Wow o_O
