### ISSUE TITLE
Neptunium Options have no effect

### ISSUE THREAD

**Issue by CREEATION** [TeamMetallurgy/Aquaculture#237]
I changed everything related to Neptunium to false, yet the recipes still show in-game.

```toml
["neptunium options"]
  "Enable recipes for Neptunium items?" = false
  "Enable recipes for Neptunium armor?" = false
  #Should Neptune's bounty be added as fishing loot? Very rare.
  "Add Neptune's Bounty as loot?" = false
```

Looking at the code related to the bounty it's probably working fine (didn't test), but I haven't found any condition checks for items/armor after a quick look here on GitHub.
I'm hoping it's just me being dumb 🐢

### Versions
Minecraft: `1.16.5`
Forge: `36.1.17`
Aquaculture: `1.16.5-2.1.18`

**Comment by GirafiStudios** [comment]
https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/java/com/teammetallurgy/aquaculture/init/AquaLootTables.java#L48

**Comment by GirafiStudios** [comment]
I misread, didn't notice you were talking about the recipes. I'll take a look.

**Comment by GirafiStudios** [comment]
All the recipes disable just fine. 
It's not done in-code, it's done through a recipe conditation, in the recipe json.

**Comment by CREEATION** [comment]
Ah, I see. I got confused because the nugget, ingot etc. were still showing up in the recipe book even though I thought this was meant by "disabling neptunium items".

Thanks for the quick reply then 🐢
