### ISSUE TITLE
[1.16.4] Turning Down Spawns

### ISSUE THREAD

**Issue by Arishant** [TeamMetallurgy/Aquaculture#238]
Hello!
In a server that I am a member of, we have an issue with the fish spawning in massive numbers. Essentially if you are in an area too long, and there's a pond near you, you can easily get 50+ fish in that pond within an hour or so. It gets to the point where if you look in the direction of said body of water, frames can drop from 50-60 fps to ~20 fps. The only option in the config that I have seen that connects to fish spawns is to turn them off, but we would like to still have the fish, just not in such massive numbers. So I suppose this is a suggestion of a sort to add a way to adjust fish spawning in the config. 
However I am in no way demanding a config change, and simply wondering if there any mods out there that you suggest using to turn down spawns, or if you have any ideas of how to adjust spawn amounts.

**Comment by GirafiStudios** [comment]
What Aquaculture version are you using?

**Comment by Arishant** [comment]
I realized I made a slight hiccup in labelling the version, it is actually 1.16.4. Server is in 1.16.5 so I thought the aquaculture version was the same. If the mod updated and fixed said issue, my apologies for not checking. I hadn't thought to see if we had the latest version of the mod.
We are using version 1.16.4-2.1.12.

**Comment by GirafiStudios** [comment]
The amount of spawns is 100% handled with vanilla.
The only thing we have sorta control over is the weight between what spawns.

**Comment by Arishant** [comment]
Alright! Thank you for your assistance.

**Comment by GirafiStudios** [comment]
There could be a mod messing with it though, causing the problems.
It sounds like a problem that was there at one point, but we fixed in earlier 1.16.4 versions.
