### ISSUE TITLE
Entity rendering in world crash on joining world

### ISSUE THREAD

**Issue by Darkmega18** [TeamMetallurgy/Aquaculture#239]
Minecraft: 1.16.5
AquaCulture: 1.16.5-2.1.18
Forge: 36.1.23
Other mods? : Plenty. see log. :V

Crash log: https://pastebin.com/dfV2urJp

After a frustrating night of datapack errors and invalidations eventually "fixed" with a combination of mod backdating or updating and not being stupid I finally load my game and make a world that doesn't hang mid world loading.

Thinking I can actually play for a little bit before bed I start a world... but nope. A fish spawns in somewhere probably and spontaneously causes my game to explode. :<

I'm unsure what did it other than an over updated forge or origins forge and it's parts.

[later]
I did a test and found that when I removed origins and it's dependency architectury the bug cleared itself. I didn't have anymore crashing trouts. so thats probably a starting point I guess?

**Comment by GirafiStudios** [comment]
Unfortunately, it's crashing on a call directly to vanilla code, which I can't do anything about.
So it's probably caused by the mod you mentioned yourself.
Otherwise potientially try without Optifine.
