### ISSUE TITLE
The hook renders above the water instead of resting in it

### ISSUE THREAD

**Issue by The-Fireplace** [TeamMetallurgy/Aquaculture#24]
![2017-06-04_00 14 22](https://cloud.githubusercontent.com/assets/5914284/26759138/52af8d92-48bb-11e7-97cc-37a7f4eb5da1.png)
Expected behavior: Hook is in the water, bobbing up and down
Actual behavior: Hook is above the water, bobbing up and down. It only enters the water when there is a bite or when initially casting it into the water.
Aquaculture 1.5.0, Minecraft 1.11.2

**Comment by darthvader45** [comment]
Vanilla bug, sometimes casting directly into water causes the hook to float upward visually.  It still functions fine, just annoying to look at.

**Comment by GirafiStudios** [comment]
As darthvader45 said this was a vanilla issue previously. Will be fixed in the 1.12.2 release of Aquaculture.
