### ISSUE TITLE
[Compat] Aquaculture fish apparently spawn in `betterportals:portal_fluid_still`

### ISSUE THREAD

**Issue by lincore81** [TeamMetallurgy/Aquaculture#242]
Not sure which mod is to blame here, but whenever I use a portal from Yung's Better Portals, I get a dozen aquaculture fish on the other side. No vanilla fish however. I assume they spawn in the portal fluid and immediately teleport. I will submit this issue on both projects.

**Comment by sscards55** [comment]
I think it might be on yung's fault, as aquaculture doesn't actually control fish spawns.

**Comment by GirafiStudios** [comment]
We're allowing our fish to spawn in any fluid block tagged as WATER. I guess I'll change it back to only allow vanilla water, to prevent cases where blocks are tagged as WATER, that is not actually proper water.
