### ISSUE TITLE
Feature Request: Support for Hoeing Rich Soil from Farmer's Delight

### ISSUE THREAD

**Issue by bcrotty** [TeamMetallurgy/Aquaculture#243]
Would it be possible to add support for hoeing Rich Soil from the [Farmer's Delight mod](https://www.curseforge.com/minecraft/mc-mods/farmers-delight) with the Neptunium Hoe?

No worries if you'd rather not, but thanks if you do! Love the mod!

**Comment by GirafiStudios** [comment]
Thank you for the suggestion!
That's not something we're looking to support, at this current time.
