### ISSUE TITLE
[Feature] Goldfish in a bucket

### ISSUE THREAD

**Issue by GalaxySynth** [TeamMetallurgy/Aquaculture#244]
I had noticed that all the fishes are bucketable, but the goldfish doesn't have an entity, only an item. 

It would be super amazing to have the goldfish as a possible entity to have in a makeshift aquarium.

**Comment by GirafiStudios** [comment]
Thanks for the suggestion!
That´s something we´ll probably consider for the future, but it's not something we're going to implement right now.
