### ISSUE TITLE
Brown Trout crash?

### ISSUE THREAD

**Issue by Blacksky649** [TeamMetallurgy/Aquaculture#245]
Not sure what to make of this, happened far enough from my character when I wasn't doing anything in the water
[crash-2021-06-07_03.06.29-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/6606585/crash-2021-06-07_03.06.29-client.txt)

**Comment by GirafiStudios** [comment]
Please remove Performant, it´s causing the issue.
Performant is very buggy, and you should avoid it - as it does not actually make things better in most cases.
