### ISSUE TITLE
Fishes from aquaculture are not registered as minecraft fish

### ISSUE THREAD

**Issue by jaz0894** [TeamMetallurgy/Aquaculture#247]
I am using a custom modpack that also includes pam´s for cooking experience.

I love fishing and aquaculture gave me an expansion on that area, however I cannot use the fish from this mod for anything out of the 2 or 3 crafts already existing for them.

Is there a way to change that?

**Comment by GirafiStudios** [comment]
Yes, they are registered as minecraft:fish.
They´re not registered to the tag Pam´s Harvestcraft uses, as it does not following naming conventions.
