### ISSUE TITLE
Worm farm doesn't work with hoppers (MC version 1.16.5, Aquaculture version 2.1.19).

### ISSUE THREAD

**Issue by Whisker72** [TeamMetallurgy/Aquaculture#248]
I want to automate the worm farm like e.g. a composter (one hopper above to put in raw materials, one hopper beneath to collect the output).

Alas, while stocking the worm farm with raw materials via hopper does work, harvesting worms via a hopper connected from below doesn't. Which means I have to harvest every worm by hand which is anything but fun and gets very tedious over time.

So is there any way I can make this work, or is this just a bug?

**Comment by GirafiStudios** [comment]
It´s intended to only work manually, yes :)

**Comment by Whisker72** [comment]
Damn, I was just tinkering with having my composter, my worm farm and the worm bin from Water Strainer being fed by one hopper and getting the output sorted into different chests. So that obviously won't work. :-(

On the other hand: how about implementing an option to turn manual harvesting on and off? :-)
