### ISSUE TITLE
Disable basic fillet recipes

### ISSUE THREAD

**Issue by KyleHannon** [TeamMetallurgy/Aquaculture#249]
I'm trying to optimize an integration between this mod and Farmer's Delight which allows you to use the Farmer's cutting board to obtain fillets. I'd like to force the player to use the cutting board, rather than the basic crafting interface, but I can't seem to disable the basic crafting recipes with something like KubeJS. I can't even disable individual recipes with their IDs like 'aquaculture:fish_fillet.pufferfish'.

I'm not sure if this is an option you'd be open to adding to the config, or if I'm missing a method based on how these recipes are generated. I haven't run into this issue with other mods I'm creating compat scripts for.

**Comment by sscards55** [comment]
To disable the fish fillet recipe, you have to disable the special type recipe which is "aquaculture:fish_fillet". This should be the case for most programmatically based recipes such as fireworks.

**Comment by KyleHannon** [comment]
Strange, that doesn't seem to work either, even as a startup script. I wonder if this is specific to KubeJS.

**Comment by GirafiStudios** [comment]
Remove the json file Sscards mentioned, with a data/resourcepack.

**Comment by Dark-Arcana** [comment]
Minecraft version: 1.16.5
Aquaculture version: 2.1.20

Sorry to re-open this issue. However, the suggested solution isn't working for me. I'm trying to do the exact same thing as the person above. I've attempted to use KubeJS to remove the fish fillet crafting recipes. When that didn't work, I found this issue. I created a datapack to override `/data/aquaculture/recipes/fish_fillet.json`. I tried leaving the file blank, with an empty object/array, and with `{"type": null}` and `{"type": "farmersdelight:cutting"}. No matter what I try, I can't seem to remove the recipes to use #forge:fillet_knife on different fish in the crafting table to create fish fillets.

Do you have some other option? Can we add a config option?
