### ISSUE TITLE
Worm farm fills, but does not give worms.

### ISSUE THREAD

**Issue by danemorgan** [TeamMetallurgy/Aquaculture#250]
Minecraft 1.16.5
Forge: 36.1.32
Aquaculture 2: 2.1.19

Clicking the worm farm with compostables fills the worm farm, but once it is full it stops responding to the clicks and never generates a worm.

**Comment by GirafiStudios** [comment]
You have to right-click with an empty hand (Or anything that can´t be composted really), no matter how full the worm farm are, in order to get a worm out :)

**Comment by danemorgan** [comment]
I added this information to the Wiki, as that's where I went looking for an answer to this first.

https://github.com/TeamMetallurgy/Aquaculture/wiki/Worm-Farm
