### ISSUE TITLE
For some reason I can't seem to get neptune's bounty? (I have been grinding for hours with luck of the sea ||| and lure |||))

### ISSUE THREAD

**Issue by whatsupyo99** [TeamMetallurgy/Aquaculture#251]
The neptunium items are checked in labeled true in the config file.

**Comment by sscards55** [comment]
It's really rare. Are you playing on a server? do you have other mods installed? what version of the mod are you on? what version of forge do you have?

**Comment by whatsupyo99** [comment]
I am playing on 1.16.5. Yes I am using a mod pack called Better Minecraft. I am on Aquaculture-1.16.5-2.1.19. My version of forge is 36.1.31.

**Comment by GirafiStudios** [comment]
Are you fishing in open water?
Can read about it in the 2nd pharagraph here:
https://minecraft.fandom.com/wiki/Fishing#Junk_and_treasure

**Comment by whatsupyo99** [comment]
Yes I have been in open water.
![2021-07-17_17 48 54](https://user-images.githubusercontent.com/87584728/126050031-a8333eed-f1ea-4d65-8c2d-b14d3d58980c.png)

**Comment by GirafiStudios** [comment]
They are very rare. Usually takes quite a few hours to get one :)

**Comment by whatsupyo99** [comment]
I have been trying to get one for 8 hours and got none.
