### ISSUE TITLE
[1.17.1] The launcher gives an error after installing the mod

### ISSUE THREAD

**Issue by Shadowglitchjpg** [TeamMetallurgy/Aquaculture#254]
Whenever I put the latest (v2.2.0) mod file in the mods folder, the launcher, instead of loading the game, gives an error (An unexpected issue occured and the game has crashed. We're sorry for the inconvenience. Exit code: 0). I have other mods installed, including Tactical Fishing, but it's not the source of the crash (I just tested it).

**Comment by GirafiStudios** [comment]
Please provide the crashlog.

**Comment by GirafiStudios** [comment]
My best guess, with what you said. Is that either you have a version of Forge that´s older than 37.0.8.
Or would you happen to have Biomes O´ Plenty installed?

**Comment by Shadowglitchjpg** [comment]
I have Biomes O'Plenty installed and my Forge version is 37.0.12

**Comment by GirafiStudios** [comment]
Make sure you´re using Biomes o Plenty version 14.0.0.13 or newer

**Comment by Shadowglitchjpg** [comment]
I'm using Biomes O'Plenty version 14.0.0.14

**Comment by Shadowglitchjpg** [comment]
Sorry, it took me a while to locate the crashlog
[crash-2021-07-28_19.25.17-fml.txt](https://github.com/TeamMetallurgy/Aquaculture/files/6895405/crash-2021-07-28_19.25.17-fml.txt)

**Comment by GirafiStudios** [comment]
The issue is on BoPs side. The problem is that I require a specific version (or newer) of BoP. But their version internally is just set to "1", which can´t really be used for much. I´ll release a new version without the check.

**Comment by Shadowglitchjpg** [comment]
Thank you, it's working now
