### ISSUE TITLE
Ola, tengo una duda con vuestro mod, como se consigue la Trampa para Peces?, "block.aquaculture.fish_trap":"Fish Trap", en listado de inventario, con JEI, no sale.

### ISSUE THREAD

**Issue by Vicus6** [TeamMetallurgy/Aquaculture#257]
Ola, tengo una duda con vuestro mod, como se consigue la Trampa para Peces?.
 "block.aquaculture.fish_trap":"Fish Trap".
 En listado de inventario, con JEI, no sale.

**Comment by GirafiStudios** [comment]
There is no Fish Trap in Aquaculture.

**Comment by Vicus6** [comment]
y esa instruccion?

**Comment by Vicus6** [comment]
es de su lang, solo sale ahi

**Comment by sscards55** [comment]
No hay un bloque que es trampa para peses

**Comment by Vicus6** [comment]
pos solo digo lo ke veo en el archivo lang:
{"itemGroup.aquaculture":"Aquaculture","_comment":"Subtitle",**_"block.aquaculture.fish_trap":"Fish Trap"_**,"block.aquaculture.neptunium_block":"Neptunium Block","block.aquaculture.neptunes_bounty":"Neptune's Bounty","block.aquaculture.tackle_box":"Tackle Box","block.aquaculture.worm_farm":"Worm Farm","block.aquaculture.farmland":"Farmland","item.aquaculture.iron_fishing_rod":"Iron Fishing Rod"

**Comment by Vicus6** [comment]
Ok, aclarado, podiais poner,(añdir) algo , como esto:

	"itemGroup.Aquaculture.main": "Water Strainer",	
	"block.Aquaculture.strainer_base": "Strainer Base",
	"block.Aquaculture.worm_bin": "Worm Bin",
	
	"item.Aquaculture.efficiency_meter": "Efficiency Meter",
	"item.Aquaculture.garden_trowel": "Garden Trowel",
	"item.Aquaculture.worm": "Worm",
	"item.Aquaculture.super_worm": "Super Worm",
	"item.Aquaculture.bait_pot": "Bait Pot",
	"item.Aquaculture.string_mesh": "String Mesh",
	"item.Aquaculture.iron_mesh": "Iron Mesh",
	"item.Aquaculture.obsidian_mesh": "Obsidian Mesh",
	"item.Aquaculture.fertilizer": "Fertilizer",
	
	"item.Aquaculture.strainer_survivalist": "Survivalist's Strainer",
	"item.Aquaculture.strainer_survivalist_solid": "Solid Survivalist's Strainer",
	"item.Aquaculture.strainer_survivalist_reinforced": "Reinforced Survivalist's Strainer",

	"item.Aquaculture.strainer_fisherman": "Fisherman's Strainer",
	"item.Aquaculture.strainer_fisherman_solid": "Solid Fisherman's Strainer",
	"item.Aquaculture.strainer_fisherman_reinforced": "Reinforced Fisherman's Strainer"
Esto solo una idea, sacar todos esos peces, cuesta un poko, tengo otro mod que pesca el solo, un pikozapato, que saca algunos items vuestros;

  "item.aquaculture.driftwood":"Madera de deriva",
  "item.aquaculture.tin_can":"Lata",
  "item.aquaculture.fish_bones":"Huesos de pescado",
  "item.aquaculture.message_in_a_bottle":"Mensaje en una botella",
  "item.aquaculture.box":"Caja",
  "item.aquaculture.lockbox":"Caja asegurada",
  "item.aquaculture.treasure_chest":"Cofre del tesoro",
  "item.aquaculture.oak_fish_mount":"Soporte para pescado de roble",, 
pero para los peces me se ahoga en aguas profundas.
Gracias por la atencion, y perdon por la indiscrepcion.
Un Saludo.
