### ISSUE TITLE
sugerencia de block, trampa para peces

### ISSUE THREAD

**Issue by Vicus6** [TeamMetallurgy/Aquaculture#258]
Ola de new.
podiais poner, (añdir) algo, como esto:

"block.Aquaculture.strainer_base": "Strainer Base",
"block.Aquaculture.worm_bin": "Worm Bin",

"item.Aquaculture.efficiency_meter": "Efficiency Meter",
"item.Aquaculture.garden_trowel": "Garden Trowel",
"item.Aquaculture.worm": "Worm",
"item.Aquaculture.super_worm": "Super Worm",
"item.Aquaculture.bait_pot": "Bait Pot",
"item.Aquaculture.string_mesh": "String Mesh",
"item.Aquaculture.iron_mesh": "Iron Mesh",
"item.Aquaculture.obsidian_mesh": "Obsidian Mesh",
"item.Aquaculture.fertilizer": "Fertilizer",

"item.Aquaculture.strainer_survivalist": "Survivalist's Strainer",
"item.Aquaculture.strainer_survivalist_solid": "Solid Survivalist's Strainer",
"item.Aquaculture.strainer_survivalist_reinforced": "Reinforced Survivalist's Strainer",

"item.Aquaculture.strainer_fisherman": "Fisherman's Strainer",
"item.Aquaculture.strainer_fisherman_solid": "Solid Fisherman's Strainer",
"item.Aquaculture.strainer_fisherman_reinforced": "Reinforced Fisherman's Strainer"

Esto solo una idea, sacar todos esos peces, cuesta un poko, tengo otro mod que pesca el solo, un pikozapato, que saca algunos elementos vuestros;

"item.aquaculture.driftwood": "Madera de deriva",
"item.aquaculture.tin_can": "Lata",
"item.aquaculture.fish_bones": "Huesos de pescado",
"item.aquaculture.message_in_a_bottle": "Mensaje en una botella ",
" item.aquaculture.box ":" Caja ",
" item.aquaculture.lockbox ":" Caja asegurada ",
" item.aquaculture.treasure_chest ":" Cofre del tesoro ",
" item.aquaculture.oak_fish_mount ":" Soporte para pescado de roble ",,

pero para los peces me se ahoga en aguas profundas.

Gracias por la atencion, y perdon por la indiscrepcion.
Un Saludo.

**Comment by sscards55** [comment]
En el momento no hay planes para añadir Trampas para Peses. La linea en el lang es un error.
Por favor solamente usa Ingles en las paginas the asuntos.

**Comment by Vicus6** [comment]
ok, 
Gracias la atencion
