### ISSUE TITLE
Korean Language is not applicable.

### ISSUE THREAD

**Issue by mindy15963** [TeamMetallurgy/Aquaculture#262]
I'm enjoying Minecraft in Korean right now. But Korean Language is not applicable.
![evidence 1](https://user-images.githubusercontent.com/39722516/129468720-a90469ea-69dd-4c1f-a683-a55796ad55e2.png)
![evidence 2](https://user-images.githubusercontent.com/39722516/129468721-581930f5-25bb-454f-9649-847b4f6e0a46.png)
![evidence 3](https://user-images.githubusercontent.com/39722516/129468722-b65270d8-1cfb-479e-93c5-fc83861666b6.png)

**Comment by GirafiStudios** [comment]
You´re right, the Korean localization does indeed seem to be broken. I´ve pushed a fix to Github.
What Minecraft version are you on? :)
