### ISSUE TITLE
Neptune's bounty not dropping

### ISSUE THREAD

**Issue by Locoapples** [TeamMetallurgy/Aquaculture#263]
Ver. 1.16.5-2.1.20
seemingly everything else that should drop from aquaculture does drop at what seems to be a normal rate. except neptunes bounty.
extensive testing via generating a chest with the following command : /setblock ~ ~ ~ minecraft:chest{LootTable:"gameplay/fishing"}
attached is a mods list
(no configs were changed)
apologies if this is my fault!
[modlist.txt](https://github.com/TeamMetallurgy/Aquaculture/files/7010457/modlist.txt)

**Comment by GirafiStudios** [comment]
It most likely won´t generate with that command, as it requires to be in "Open Water", as all vanilla treasure also do nowadays :)
