### ISSUE TITLE
Disable Basic Fillet Recipes

### ISSUE THREAD

**Issue by Dark-Arcana** [TeamMetallurgy/Aquaculture#265]
Minecraft version: 1.16.5
Aquaculture version: 2.1.20

Sorry to re-open this issue. However, the suggested solution isn't working for me. I'm trying to do the exact same thing as the person above. I've attempted to use KubeJS to remove the fish fillet crafting recipes. When that didn't work, I found this issue. I created a datapack to override `/data/aquaculture/recipes/fish_fillet.json`. I tried leaving the file blank, with an empty object/array, and with `{"type": null}` and `{"type": "farmersdelight:cutting"}. No matter what I try, I can't seem to remove the recipes to use #forge:fillet_knife on different fish in the crafting table to create fish fillets.

Do you have some other option? Can we add a config option?

_Originally posted by @Dark-Arcana in https://github.com/TeamMetallurgy/Aquaculture/issues/249#issuecomment-915551420_

**Comment by GirafiStudios** [comment]
Have you tried to actually use the crafting recipe, after having made the datapack change?
It might still show up in JEI. I can add an config option for it showing up in JEI, but not for disabling the recipes - due to how Forge loads things.

**Comment by Dark-Arcana** [comment]
![image](https://user-images.githubusercontent.com/6245904/132588383-67bdfa1b-0951-4053-b042-d11ddffb4b53.png)

You're right, it's entirely disabled in the crafting table interface. That's great to see actually. So I guess my current issue is that it's not disabled in JEI.

![image](https://user-images.githubusercontent.com/6245904/132588466-d38c17c7-3aff-46e4-b82e-540f73b7fd2a.png)

The standard crafting recipe using a crafting table is the first thing a player will see. I don't want them to get confused looking for a fillet knife and seeing that the recipe itself doesn't actually work. I want them to only see the cutting board from farmer's delight. Hope this info helps. I would greatly appreciate a config option to remove showing the recipes in JEI.

**Comment by GirafiStudios** [comment]
Added in https://github.com/TeamMetallurgy/Aquaculture/commit/fb37889c1d8848dc4940276634dad31ea5ae9a9b

**Comment by Dark-Arcana** [comment]
Thanks so much! I'll test it out as soon as it's updated on curseforge and let you know if I run into any more issues.

**Comment by Dark-Arcana** [comment]
I'm so happy. It worked!
![image](https://user-images.githubusercontent.com/6245904/132596012-6e704a10-715c-41f2-b4e8-05079a44541d.png)
