### ISSUE TITLE
Fish no weight

### ISSUE THREAD

**Issue by Yurinann** [TeamMetallurgy/Aquaculture#266]
"Enable weight for fish? Useful for fishing competitions" = true

But the fish I caught have no weight

1.16.5 Server: Arclight (https://github.com/IzzelAliz/Arclight)
With Piscary (another fish mod)

**Comment by sscards55** [comment]
It's a bukkit server, those are not supported due to how they change gameplay and code.

**Comment by Yurinann** [comment]
Is there any other solution? This server also supports mods.

**Comment by sscards55** [comment]
Not really, unless you can run the server without plugins. In which case just run a normal forge server.

**Comment by Yurinann** [comment]
I tried it in singleplayer mode, and there is no weight..

**Comment by GirafiStudios** [comment]
Is it only the Piscary fish that don´t have weight, or what are you saying?

**Comment by Yurinann** [comment]
all fish

**Comment by GirafiStudios** [comment]
![image](https://user-images.githubusercontent.com/6305377/132947873-9dd12b29-a89c-48f4-9e6e-799d414ae331.png)
Unable to reproduce, works just fine with Aquaculture and Piscary together.

**Comment by Yurinann** [comment]
to open the weight, in addition to setting "Enable weight for fish? Useful for fishing competitions" = true , is there anything else? thx

**Comment by sscards55** [comment]
No, just enable that config.

**Comment by GirafiStudios** [comment]
Well you need to catch a new fish, after enabling the config. Fish caught previously will not have a weight.

**Comment by Yurinann** [comment]
i did this, and i think may be caused by other mods. i will try
and i had another mod about fishing -- fishingoverhaul (a game when you catch a fish)
i will try to delete him and test again

**Comment by Yurinann** [comment]
Seems to be an edited question, not the mod. Now the weight is displayed, but it isn't have "Large" or others like the picture above.

**Comment by Yurinann** [comment]
oh.. it looks like some have and some don't

**Comment by Yurinann** [comment]
Perhaps this is the original look like?

**Comment by Yurinann** [comment]
Anyway, thank you very much for your help!
