### ISSUE TITLE
Neptunium Hoe does not work with Peat Farmland

### ISSUE THREAD

**Issue by evankimori** [TeamMetallurgy/Aquaculture#270]
Current modpack: Engineer's Life 2 alongside with replacement for Peat via Terra Incognita.

Using Neptunium Hoe on (T.I) Peat to turn Farmland does not apply moisture buff and block stays dry, even with water source block below it.

Compatibility, intended or low priority issue?

**Comment by sscards55** [comment]
Compatibility, by default AQ2 only works on normal vanilla dirt.

**Comment by evankimori** [comment]
Is there a way to add in compatibility, anything I can work on from my end or Close this here?

**Comment by GirafiStudios** [comment]
Exactly as sscards said.
Unless you´re the mod author of Terra Incognita, then no.
