### ISSUE TITLE
Error Aquacilture not working

### ISSUE THREAD

**Issue by NekosukiTheLoli** [TeamMetallurgy/Aquaculture#272]
Im playing aquaculture on 1.17.1 i put in the mod but it doesn't work I can open Minecraft but nothin I'm using fabric and it still doesn't work when I'm in the game it wont craft any of the items I don't see the items in creative mode too how do I fix this or is this a bug or an error

**Comment by Shadowclaimer** [comment]
The mod isn't out for Fabric.
