### ISSUE TITLE
Worm Farm crashes server when used with Hopper

### ISSUE THREAD

**Issue by LiskoSlayer63** [TeamMetallurgy/Aquaculture#275]
My friend tried to automate the Worm Farm and crashed server so he couldn't even join in anymore. I needed to restore earlier backup to get rid of the hopper so the server doesn't crash loop anymore.

**Minecraft ver:** 1.16.5
**Forge ver:** 36.2.8
**Aquaculture ver:** 2.2.3
**Server software:** Mohist 1.16.5-839

Crash log: https://pastebin.com/xj7jVvj1

**Comment by GirafiStudios** [comment]
Any Bukkit/Forge hybrid is unsupported, which includes Mohist.
Does not happen on a server with just Forge.

**Comment by LiskoSlayer63** [comment]
Thanks for the fast answer, I'll test it again with just Forge and then report it to Mohist.
