### ISSUE TITLE
Fish spawn rates

### ISSUE THREAD

**Issue by iiDogez** [TeamMetallurgy/Aquaculture#276]
I love using this mod with fish as entities enabled, problem is though, they hog up the spawn cap considerably, is it possible to add a spawn rate thing into the config or turn down the spawn rates so they don't kill the spawn cap?

**Comment by sscards55** [comment]
This is something that is controlled by vanilla, not aquaculture, sadly.

**Comment by GirafiStudios** [comment]
Aquaculture is is respecting the spawn caps.
It is caused by another mod - depends on what Minecraft version you are on.
Although make sure you are using the latest version of Aquaculture and Forge.
