### ISSUE TITLE
Jellyfish do not smelt in IE- powered furnaces (ac2, 1.16.5)

### ISSUE THREAD

**Issue by databeast** [TeamMetallurgy/Aquaculture#277]
smelting a jellyfish in a furnace powered by an Immersive engineering furnace heater produces no results.. the furnace lights, the progress bar moves, but then the jellyfish remains unsmelted at the end, and the progress bar remains stuck at 100%

**Comment by sscards55** [comment]
Immersive Engineering?

The recipe is just a standard furnace recipe, it doesn't have any special handlers.

**Comment by sscards55** [comment]
Do you have any other mods installed? What version of forge are you using? Are you playing with a modpack? Are all mods up to date?

Did you report this bug to IE already?

**Comment by databeast** [comment]
forge is 36.2.8. couple of other mods. 

this is the first time I've ever encountered anything not smelt as normal in a furnace powered by an IE heater, so yeah my mind went to it being that you were doing something specific with it on your end, and it not being IE related directly.

I'll do some more experimentation and get you some more datapoints, but as you've said, if it's a standard furnace recipe, then It's likely the issue may lie elsewhere, if you aren't tapping direct into, say, fuel consumption data or the like.

**Comment by GirafiStudios** [comment]
Just a straight up furnace recipe, as sscards said.

Link toe recipe for reference:
https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/resources/data/aquaculture/recipes/jellyfish_to_slimeball.json
