### ISSUE TITLE
Fishing Rods Will NOT Catch Fish

### ISSUE THREAD

**Issue by ElysianEyes** [TeamMetallurgy/Aquaculture#278]
I have an issue, I'm on the newest version of Forge, Version 1.17.1.
All of the items are in the game, I can craft the tackle boxes and all...

But no matter what fishing rod I use, when I try to pull in a fish, nothing is pulled in.
I cannot catch fish with fishing rods. And I don't know if any of the mods I have are somehow messing with it? But this is obviously a problem, please help.

**Comment by sscards55** [comment]
Are you playing on a server? Can you hold F3+C for 10 seconds and post the crash here?

**Comment by ElysianEyes** [comment]
It's single player. Here's the crash report file.
[crash-2021-11-12_04.08.58-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/7526232/crash-2021-11-12_04.08.58-client.txt)

**Comment by sscards55** [comment]
Are you fishing in open waters, and what biome are you in?

**Comment by ElysianEyes** [comment]
I tried both the shore (Beach) and just the open Ocean. I even attempted a restart of Minecraft and even another world in Creative. Even attempted in a boat.

**Comment by GirafiStudios** [comment]
Can you try with just Aquaculture, to see if the problem is still happening for you then? :)

**Comment by ElysianEyes** [comment]
Problem persists with ONLY Aquaculture in mods folder. I'm going to try an earlier 1.17.1 Forge to see if the problem is still persisting then.

**Comment by GirafiStudios** [comment]
Latest Forge version definitely broke it. Please use an older version for now, while I work on a fix :)

**Comment by ElysianEyes** [comment]
Update: 1.17.1-37.0.103 Forge WORKS fine!

The newest version of Forge doesn't work.
