### ISSUE TITLE
Config for spawn rates?

### ISSUE THREAD

**Issue by Ace1362** [TeamMetallurgy/Aquaculture#279]
When looking at the config file for this mod it references that you can change rates and weights on the loot table... but It seems that neither I nor others have been able to find one we can access

**Comment by GirafiStudios** [comment]
You can use a ResourcePack to alter Loot Tables, just as you would with vanilla loot tables :) 

If you´re to make the changes for a modpack you´re creating, using something like [Open Loader](https://www.curseforge.com/minecraft/mc-mods/open-loader), might be a good option for you - as it allows the changes to be automatically applied to every world/save.
