### ISSUE TITLE
Fishing with the mod

### ISSUE THREAD

**Issue by Blazachicken** [TeamMetallurgy/Aquaculture#280]
I've been using an iron fishing rod with a golden lure and luck of the sea III, but all i catch is fish, and very very rarely a few trash items like bowls and the wooden chest, why can't i catch anything better like enchantment books, and the better chests

**Comment by GirafiStudios** [comment]
You can, you´re just unlucky :)
Make sure you´re fishing in open water, as that´s the only place you can get treasure (Change in vanilla in 1.16 I believe)

Please use Discord for questions - link can be found on our CurseForge page.

**Comment by Blazachicken** [comment]
That was my issue, i was unaware of that change in 1.16 and now my loot is much better with open water
