### ISSUE TITLE
[1.17.1] Fishing catches no fish

### ISSUE THREAD

**Issue by andres-urda** [TeamMetallurgy/Aquaculture#282]
Using Aquaculture-1.17.1-2.2.3 and getting console output 
[Server thread/ERROR]: Loot was empty in Biome: minecraft:river. Please report on Github.
[Server thread/ERROR]: Loot was empty in Biome: minecraft:beach. Please report on Github

This happens after every successful fish attempt, but no fish is caught. Tried with iron fishing rod and diamond fishing rod, minnow bait, double hook, no hook, all giving the same issue. Tried with Minecraft fishing rod, same issue but no console error.

Mod used to work when the mod was installed at the beginning of the server. Hadn't fished since early November until today, and now this issue arose.

Modlist is the following:
![image](https://user-images.githubusercontent.com/93447646/142489058-734a18d1-90fd-4ad3-b3b5-efd1ec21cd4e.png)

Let me know if you need anymore info.

**Comment by GirafiStudios** [comment]
Update to Aquaculture 2.2.4, or downgrade your Forge to version 37.0.108 or lower.

**Comment by andres-urda** [comment]
I'm on forge 37.0.103

**Comment by GirafiStudios** [comment]
Is this happening for you with just Aquaculture?

**Comment by andres-urda** [comment]
Tried it on a brand new singleplayer world with all the mods above, works fine.
Decided to download the world from the multiplayer server and try it in singleplayer mode, works perfectly fine. Catches fish.
Restart the MP server, log in and go to the same fishing spot, empty catch every time, no matter what rod I use.

Not sure what might be going on here.

**Comment by GirafiStudios** [comment]
Are you using some forgot of Forge/Bukkit hybrid for your server?

**Comment by andres-urda** [comment]
using forge 1.17.1 for my server 
![image](https://user-images.githubusercontent.com/93447646/142732833-c8b960e4-d477-47c3-8918-d32fa1805b15.png)

not using Bukkit or anything of the sort.

**Comment by GirafiStudios** [comment]
Looking at that, it looks like your server is automatically udpating Forge, when a new version comes up (Or shortly after). So you´re most likely using Forge version 37.0.109 or newer, on your server - while you´re not on your client.
Could you try updating to Aquaculture 2.2.4 on your server, should fix the issue, if that´s the case :)

**Comment by andres-urda** [comment]
*facepalm* can't believe I missed that.

![image](https://user-images.githubusercontent.com/93447646/142733974-eca7ef36-6470-4fa1-92aa-876ae6147bbb.png)

Changing it to an older version and I'll let you know if this works or if I'll just end up having to upgrade to 2.2.4.

**Comment by andres-urda** [comment]
Fixed!! Changing it to an older forge version worked. Surprised a newer forge version broke the older one, but glad you caught that.

Ty!
