### ISSUE TITLE
missing loot for tropicraft biome

### ISSUE THREAD

**Issue by Gattoartico** [TeamMetallurgy/Aquaculture#289]
According to the server Aquaculture is missing loot in Tropicraft. It told me to report it btw pls don't crucify me Girafi

console text:
[00:15:02] [Server thread/ERROR] [aquaculture/]: Loot was empty in Biome: tropicraft:tropics. Please report on Github

game version is 1.16.5, Aquaculture version is 2.1.21, Tropicraft version is 9.0.1 beta 64

relocated from the wrong spot pls don't kill me

it's nearly midnight and I'm tired pls forgive me

**Comment by GirafiStudios** [comment]
My best guess would be that Tropicraft don't have  their biome added to the BiomeDictionary.
I don't have access to a computer before in a few days, so can't check before then :)

**Comment by GirafiStudios** [comment]
Look like Tropicraft is not adding any of its biomes to the BiomeDictionary, so the issue is on their end.

You can possibly add them with CraftTweaker yourself, but not 100% sure that is possible.
