### ISSUE TITLE
1.18.1 - Constant Crash

### ISSUE THREAD

**Issue by celsiusqc** [TeamMetallurgy/Aquaculture#291]
Setting ""Enable fish spawning?" = true" to false makes the game crash upon launch
https://pastebin.com/xirN3R2E

**Comment by GirafiStudios** [comment]
Try deleting your config, letting it re-generate and then disabling fish spawning again :)

**Comment by GirafiStudios** [comment]
Closing because of no response. Please open a new issue, if my suggested fix does not work.
