### ISSUE TITLE
tackle box in 1.12.2?

### ISSUE THREAD

**Issue by IceLeviathan444** [TeamMetallurgy/Aquaculture#292]
So I just recently got aquaculture for 1.12.2, as I am using mods from 1.12.2 with it. Anyways, I was checking it out, and I realized its missing some features, like tackle boxes and baits and things like that. Will these be added to the 1.12.2 version of it eventually?

**Comment by GirafiStudios** [comment]
Aquaculture 1 is for 1.12.2 and before. Aquaculture 2 is for 1.13+ - as stated on CurseForge.

**Comment by IceLeviathan444** [comment]
so there wont be any more updates to aquaculture 1?

**Comment by GirafiStudios** [comment]
No, that ended a few years ago.

**Comment by IceLeviathan444** [comment]
ok.
