### ISSUE TITLE
[1.18.1] Fishing only seems to catch vanilla items

### ISSUE THREAD

**Issue by r-uiz** [TeamMetallurgy/Aquaculture#293]
I've only been able to fish out vanilla items and fish. Aquaculture 2 fish spawn in-game, but I don't fish them out.

**Comment by GirafiStudios** [comment]
Are you fishing in one of the new vanilla biomes by chance? Forge have not added them to the BiomeDictionary yet, and therefor fish and loot can´t be added to them.

**Comment by GirafiStudios** [comment]
Closing as there haven´t been any response.
Try another biome, that excised in 1.17 as well. If that doesn´t help, please open up a new issue with more thorough information.
