### ISSUE TITLE
Strange Version Incompatibility

### ISSUE THREAD

**Issue by remram25** [TeamMetallurgy/Aquaculture#296]
[crash-2021-12-22_02.56.58-fml.txt](https://github.com/TeamMetallurgy/Aquaculture/files/7761011/crash-2021-12-22_02.56.58-fml.txt)

![Capture](https://user-images.githubusercontent.com/81492264/147057437-bfba91f2-4a01-4dc0-ab40-20a46508b8c3.PNG)

**Comment by sscards55** [comment]
Which version of Aquaculture are you using?

**Comment by sscards55** [comment]
Can you update your version of Aquaculture and see if you still get the error?

**Comment by remram25** [comment]
I was using the latest forge version

**Comment by remram25** [comment]
of Aquaculture

**Comment by sscards55** [comment]
According to your log you have version 1.16.5-2.1.15 installed. The latest available version of Aquaculture 2 is 1.16.5-2.1.21

**Comment by GirafiStudios** [comment]
It was fixed ages ago in 2.1.17.
How do you even come across an old version like that?
