### ISSUE TITLE
Worm Durability

### ISSUE THREAD

**Issue by Jmmajovsky** [TeamMetallurgy/Aquaculture#298]
On 1.18.1, the worm durability either does not show (when a fresh worm is put on the rod) or is black, meaning no durability left. This issue is still present when placing multiple worms in the slot. I assumed this feature let you catch multiple fish/items before the worm would run lose its durability.

**Comment by GirafiStudios** [comment]
It´s a visual glitch, the durability does work :)
I´ll look into fixing it.
