### ISSUE TITLE
Not sure if bug or feature

### ISSUE THREAD

**Issue by LunafeyLazuli** [TeamMetallurgy/Aquaculture#299]
With the 1.18.1 update, I'm not sure if this is meant to be a feature or a bug, but with the normal vanilla fishing rod, I've noticed that about 70% of the time when I reel in a fish, I don't actually get anything. Tried looking for some logs for it but couldn't find anything related, so I was mainly wondering if this could be looked into.

**Comment by GirafiStudios** [comment]
Unable to reproduce. Caught something 10/10 times with a vanilla rod.
Sounds like some other mod is breaking stuff.
