### ISSUE TITLE
Fish not Hooking 1.16.5

### ISSUE THREAD

**Issue by Jaden99c** [TeamMetallurgy/Aquaculture#300]
Like the title says the fish in your mods are not able to be fished. Only vanilla items are being fished.
Current forge version is 36.2.22. Tried different biomes both vanilla and modded, bait, hooks, different fishing rods, etc..

**Comment by GirafiStudios** [comment]
Unable to reproduce with same Forge version. Make sure you´re on the latest version of AQ2 - if you already are, some other mod you have is breaking stuff.
