### ISSUE TITLE
Issue starting up forge client

### ISSUE THREAD

**Issue by cheesefries0** [TeamMetallurgy/Aquaculture#301]
Hi,
when me and my friends start up our client (vers 1.18.1-forge-39.9.18) with aquaculture 1.18.1-2.3.2 installed on both client and sever side, an error saying "Error loading mods 1 error has occurred during loading Aquaculture 2 (aquaculture) encountered an error during the sided_setup event phase

After restarting the client multiple times, it finally works. However, it's still an issue as we have to restart over and over all the time.

[crash-2022-01-12_17.24.24-fml - Copy.txt](https://github.com/TeamMetallurgy/Aquaculture/files/7859080/crash-2022-01-12_17.24.24-fml.-.Copy.txt)

**Comment by HumanMint** [comment]
![image](https://user-images.githubusercontent.com/19350964/149681797-361eabae-c734-42ea-93b8-5778b38922d1.png)
I have the exact same issue as well.. it works eventually after restarting a couple of times but it is becoming annoying

**Comment by GirafiStudios** [comment]
Sorry for getting back on this so late.
I´ve unfortunately been unable to reproduce this. Since it´s been a good while since anybody reported it, I gather it was probably any issue caused by Forge at the time.
