### ISSUE TITLE
Boxes, Lockboxes, and Crates do not generate in the latest 1.18 version 

### ISSUE THREAD

**Issue by hotdog2314** [TeamMetallurgy/Aquaculture#302]
I have fished for multiple hours without fishing up a single Box, Lockbox, or Crate. In this time, I have found 2 Neptune's bounties. I have also tried giving myself a Neptunium Fishing Rod equiped with bait and a nether star hook in a Creative world without any other mods to interfere, and the issue persisted. Am I doing something wrong, or are the fishing tables bugged?
Thanks! :)

**Comment by GirafiStudios** [comment]
You can definitely catch them in 1.18 :)
Sounds like you´re fishing with stuff that increases luck. The items mentioned is all counted as trash, and would therefor be quite unlikely when fishing with luck modifiers :)
