### ISSUE TITLE
Custom Fish Items Not Able to be Reeled In

### ISSUE THREAD

**Issue by AsokaDeg** [TeamMetallurgy/Aquaculture#303]
I've noticed that with my vanilla or custom rod from the mod works fine with vanilla fish, but it does not allow me to catch the custom fish within the mod. Not sure how to fix this. I am using the Better Minecraft 1.18.1 modpack and am running it on a server on my own machine. Any help would be appreciated.

**Comment by GirafiStudios** [comment]
Aquaculture allows any fishing rod to catch its new custom fish/loot. The Better Minecraft modpack must have changed things, or other mods is changing it.
