### ISSUE TITLE
"Incomplete set of tags received from server. Please contact server operator."

### ISSUE THREAD

**Issue by MyWorldNetwork** [TeamMetallurgy/Aquaculture#305]
I am still working on narrowing down whether there is more than one cause however running forge 39.0.63/ 1.18.1 I receive the above error when trying to join my server.

The client and server both load. The modpack had 190 mods, so far 15 of which, in alphabetical order, dependences aside, have been re-added without issue. #16 'Aquaculture 2', is where it fails.

SO far the issue arises with both 2.3.1 and 2.3.2

I will report back with any further info.

**Comment by GirafiStudios** [comment]
Been 14 days without reporting anything further back.
If you can provide a way to reproduce it, and it´s caused by Aquaculture - first then can I really try to fix it :)
