### ISSUE TITLE
Fish Fillet ForgeTags

### ISSUE THREAD

**Issue by Sinuisan** [TeamMetallurgy/Aquaculture#306]
Hi there, 

I'm trying to add the "raw_fish" tag to the Fish Fillet from your mod. However I'm struggling to understand how I'd do that, or locate the fish fillet item in your mod file structure. 

I'm fairly new to datapacks but I've made 1 or 2 so I _think_ I understand how it works. 

It would add some extended feature compat and be useful for when fishing with weighted fish. 

Any pointers would be appreciated.

**Comment by GirafiStudios** [comment]
It´s the same as when creating a datapack for vanilla, just have to use "forge" instead of "minecraft in the path.
This tutorial will hopefully be helpful :)
https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack
