### ISSUE TITLE
[1.16.5][Forge-36.2.20][2.1.21] NullPointerException crash

### ISSUE THREAD

**Issue by GabrielF-C** [TeamMetallurgy/Aquaculture#307]
Encountered this crash a few times.

[Crash report](https://github.com/TeamMetallurgy/Aquaculture/files/8077166/crash-2022-02-16_00.51.07-client.txt)

**Comment by GirafiStudios** [comment]
https://github.com/TeamMetallurgy/Aquaculture/commit/2cbf07bd8e9a0dad735a03ffd07cc2032269e2ef
