### ISSUE TITLE
Neptunium leggins not working ?

### ISSUE THREAD

**Issue by kylian-plard** [TeamMetallurgy/Aquaculture#308]
Hello there
I'm not sure I understood how Neptunium leggins work
Are they supposed to make you not falling in water ? Like staying at the level you currently are (no gravity in water) ? If it is the case, it doesn't work, I have them eqquipped and I'm still falling in water
Thanks in advance o/

**Comment by GirafiStudios** [comment]
It heavily reduces the speed of which you "fall" underwater. Making it not "fall" at all breaks swimming completely.

**Comment by kylian-plard** [comment]
Well I don't see any difference when I remove them tho, either when being underwater, or falling from high in water :/
Compared to other pieces of armor, I don't really get how useful they are ô_o

**Comment by zanecek** [comment]
For me leggins does nothing too...
