### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by WelpSTudent** [TeamMetallurgy/Aquaculture#310]
Hi, Aquaculture seems to be incompatible with https://www.curseforge.com/minecraft/mc-mods/ecospherical-expansion.
The dev of that mod strongly believes the issue is on Aquaculture's end in regard to how you get the fish to spawn in certain biomes
[crash-2022-03-01_21.06.07-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/8171658/crash-2022-03-01_21.06.07-client.txt)

**Comment by GirafiStudios** [comment]
I´m unable to reproduce the crash at all unfortunately. 
I´ve added a few null checks to hopefully prevent the issue. It´s for 1.18.2 though, so you would unfortunately have to wait for Ecospherical Expansion to update.
