### ISSUE TITLE
Tackle box crafting doesn't exist nor the box itself

### ISSUE THREAD

**Issue by eimer-gamer** [TeamMetallurgy/Aquaculture#315]
![2022-03-18_10 03 56](https://user-images.githubusercontent.com/97738103/158929745-b808898b-16fe-415e-a8ba-19aca2032e5c.png)
See? There is neither the crafting recipe or the items itself

**Comment by GirafiStudios** [comment]
You're playing Aquaculture 1 which is for 1.12 and before.

**Comment by eimer-gamer** [comment]
How to get Aquaculture 2 for 1.12.2?
