### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by ReobenH** [TeamMetallurgy/Aquaculture#319]
Hi! I was just wondering if there is going to be a 1.18.2 fabric version? I am planning to do an ocean world with my friends and most the mods we are using are on fabric. itd be nice to also have this one as it looks like a very good mod. if there are no plans for a fabric version then no problem.
(also this isnt really an ''issue'' but i dont really know how github works so sorry about that.)

Thanks, ReobenH

**Comment by GirafiStudios** [comment]
There is no plans to ever have a Fabric version, no.
