### ISSUE TITLE
Pacific Halibut and Atlantic Halibut bug

### ISSUE THREAD

**Issue by Sshhkaf** [TeamMetallurgy/Aquaculture#320]
Hello! There's bug with  Pacific Halibut and Atlantic Halibut; only their tails are visible. Please, could you repair this two fellas and update the mod?
![unknown](https://user-images.githubusercontent.com/103606410/163266756-52dd71ef-0274-4a57-9961-ce7b9a9b68cf.png)

**Comment by GirafiStudios** [comment]
What version are you on?

**Comment by Sshhkaf** [comment]
> What version are you on?

1.18.2!

**Comment by GirafiStudios** [comment]
A fix will be available on CurseForge, as soon as it gets approved :)
