### ISSUE TITLE
Worm Farm doesn't deposit into a hopper

### ISSUE THREAD

**Issue by RegulusCentauri** [TeamMetallurgy/Aquaculture#321]
Hey, I've tried it twice over. It's possible to use a hopper to deposit items INTO the Worm Farm, but the Worm Farm itself doesn't then deposit the WORMS into the next hopper (connected to a chest of course).
**Version is 1.18.1 - Aquaculture-1.18.1-2.3.3.jar**

Would be awesome if the fix could be deployed for 1.18.1 as well please. Not all the mods we use in our shared game have been updated to 1.18.2 yet.

Thank you in advance and thank you for what you've done with the mod, we're loving it so far!

**Comment by GirafiStudios** [comment]
That's very much intended, so it can't be fully automated :)
