### ISSUE TITLE
Compatibility with terralith 

### ISSUE THREAD

**Issue by Urias0** [TeamMetallurgy/Aquaculture#322]
Hello ,  i have a problem with terralith and aquaculture 2 , when i'm fishing in any terraltih biome i don't get any new fish and i sometimes don't get anything at all , reported it on the of this mod discord , tested something (i have no problem with new fish spawning or fishing on vanilla biome)  and then to the terralith discord , since it's a problem on their part and they told me this 

"Terralith is a datapack / a datapack packaged as a mod, which seems to prevent a lot of mods to read the biome categories, not sure, but maybe this will help https://github.com/Stardust-Labs-MC/biometweaker-configs 
I recommend forwarding this to the Aquaculture devs"

if you need any info ask me

**Comment by GirafiStudios** [comment]
Their biomes need to be in the BiomeDictionary in order to work with Aquaculture.
If the mod is purely datapack with zero code, that would be a problem.

It can be added with CraftTweaker though in a modpack.

**Comment by GirafiStudios** [comment]
The BiomeTweaker mod might work as well, as mentioned by the Terralith dev :)

**Comment by Urias0** [comment]
Hey , That's what i ended up doing and it worked perfectly , got all the fish available yesterday and almost got the entire armor , had no more problem with fishing nothing , but thanks for telling me i figured it out after i posted this issue
