### ISSUE TITLE
Report 

### ISSUE THREAD

**Issue by hkkl-VoeD** [TeamMetallurgy/Aquaculture#323]
![image](https://user-images.githubusercontent.com/105157776/167297970-5f4921db-cc9f-4bf8-bfa1-ae31709e28c6.png)

**Comment by GirafiStudios** [comment]
Duplicate of https://github.com/TeamMetallurgy/Aquaculture/issues/322
Problem is with how Terralith is only a datapack, shipped as a mod.

**Comment by hkkl-VoeD** [comment]
And what to do?

**Comment by GirafiStudios** [comment]
> And what to do?

Read the solution in the issue I linked :)
