### ISSUE TITLE
No loot in biome glitch in 1.18.2 server 

### ISSUE THREAD

**Issue by GhostlyGaming** [TeamMetallurgy/Aquaculture#324]
I get the following message when i try to fish in the water -
[aquaculture/]: Loot was empty in Biome: minecraft:ocean. Please report on Github

please let me know on how to fix this, Thank you

**Comment by GirafiStudios** [comment]
Does this happen when you only have Aquaculture 2 on the server?

This is most likely caused by a mod breaking the fish loot table, happens every once in a while.

**Comment by GhostlyGaming** [comment]
no it started happening recently after i added mods, I will check it and let you know, Thank you

**Comment by GirafiStudios** [comment]
Did you figure anything out?
Could be caused by a data pack as well btw.

**Comment by GirafiStudios** [comment]
Closing because of no response.
