### ISSUE TITLE
Only Vanilla Fish

### ISSUE THREAD

**Issue by ha7ak3** [TeamMetallurgy/Aquaculture#325]
I'm using the mod in the 1.16.5 version but I only got vanilla fishes, not aquaculture ones or treasures.

**Comment by GirafiStudios** [comment]
Does this happen when you only have Aquaculture 2 on the server?

This is most likely caused by a mod breaking the fish loot table, happens every once in a while.

**Comment by ha7ak3** [comment]
I have a lot mods I'll try acuaculture only and report back. Thanks.

**Comment by ha7ak3** [comment]
I had a datapack "classic fishing loot", I delete it and now I'm getting aquaculture fishes.

**Comment by GirafiStudios** [comment]
That´s the problem with datapacks, as they overwrite vanilla + mods completely. Good you figured it out :)
