### ISSUE TITLE
[1.16.5]Aquaculture2 cant work in arclight

### ISSUE THREAD

**Issue by SpicyFishOuO** [TeamMetallurgy/Aquaculture#326]
Hi, My ServerCore is arclight,
the neptunes_bounty works well in local game,
but its empty inside in server.
And if I swich to creative mode, it works again

maybe its a BUG and it still exists when only Aquaculture2 is added in the mods folder

Minecraft Version: 1.16.5
Server forge version: forge-1.16.5-36.2.26.jar
mod version: Aquaculture-1.16.5-2.1.22.jar
server core version: arclight-forge-1.16.5-1.0.23.jar
arclight github: https://github.com/IzzelAliz/Arclight/releases
arclight build station: https://ci.appveyor.com/project/IzzelAliz/arclight-16/build/artifacts

**Comment by Shadowclaimer** [comment]
Our mods do not provide support and compatibility for Bukkit-related systems.
