### ISSUE TITLE
Aquariums

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Aquaculture#33]
Aquariums are glass boxes that spawn renders of the icons of the fish in them to wander around inside them. The scale of the fish icon is based on its weight compared to its maximum weight. Could have a few different sizes of Aquarium, small would hold 1 fish, medium 2, large would be a 2x1x1 that stores 4 fish.

Recipe would involve gravel, glass panels and a bucket of water. Larger aquariums more of each or might just be a smaller aquarium + extra ingredients.

**Comment by Pulverizer** [comment]
Multiblock structures for larger aquariums?

**Comment by GirafiStudios** [comment]
Closing as this was planned before fish entities was added to Minecraft.
Notes about Aquariums is still kept in the spreadsheet
