### ISSUE TITLE
Compatibility issue with artifice

### ISSUE THREAD

**Issue by DarkWolf1911** [TeamMetallurgy/Aquaculture#331]
Duplicate enchantment id. invisibility enchantment.

Minecraft 1.7.10. Artifice 1.1.5. Aquaculture 1.2.6.21

![Screenshot (428)](https://user-images.githubusercontent.com/106776125/171731219-9ef22500-79c8-4ef8-9ac4-8e000de455e0.png)

**Comment by GirafiStudios** [comment]
Minecraft 1.7.10 have not been supported for like 5 years.
Pretty sure you can change the ID in the config(s)
