### ISSUE TITLE
Auqaculture.message0

### ISSUE THREAD

**Issue by DiggityMan420** [TeamMetallurgy/Aquaculture#333]
so i have it set to the default amount cuz i don't know how to add custom messages or even more if i got over 29 i get aquaculture.message30, etc. but even when i have it set at defulat i get aquaculture.message0 sometimes i think that a you fix not a me but if im wrong please lmk. also would love to add custom messages

see pic [https://ibb.co/0ZpR8Lm](https://ibb.co/0ZpR8Lm)

**Comment by GirafiStudios** [comment]
What version are you on?

**Comment by Aceplante** [comment]
this really feels like a bug. I was about to report it, but are you saying this is intentional? Jokes are fine, but this feels like a bug
