### ISSUE TITLE
Hook/Bait Crashes Server

### ISSUE THREAD

**Issue by Lokos2** [TeamMetallurgy/Aquaculture#335]
Me and some friends are playing on a server with the latest version of Forge (41.0.37)
Using a vanilla rod or a new rod with no modifications works fine, but whenever a rod with a hook and/or bait is cast into the water, the server will crash and kick everyone out. This also happened on earlier versions of forge, we thought maybe the latest would fix it.
No error message is given, but could perhaps be the same issue listed here: https://github.com/TeamMetallurgy/Aquaculture/issues/334

UPDATE:
Tried it in singleplayer and it is indeed the same error message as https://github.com/TeamMetallurgy/Aquaculture/issues/334

"The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.catchSound" is null
Exit Code: -1"

Mods used:
Aquaculture-1.19-2.4.0
architectury-5.7.27-forge
betteranimalsplus-1.19-11.0.6-forge
BiomesOPlenty-1.19-17.0.0.136
corpse-1.19-1.0.4
journeymap-1.19-5.8.5rc2-forge
TerraBlender-forge-1.19-2.0.0.112

**Comment by DiscoDude96** [comment]
This happens to me too, glad to know it's not just me.
