### ISSUE TITLE
mod instantly crashes game

### ISSUE THREAD

**Issue by LegitSpy** [TeamMetallurgy/Aquaculture#337]
self explanatory, newest update crashes game
log: https://pastebin.com/pgjWHjZQ
also this doesn't seem to be a mod conflict

**Comment by Chynosupremo** [comment]
Yeah, same issue here, i even tried isolating the mod and having it on it's own, still crashes.

**Comment by Chynosupremo** [comment]
ah yeah, makes sense aha, thanks for the quick response! :)
