### ISSUE TITLE
Mounting

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Aquaculture#34]
Reference photo:
![image](https://user-images.githubusercontent.com/2214143/39543585-aa95c846-4e19-11e8-9f22-a80195357286.png)

A wooden plaque you can stick a fish on that when right clicked will display the species, weight of the fish, and date it was caught. Would just be the icon of the fish rendered onto the wall (or a new series of artwork could be made to be rendered against it) similar to an item frame. Scale of the icon to the wall could be based on weight to weight maximum.

**Comment by GirafiStudios** [comment]
Closed by https://github.com/TeamMetallurgy/Aquaculture/pull/54
