### ISSUE TITLE
Error message whenever I try loading my game

### ISSUE THREAD

**Issue by HICMGUN** [TeamMetallurgy/Aquaculture#342]
The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: minecraft:empty
Exit Code: -1

This is the error that keeps coming up. This mod is one of the couple that causes it. The other two are U TEAM CORE and USEFUL BACKPACKS.

[crash-2022-07-08_22.45.21-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/9075743/crash-2022-07-08_22.45.21-client.txt)

**Comment by GirafiStudios** [comment]
Pretty sure this is because you´re using an old version of Forge, please update to Forge version 41.0.63 (A lot of mods does not work with 41.0.64 yet, hence why I recommend 41.0.63)
