### ISSUE TITLE
1.19 Internal Exception

### ISSUE THREAD

**Issue by SmaackBZ62** [TeamMetallurgy/Aquaculture#344]
Heyo! I'm trying to run Aquaculture 2 on an Apex server and am running into an issue that seems to have happened in the past and I tried the solution that was used there (downloading and using the jenkins23 jar file) to no avail, this is my first time submitting an issue on Github so let me know if I need to give any other info! I'm excited to try out the mod!

 ![image](https://user-images.githubusercontent.com/109389771/179325817-011a28e8-f485-4e67-aff9-2f8ddb8e1980.png)

**Comment by antiwesley** [comment]
While I'm not a person who works on this, if you can provide the error log, that will help them immensely. 
You can find them in your .minecraft folder under "crash-reports". This also gives them information about your version of Minecraft, the server info, and etc..

**Comment by SmaackBZ62** [comment]
Well, the weird thing is that the server is up and running but I (nor my friends) can connect to it, so there isn't a crash report to give, but let me know if there's any other details I should give

**Comment by GirafiStudios** [comment]
Are you sure you´re running Forge on the server?

**Comment by SmaackBZ62** [comment]
Yes, if it helps any I'm using their preset version of Forge for 1.19 which is 41.0.94 and the ability to use a custom version of Forge isn't there anymore so I can only use .94

**Comment by GirafiStudios** [comment]
Are you sure you´re using the same version of both Forge and Aquaculture on the server and the client?

**Comment by SmaackBZ62** [comment]
Sorry about the late reply but I didn't realize that you need to have both the client and the server modded to play modded servers (which kinda makes sense) but yeah! It's working! Thanks for the help!
