### ISSUE TITLE
This mod is incompatible with 1.19 advent of ascension. 

### ISSUE THREAD

**Issue by Thisguyneedshelp** [TeamMetallurgy/Aquaculture#347]
Not sure if its their fault or this mods fault but it says aquaculture2 sidesteps an event. Heres the crash log https://mclo.gs/oeIdc9x

**Comment by GirafiStudios** [comment]
Does this happen on startup?

**Comment by Thisguyneedshelp** [comment]
Yes it shows the error as sidesteps event as if it hadnt loaded properly

**Comment by GirafiStudios** [comment]
I was able to reproduce it on first launch with Advent of Ascension, but didn´t occur after that.
The crash was on Advent of Ascensions side for me though.
https://gist.github.com/GirafiStudios/b2eb2e1d7d7b1e038d5df5f95af68a38

**Comment by Thisguyneedshelp** [comment]
its in a large modpack but i keep getting the same problem with only aqua it works otherwise

**Comment by GirafiStudios** [comment]
Could you try if this fixes it for you? :)
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.19/25/

**Comment by Thisguyneedshelp** [comment]
im unfamiliar with this website do i download only the bottom one or both

**Comment by GirafiStudios** [comment]
The bottom one. The one that does not say api :)

**Comment by Thisguyneedshelp** [comment]
i tried that first luckily and it worked thanks!!!

**Comment by GirafiStudios** [comment]
Perfect! :)
