### ISSUE TITLE
"Connection Lost" error when use fishing pole

### ISSUE THREAD

**Issue by HinnoZ** [TeamMetallurgy/Aquaculture#348]
I recently updated to the most recent 1.19 forge version (1.19-41.1.0) to attempt to fix the invisible fishing line bug on my server. Now, the game runs perfectly fine until I try to use the fishing pole, at which point the game crashes and I receive the message shown in the image. 
![aquaculture error](https://user-images.githubusercontent.com/110078519/182250237-eabb397c-4615-4863-b004-5c0055b0eeca.PNG)

**Comment by GirafiStudios** [comment]
Weird question. Was the fishing pole created after you updated Forge, or after? :)

**Comment by GirafiStudios** [comment]
Should be fixed by Aquaclture 2.4.5
