### ISSUE TITLE
fishingline bug thing ?

### ISSUE THREAD

**Issue by lichgr3671** [TeamMetallurgy/Aquaculture#349]
![image](https://user-images.githubusercontent.com/109100627/182726024-90791fa9-c179-4589-89b8-4a480d5bde8d.png)
[latest.log](https://github.com/TeamMetallurgy/Aquaculture/files/9255476/latest.log)

**Comment by GirafiStudios** [comment]
Crash caused by the mod Randomium (Whatever that is).
