### ISSUE TITLE
Bobber Options

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Aquaculture#35]
![image](https://user-images.githubusercontent.com/2214143/39544041-da46daa2-4e1a-11e8-9022-ba7be7c85fdf.png)

Unlocked via Advancements #32 they allow you to customize your bobber a little bit. Either through a tackle box or a side inferface tab on the inventory, TBD.

**Comment by GirafiStudios** [comment]
Moved to #32
