### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by StarrSage** [TeamMetallurgy/Aquaculture#350]
Trying to load this mod gives an error that says "Failed to load correctly java.lang.InvocationTargetException: null"

**Comment by GirafiStudios** [comment]
Please provide a crash report, otherwise there is nowhere for me to even start attempting to look into the issue.

**Comment by StarrSage** [comment]
I’ve dealt with this issue on a few of my mods and have learned it has something to do with the mod needing to be updated for Forge. I am currently using the recommended 1.19 version.

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 are you using?

**Comment by StarrSage** [comment]
I was trying to use the latest 1.19 (not 1.19.1) version, 1.19-2.4.4.jar

**Comment by GirafiStudios** [comment]
There is no 1.19.1 version of Aquaculture 2, the 1.19 versions just work with it as well. Aquaculture 2.4.5 is built against the 1.19 recommended version of Forge.
