### ISSUE TITLE
No indication that this is a Forge only Mod

### ISSUE THREAD

**Issue by Coyote21** [TeamMetallurgy/Aquaculture#354]
I might be blind and missing the bleeding obvious (I do that alot) but I could find no mention or indication what-so-ever on your curseforge page that this is a Forge only mod.

The Forge API is not even listed in the dependencies. It took a lot of research through the issues to find out that it even requires any loader, either Fabric/Quilt or Forge, etc.

It might be nice if the mod page was edited to make it clear that this mod requires Forge and is Forge only.

**Comment by GirafiStudios** [comment]
It´s listed for every single file uploaded for years now.
![image](https://user-images.githubusercontent.com/6305377/186145137-7a4b687c-e55f-41fc-8626-6f7fe7c64f40.png)

**Comment by Coyote21** [comment]
Yep OK, I didn't see that before. Still it would be simpler to just put it on the Description page, instead of having to first click on Files then click on the title of the version you want before seeing that Supported Modloader message.

Personally, I almost never see this page b/c I just read the description and then go to the Files Page and click the Download button there for the appropriate version.

![image](https://user-images.githubusercontent.com/34091472/186204256-0f55bbfd-91fc-4d53-bdee-8ceffbbfcd4f.png)

Anyway it's your mod, and it's a great mod, and I greatly appreciate you generously donating your time to developing and maintaining it so pls don't read any of this a criticism. I was just hoping to help anyone else who made the same mistake as me.
