### ISSUE TITLE
The Chinese translation of the module's name is incorrect

### ISSUE THREAD

**Issue by hrh233** [TeamMetallurgy/Aquaculture#355]
Result: I imagined the Chinese translation of the module's name to be “水产业2/水产品2”[1]
Reason: The word "养殖" in the current Chinese name of the module (水产养殖 2) is a mistranslation and does not actually provide any “养殖” content（“养殖”in English means keeping animals or plants in order to produce young ones in a controlled way）. Because of this , I have therefore amended the translation to “水产品2/ 水产业2”

References：
[1]平瑛,李鸣.国际金融危机对中美水产品出口贸易的影响[J].湖南农业科学,2009(09):155-158.DOI:10.16498/j.cnki.hnnykx.2009.09.055.   :
This paper aims to assess the adverse effect of the financial crisis on China 's _aquaculture_ based on the analysis of the change trend of China 's aquatic products export to the United States .
通过对中美 **水产品** 出口贸易主要产品变动趋势的分析 , 判断金融危机对我国 **水产业** 带来的负面影响程度。

**Comment by GirafiStudios** [comment]
Sounds good :)
Could you please make a Pull Request with the changes?

**Comment by hrh233** [comment]
> Sounds good :) Could you please make a Pull Request with the changes?

ok
