### ISSUE TITLE
Request authorization

### ISSUE THREAD

**Issue by hrh233** [TeamMetallurgy/Aquaculture#357]
Dear All,
I am a Chinese player of Minecraft and I like the mod very much.However, this mod cannot be downloaded from a well-known Chinese Minecraft website-- www.mcmod.cn .Would it be possible for you to get your permission to open the download of this mod on that site?
And we promise: when licensed, it will provide the same Mod files for download as the official ones, without tampering with the gameplay, without attribution, without malicious files attached, and without any downloaders or plugins bundled.
Best wishes

**Comment by GirafiStudios** [comment]
Thank you for asking!
We do however not allow any of our files to be re-uploaded elsewhere.
You´re very welcome to link to the original files on CurseForge, if you wish to do so.

**Comment by hrh233** [comment]
> Thank you for asking! We do however not allow any of our files to be re-uploaded elsewhere. You´re very welcome to link to the original files on CurseForge, if you wish to do so.

All right,thank you.
