### ISSUE TITLE
Fish Mount performs inconsistently with fish placement

### ISSUE THREAD

**Issue by DevDrako** [TeamMetallurgy/Aquaculture#361]
Attached video is replicating a bug originally discovered by OutrightWings on Forge 40.1.68. Only Aquaculture-1.18.2-2.3.8 was present in the modlist.
https://user-images.githubusercontent.com/45469673/189519663-bfc172f0-7fec-4d28-9156-0b53479ef61a.mp4

**Comment by Shadowclaimer** [comment]
To note, I worked with this set of users to isolate this bug.

**Comment by GirafiStudios** [comment]
Unable to reproduce for 1.19
Don´t have the means to setup a 1.18 workspace atm.

**Comment by GirafiStudios** [comment]
Unable to reproduce for 1.18.2 with exact version specified, otherside a dev workspace.
 AQ2 for 1.18.2 is only receiving bug fixes, for issues that´s more impactful.
 
 If you can reproduce this for 1.19.2, please open a new issue :)
