### ISSUE TITLE
Can't get fish out of pool

### ISSUE THREAD

**Issue by moonidile** [TeamMetallurgy/Aquaculture#362]
I'm building a city with several mods installed, including this one. I am trying to build a public pool but I cannot seem to get fish out of the pool. Whenever I kill them all, a few minutes later, they respawn. Is there any way to not let the fish spawn?

**Comment by moonidile** [comment]
> I'm building a city with several mods installed, including this one. I am trying to build a public pool but I cannot seem to get fish out of the pool. Whenever I kill them all, a few minutes later, they respawn. Is there any way to not let the fish spawn?
This is in Minecraft version 1.16.5, Forge 36.2.34, Mod file name 1.16.5-2.1.22.jar

**Comment by GirafiStudios** [comment]
For 1.16.5 it checks in a + shape, to see if all neighbouring blocks is a water source block. Which is actually more requirements than vanilla had at the time.
This have been changed multiple times on newer Minecraft versions.
