### ISSUE TITLE
[Feature] Fishing Levels and skill trees

### ISSUE THREAD

**Issue by Morasiu** [TeamMetallurgy/Aquaculture#363]
It would be fun to have an option to level up 'Fishing skill" by just fishing. Each level could increase luck or something. 

Also adding some skill trees connected with levels would be amazing. 

Example skills:
* **Fisheater** - you can repair your fishing rod using fish.
* **Steady hands** - you can lure fishes faster
* **Shark fins** - you can swim fasters
* **Hardwood** - you have a chance not to use durability (like Unbreaking)
* **Water sorcerer** - your water bucket always have infinity (toggle on/off)
* **Diver** - you can spend more time underwater
* **Chef** - you can gain extra fillets (+chance for random treasure?)
* **Immortal corrals** - you can make corrals not die without water
* **Divine fish** - you can combine fish + water bucket to make fish in the bucket
* **Worm digger** - you have a chance to double your worms from sources
* **Ice breaker** - you can break ice with silk touch using your rod

**Comment by Shadowclaimer** [comment]
Cool idea but not within the scope of the mod. We like to keep it rather vanilla+ and build upon the systems provided.

**Comment by Morasiu** [comment]
Oh, man. I get it :( Still, keep up a good work :)
