### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by SegoItCh** [TeamMetallurgy/Aquaculture#367]
https://paste.gg/p/anonymous/7c3c064e899545f8979c62646d08b84a

**Comment by GirafiStudios** [comment]
Change the enchantment ids in the config, as it's clashing with another mods enchantment ids.
Common thing you had to do back in the day.

Also 1.7.10 have not been supported for over 5 years

**Comment by SegoItCh** [comment]
So 1.12.2 better in this term?

**Comment by GirafiStudios** [comment]
Yes, Enchantment IDs got removed in Forge later on & was automatically assigned, so there wouldn´t be any more conflicts :)
Back in 1.6.4 and before, there were the same problem with items and blocks, so getting a modpack to run back in the day was quite difficult!

**Comment by SegoItCh** [comment]
This mod won't help? https://www.curseforge.com/minecraft/mc-mods/enchantment-id-extender

**Comment by GirafiStudios** [comment]
Only if you´ve run out of Enchantment IDs to use (256 normally). Otherwise you would still have to manually make sure no enchantment ids is conflicting. Normally mods would have a config to change the enchantment ids
