### ISSUE TITLE
1.7.10 Entity ids not in config

### ISSUE THREAD

**Issue by GamebP** [TeamMetallurgy/Aquaculture#368]
When playing with [Aquaculture-1.7.10-1.2.6.21.jar](https://www.curseforge.com/minecraft/mc-mods/aquaculture/files/2285775) in config folder it does have Aquaculture.cfg but inside it dosent have the entity named EntityCustomFishHook or CustomFishHook(rebelkeithy.mods.aquaculture.handlers.EntityCustomFishHook)

**Comment by GirafiStudios** [comment]
Aquaculture for 1.7.10 have not been supported for over 5 years.
Additionally you´re not providing any problem caused by that their IDs are not configurable.

**Comment by GamebP** [comment]
I mean, your mod config dosent provide entity ids on fish hook.. whatever was it.
