### ISSUE TITLE
[Request] Oredict fish

### ISSUE THREAD

**Issue by Mike-U5** [TeamMetallurgy/Aquaculture#37]
It would be nice for cross-mod compatibility if every fish was registered in the **fish** oredict entry.
Perhaps exlude special catches such as the Turtle and Fish Bones.

**Comment by Shadowclaimer** [comment]
Its under consideration and discussion. Thank you =D

**Comment by Shadowclaimer** [comment]
The actual item driftwood as a log block equivalent?

**Comment by Shadowclaimer** [comment]
Misclick

**Comment by GirafiStudios** [comment]
OreDictionary is no longer a thing in 1.14.
All fish added to the "fishes"-tag in 1.14.2 though
