### ISSUE TITLE
[Feature] Neptunium Armor/Tools Value Tweaking

### ISSUE THREAD

**Issue by MrHipsterG** [TeamMetallurgy/Aquaculture#370]
While trying to design a Modpack featuring Aquaculture 2 in 1.18.2 it has become apparent that the stats on Neptunium gear is the strongest in the pack, stronger than Netherite by a large margin.

Would it be possible to allow for tweaking of these stats through the config file? Specifically the armor and armor toughness values and the attack damage values of weapons and tools.

**Comment by GirafiStudios** [comment]
Sounds like you found a workaround, based on what you said on Discord :)
