### ISSUE TITLE
Box Loot Tables Not Working?

### ISSUE THREAD

**Issue by viiizee** [TeamMetallurgy/Aquaculture#372]
I was hoping you could help me with an issue I'm having with some data packs that I've made for my mod pack. They are intended to modify Aquaculture loot tables; however, when I load a world and attempt to use these items, they won't open on right click? I'm assuming it's because there is something wrong with the syntax or weights, as I've triple checked the mod id's and they all seem to be correct... the weird thing is that the default structure in aquaculture name state folders have the treasure chest as 40, 50's etc, but the others are with sub-10 numbers (1,2,3..10) I tried to follow this structure and now the box and lockbox are not working, but the treasure chest is working? Super confused.

Are the numbers here supposed to add up to 100? I made sure to do this, but maybe I just have too many entries as a whole?
[datapack.zip](https://github.com/TeamMetallurgy/Aquaculture/files/10024526/datapack.zip)

**Comment by GirafiStudios** [comment]
Github is not a place for general support, our Discord would be a better place for that. Invitation link can be found on the Aquaculture 2 Curseforge page.

Took a quick look at the datapack you have attatched & the jsons look fine. The numbers are as they´re supposed to, yes.
Is that the same file structure you´re using in your actual datapack?
The jsons need to be in data/aquaculture/loot_tables/box/
