### ISSUE TITLE
1.19.3 port

### ISSUE THREAD

**Issue by gohkenytp** [TeamMetallurgy/Aquaculture#374]
Sorry to bother you but could you port this to 1.19.3 please? Thanks!

**Comment by GirafiStudios** [comment]
Is it not working for 1.19.3?

**Comment by gohkenytp** [comment]
It's not working for 1.19.3

**Comment by GirafiStudios** [comment]
There is currently a bug in Forge, which prevents us from being able to add new loot to the fishing loot table, hence why there is not a release yet.
If you want to play around with an early build, you can grab one here: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.19/
