### ISSUE TITLE
Rods don't function in offhand - 1.18.2

### ISSUE THREAD

**Issue by BitBlitObviMormon** [TeamMetallurgy/Aquaculture#375]
The bobber disappears when the rod is held in the off hand. You can even spam click it to cast but the bobber will immediately disappear after casting. The vanilla rod can still be used to fish with the off hand. Confirmed to happen with Aquaculture as the only mod installed.

Forge 40.1.73
Aquaculture 1.18.2 - 2.3.9

**Comment by GirafiStudios** [comment]
Thanks for reporting!
Seems to be a problem in 1.18.2 only, as it works in 1.19

**Comment by BitBlitObviMormon** [comment]
So, you don't intend to patch it on 1.18?

**Comment by GirafiStudios** [comment]
I fixed it, as the reference to the commit says?
A new version with the fix is already released on CurseForge.

**Comment by BitBlitObviMormon** [comment]
Oops, you're right. My mistake, sorry!
