### ISSUE TITLE
Russian translation bug

### ISSUE THREAD

**Issue by ShamHyper** [TeamMetallurgy/Aquaculture#376]
**Greetings!**

I found a problem that the mod has a json file with a translation into Russian, but there is no such Russian language (version 1.19.2, on all versions of your mod)

I found the reason using the Compare plugin in Notepad++ 

**You forgot to put one comma on the 285th line)**

I'm sending a file with a corrected translation, change it in the current version for the rest of the Russian players (I'm not sending json, since GitHub does not skip it)

**Good luck, dear developer!**

[ru_ru.json.txt](https://github.com/TeamMetallurgy/Aquaculture/files/10262627/ru_ru.json.txt)

**Comment by ShamHyper** [comment]
![image](https://user-images.githubusercontent.com/104412752/208518634-1ebcfd81-9378-4d2a-95b5-483ed305bdfc.png)

Now all working fine)

**Comment by GirafiStudios** [comment]
Fixed in the 1.19.3 version already :)
