### ISSUE TITLE
Incompatable with WeaponLeveling

### ISSUE THREAD

**Issue by Elaski6573** [TeamMetallurgy/Aquaculture#377]
Neptunium fillet knife has nbt problem.
other knives has nbt { "Damage": 0 } so it doesn't make problem.
But Neptunium fillet knife has "blank" nbt
WeaponLeveling thinks that tool is broken. So I can't use this knife.
I think that need to fill up nbt tag to prevent this problem.
Like { "Damage": 0, "Unbreakable": 0b }
![image](https://user-images.githubusercontent.com/114150904/209036352-b54f2728-6a94-48c6-9a51-4d7f52630100.png)
![image](https://user-images.githubusercontent.com/114150904/209037346-d70a5c6a-c2ca-44b7-877d-dc575f1c15c5.png)

https://github.com/GeradesoLukas/weaponleveling/issues/31

**Comment by GirafiStudios** [comment]
I'm not familiar with the mod, but according to their Github page, it only works with axes and swords, where the fillet knifes is neither of those.
Fillet knives is also not really meant to be useful as a weapon.
