### ISSUE TITLE
Can't launch my Aternos Forge server with AquaCulture2 on it !

### ISSUE THREAD

**Issue by BluePlanet04** [TeamMetallurgy/Aquaculture#379]
So this mod was really interesting for me so I decided to try it out on an aternos Forge server.
So I install in aternos and then I launch my server and when I tried to connect to it it was showing this :

Internal Execption: io.netty.handler.codec.DecoderException: javalang.IllegalArgumentException: Unknow recipe serializer aquaculture:crafting_special_fish_fillet

Please help me

**Comment by Shadowclaimer** [comment]
We do not provide support for server hosting installation setups.
