### ISSUE TITLE
The game crashes when picking up the Neptunium Fillet Knife.-1.19.2

### ISSUE THREAD

**Issue by JellyBubb1e** [TeamMetallurgy/Aquaculture#380]
[crash-2023-01-02_20.40.10-server.txt](https://github.com/TeamMetallurgy/Aquaculture/files/10331685/crash-2023-01-02_20.40.10-server.txt)

**Comment by GirafiStudios** [comment]
Unable to reproduce.
Crash log is not providing any useful information either, as it´s not mentioning Aquaculture at all.

**Comment by Bronski** [comment]
I'm getting this now, when I mouse over the knife it's done. I AQ2 to Luna Pixel's "Better MC Forge" v13 pack. My crash log looks like OPs:

https://gist.githubusercontent.com/Bronski/10ae09c5229e51e62115107a1878c076/raw/9d65e0801d4d645eaef261cf5345e7a04aa2cb64/gistfile1.txt
