### ISSUE TITLE
Saltwater fish spawn in places I don't think they're supposed to, and don't spawn in places I think they are

### ISSUE THREAD

**Issue by annelidCerebellum** [TeamMetallurgy/Aquaculture#381]
Checking through the Discord it seems that "saltwater" is intended to refer to strictly oceans. However, fish from the saltwater spawn table (red grouper, jellyfish, tuna) spawn in bodies of water in many non-ocean biomes and seemingly not at all in oceans.

![mushroom-fields](https://user-images.githubusercontent.com/106266478/210436561-044ec7af-7a26-4c19-bec0-3e9db1f89ade.png)
![ocean](https://user-images.githubusercontent.com/106266478/210436564-b4ed9c86-0934-4d3c-8973-d8e3c39d7ae8.png)
![plains](https://user-images.githubusercontent.com/106266478/210436569-034819fb-1b60-40f9-85a7-6e6579fbd626.png)
![river](https://user-images.githubusercontent.com/106266478/210436574-75eb73ee-946a-4a88-aaab-4a48b2e1b3c4.png)
![warm-ocean](https://user-images.githubusercontent.com/106266478/210436579-4ee42097-25a2-4552-962f-e1496f0b0def.png)
![cold-ocean](https://user-images.githubusercontent.com/106266478/210436588-84c30901-2f2a-4899-a2b7-0ba1dde40fd9.png)
![desert](https://user-images.githubusercontent.com/106266478/210436594-f793dc4a-8152-4189-acaf-e76e74407e3c.png)
![frozen-ocean](https://user-images.githubusercontent.com/106266478/210436597-348e6a9d-dc62-45e2-af3c-f8cc8e37f6ab.png)
![jungle](https://user-images.githubusercontent.com/106266478/210436599-0250e2db-fd88-44e2-811a-85067ec5161c.png)
![lukewarm-ocean](https://user-images.githubusercontent.com/106266478/210436604-ded0e32a-8e07-424e-8a8d-4a651b059af7.png)

![2023-01-03_16 24 28](https://user-images.githubusercontent.com/106266478/210437719-6ec5fcac-9b3c-4338-89c6-40467cc748df.png)

Screenshots show results of tests conducted in a 1.19.3 install with no mods except for Aquaculture 2. Tests involved creating a single biome world of the biome in question (F3 screen is visible in each to see which, except for the screenshot of a plains world where I forgot), making a hole with water between y=50 and 63 (the levels at which fish naturally spawn according the Minecraft wiki), then using command blocks to continuously kill any fish that spawn and collect their drops.

Please note this testing covers only spawns of fish mobs in the world, not fishing drops, but I have incidentally pulled saltwater fish in seemingly freshwater biomes so it is likely the same issue applies.

**Comment by GirafiStudios** [comment]
Looks like I made a few mistakes, when moving over to the new mob spawn system in 1.19.
For Jellyfish for example I had aciddently made it so it would only appear in the biomes it was not supposed to.

Will get out a fix sometime today :)

**Comment by GirafiStudios** [comment]
Same problem with Red Grouper & Tuna.
From what I can tell from the pictures, those are the only 3 fish that´s the problem as well - unless I´m missing something?

**Comment by annelidCerebellum** [comment]
I don't think you're missing anything, that was my takeaway as well.
