### ISSUE TITLE
request: Fish models and textures that better suit fish

### ISSUE THREAD

**Issue by epicspeco** [TeamMetallurgy/Aquaculture#384]
was wondering if there were any plans of upgrading some of the models so they look more like the species of fish they're meant to resemble and can be better differentiated from one another?? especially the gar, muskie and arapaima who look nothing alike in real life but share the same model in the mod.
 also most of the fish models and textures don't include the defining features and textures of the species of fish they're meant to look like (fin structure defining patterns, etc.)
![image](https://user-images.githubusercontent.com/124405020/216723890-eff32a93-b517-45ed-8c53-4e476a8ef81a.png)
 (for example the blue gill could have a model that is more round and flat that resembles the body shape of a pan fish, and have the classic ear spot that all sunfish have). maybe I'm just too picky about these things being a big fish nerd, and not really having any modding experience, but I think this would be doable?

also in my game (Minecraft 1.9.2) groupers and tuna spawn in swamps, and jellyfish spawn in all biomes

**Comment by Shadowclaimer** [comment]
We have been specifically keeping them using vanilla style fish models and keep them as simple as possible. So this won't be happening (though that's not to say some models might not change in the future, but the style is definitely intentional.)
