### ISSUE TITLE
Losing server connection on singleplayer

### ISSUE THREAD

**Issue by Herobattler** [TeamMetallurgy/Aquaculture#385]
Losing server connection on singleplayer when creating a world or joining an existing world. 

1.19.2-2.4.8.jar
Uploaded by
[Girafi](https://www.curseforge.com/members/girafi)
Uploaded
Nov 8, 2022
Game Version
1.19.2   +3
Size
569.70 KB
Downloads
1,101,397
MD5
072d1a0422d9bba07ce517b9b43781bc

**Comment by GirafiStudios** [comment]
Please provide logs, can't do anything with that information.

**Comment by GirafiStudios** [comment]
Closing as no additional information was provided.
