### ISSUE TITLE
Support for tilling rich soil from Farmer's Delight

### ISSUE THREAD

**Issue by WFPhantom** [TeamMetallurgy/Aquaculture#386]
FD's rich soil makes plants grow faster and is an incredible way to upgrade farms, not to mention FD being undoubtedly the best food mod in the game, and extremely popular, many people have it in their modpacks. That's why I'm requesting compat for tilling the rich soil from FD with the Neptunium Hoe, while still keeping the positive effects from FD's rich soil and the always stay moist feature from Aquaculture.

**Comment by GirafiStudios** [comment]
Thanks for your suggestion, but that's not really something we're interested in implementing :)
