### ISSUE TITLE
Suggestion: Upgrading fishing rods using smithing table

### ISSUE THREAD

**Issue by AnasterianSunstrider** [TeamMetallurgy/Aquaculture#389]
Enchantments are expensive and it would be nice if we could upgrade our fishing rods to the next tier using the smithing table so we don't have to start the whole process again.

**Comment by GirafiStudios** [comment]
We try to keep to vanilla behaviour as much as possible. As the smithing table is only for upgrading diamond gear to netherite gear, it's a bit out of scope currently.
If we ever add a Netherite Fishing Rod, we would probably add this functionality for that.
