### ISSUE TITLE
More configuration options?

### ISSUE THREAD

**Issue by Guinaro** [TeamMetallurgy/Aquaculture#390]
Hi,
I'm trying to configure my modpack, but some aquaculture items are giving issues.
Crafttweaker cannot configure the burntime of the wooden fillet knife aswell as driftwood.

I would like to disable the fillet knifes and make my own recipes with the Croptopia knife instead.
I would also like to disable all the Neptunium Gear (armor and weapons).

By disabling I mean, not appearing in game at all, because even if I hide them with JEITweaker, they will still appear in categories like the Anvil, Fuel, ...

Would it be possible to add configuration options for this?
Wooden Fillet Knife Burntime in Ticks (default 150)
Driftwood Burntime in Ticks (default 600)
Disable Fillet Knifes? (Also disables the Recipes ofcourse) (Default False)
Disable Neptunium Gear? (Default False)

Thank you,
Guinaro

**Comment by GirafiStudios** [comment]
There is already a config option to disable Neptunium gear.
Fillet knifes recipes can be disable with a data pack, if you add your own empty json, for the fillet knife recipe serializer.
Removing burn times from AQ2 items should be possible with CraftTweaker, as we implent it the same way all other mods do it as well.

**Comment by Guinaro** [comment]
Using
<item:aquaculture:wooden_fillet_knife>.burnTime = 0;
Or <item:aquaculture:wooden_fillet_knife>.burnTime = 200; //Alters burntime in a furnace to 1 item, instead of the standard 0.75 of an item.
Has no effect. In game. The knife stays present in the Fuel Tab. And you can use a knife to burn items for 0.75 items.
I tried this before in 1.18.2 aswell, aswell in that version with KubeJS. And all the results are the same, no effect on burntime of the items.
I can only guess that setting burntime inside the code happens later than when the scripts of crafttweaker or kubeJS run. So aquaculture code has the last say over the value.

I also know that you provide options for disabling the recipes, but you there is no option to simply not registering the items in the first place. I can understand if this is to difficult to implement. Jeitweaker does provide an function to hide the item, but for eg. gear and armor this is insufficient as we reviewing all recipes, the items still appear in various tabs (like anvil and such), that's why I requested if it is possible to fully disable the items, and not only the recipes.

Sinceerly,
Guinaro
