### ISSUE TITLE
[1.19.4] [Forge} MIssing Fish Fillet recipe on JEI

### ISSUE THREAD

**Issue by ffuentesm** [TeamMetallurgy/Aquaculture#392]
Is this a JEI or Aquaculture problem? 
![image](https://user-images.githubusercontent.com/44974827/230752882-c59309ba-53da-413d-a998-793381a93257.png) ![image](https://user-images.githubusercontent.com/44974827/230753171-03a4a962-fff4-4a17-920e-fe2b45144493.png)

**Comment by GirafiStudios** [comment]
It's a problem on our end. JEI wasn't updated, when AQ2 got updated.
