### ISSUE TITLE
Can't craft any of the new Fishing Rods

### ISSUE THREAD

**Issue by Manic137** [TeamMetallurgy/Aquaculture#393]
I'm on Fabric 1.18.2, Ver. 2.3.11, and for some reason I can't craft the new fishing rods. Here is my mod list:
        - antixray 1.2.1
	- arcanus 1.29
	- architectury 4.11.89
	- balm-fabric 3.2.6
	- c2me 0.2.0+alpha.7.38
	- cardinal-components 4.2.0
	- chunky 1.2.164
	- cloth-config 6.4.90
	- clumps 8.0.0+17
	- collective 6.53
	- companion 2.0.1
	- couplings 1.8.0+1.18.2
	- creativecore 2.6.12
	- dataattributes 1.3.0
	- dragondropselytra 3.0
	- dynview 1.18.2-2.3
	- elytra_aeronautics 1.1.0
	- essential_commands 0.32.0-mc1.18.2
	- fabric-api 0.76.0+1.18.2
	- fabricloader 0.14.18
	- fastload 1.5.10
	- feature_nbt_deadlock_be_gone 2.0.0+1.18.2-rc1
	- ferritecore 4.2.1
	- fireplacelib 6.3.1+1.18.2
	- fishofthieves 1.1.1
	- flan 1.18.2-1.8.4.1
	- forgeconfigapiport 3.2.4
	- forgero 0.10.6-BETA-1.18.2
	- golfiv 0.5.2
	- gottagofast 1.0.2
	- hardcorerevival 8.0.1
	- immersive_armors 1.5.4+1.18.2
	- immersive_paintings 0.5.1+1.18.2
	- immersivemc 1.3.0
	- java 17
	- krypton 0.1.9
	- lazydfu 0.1.2
	- lithium 0.10.3
	- map_atlases 2.3.0
	- mcdiscordchat 2.1.3
	- memoryleakfix 1.0.0
	- minecraft 1.18.2
	- mostructures 1.4.2+1.18.2
	- patchouli 1.18.2-71.1-FABRIC
	- playerex 3.4.2
	- purpeille 2.3.3+fabric-1.18.2
	- relicex 3.3.1+1.18.2
	- repurposed_structures 4.1.15+1.18.2
	- smoothboot 1.18.2-1.7.0
	- sound_physics_remastered 1.18.2-1.0.6
	- spark 1.9.11
	- spawn_animations_mr 1.8.2
	- starlight 1.0.2+fabric.89b8d9f
	- starterkit 5.2
	- t_and_t 1.10.0.1
	- torchhit 6.0.1.2
	- totw_additions 1.2.1
	- travelersbackpack 1.18.2-7.1.22
	- trinkets 3.3.1
	- unforgivingvoid 3.1.3+1.18.2
	- villagernames 5.2
	- villagespawnpoint 4.0
	- vivecraft 1.18.2-0.0.15
	- voicechat 1.18.2-2.4.3
	- vrapi 3.0.2
	- wandering_collector 1.2.0+mc1.18.2
	- waystones 10.2.0
	- wwoo 2.6.2+1.18.2
	- xercapaint fabric-1.18.2-1.0.1
	- yigd 1.3.14

**Comment by GirafiStudios** [comment]
Aquaculture 2 is not for Fabric? It shouldn't load at all for Fabric.
