### ISSUE TITLE
Hooks Not working

### ISSUE THREAD

**Issue by Aceplante2** [TeamMetallurgy/Aquaculture#394]
The dual hook does not seem to give me double drops when held in my offhand. I am probably doing it wrong but I could not find any explanation on how to actually use hooks/worms.

**Comment by GirafiStudios** [comment]
What Aquaculture 2 version are you on?

**Comment by Aceplante2** [comment]
1.18.2 forge?

**Comment by Aceplante2** [comment]
Nvm im dumb. You should maybe make it more clear you can only attach hooks/worms with the tackle box

**Comment by GirafiStudios** [comment]
I´ll add that to the wiki :)
