### ISSUE TITLE
Suggestion: Add Neptunium nuggets to Bounty

### ISSUE THREAD

**Issue by Aceplante2** [TeamMetallurgy/Aquaculture#397]
As of now, neptunium nuggets are completly unused and unobtainable unless you manually craft them. Even smelting down a piece of neptunium gear gives you an ingot instead of a nugget (which, to clarify, is a good thing). Still, I appreciate the fact they exist, and perhaps servers can use them as a sort of currency, but I feel like they could be better integrated.

Neptunes bounty should contain 1-4 nuggets in addition to the neptunium item. It would be small, but after a few they add up to an ingot you can use for something else!

**Comment by Shadowclaimer** [comment]
I like this idea but I don't think we'll be implementing it.

The nuggets are mostly there as a support thing for modpacks that want to do more with Neptunium or balance other mechanics with it. The reality is by the time you'd have enough nuggets to craft something, you'd probably have a large amount of Neptunium, and I don't want to put too much value in each chest (as each Neptunium chest is already insanely high value.)

We could however add Neptunium nuggets to the treasure table which I think would be a better option. (@GirafiStudios)

**Comment by Aceplante2** [comment]
Perhaps have each chest only have a chance to contain a neptunium item, making it not guaranteed. But at least, with this change, you can count on at least a few nuggets?

**Comment by GirafiStudios** [comment]
Basically our Neptunium Loot table is added with a weight of 1, to the treasure loot table.
If you "hit" the Neptunium Loot Table, there is then a 33% chance to get a Neptune's Bounty, 33 % to get a Neptunium Nugget & then a 33% chance it'll just default back to the fish loot table :)

**Comment by Aceplante2** [comment]
a single nugget? I think 1 nugget seems kind of underwhelming. If you had gotten an item, you can smelt it down into 1 ingot, or the equivalent of 9 nuggets. How about 2-4 or something?

Also, this treasure loot table is rolled once in each bounty right? In that case I think 33% for an item, 33% for nuggets and 33% for fish seems balanced and fair
