### ISSUE TITLE
Suggestion: Better fishing mechanic

### ISSUE THREAD

**Issue by Aceplante2** [TeamMetallurgy/Aquaculture#398]
You should be able to right click and hold to charge your cast (similar to a bow), which increases the distance the hook goes when you let go. You could still click instantly to cast it the normal distance, but this new mechanic of also being able to cast farther could be useful in some cases, such as pvp?

**Comment by GirafiStudios** [comment]
That would be altering how fishing in Minecraft works quite a bit. The aim of Aquaculture is to expand on the vanilla fishing, not to change it.
