### ISSUE TITLE
Include fillets in raw_fishes for compatibility

### ISSUE THREAD

**Issue by Aceplante2** [TeamMetallurgy/Aquaculture#399]
If fillets were included in forge:raw_fishes, they would be compatible with other mods such as farmers delight. As of now, they are ONLY used in your mod's sushi recipe

**Comment by GirafiStudios** [comment]
They are included.
https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/resources/data/forge/tags/items/raw_fishes.json

**Comment by Aceplante2** [comment]
Then it doesnt seem to work? Fillets are not valid in recipes that use forge:raw_fishes
