### ISSUE TITLE
Neptunium Leggings not having any effect.

### ISSUE THREAD

**Issue by Flyvee** [TeamMetallurgy/Aquaculture#402]
I saw that the leggings is supposed to help with dropping slower in water but I've timed it with and without the leggings and there is no difference. You mentioned in a previous issue about this that there isn't a way to stop a person from dropping underwater. In this link, is the fabric origin code for how they managed to stop a player from dropping in water, maybe it can help you figure out a way for the leggings to work? https://github.com/apace100/origins-fabric/blob/1d52bae374f591425a603134b06c2bbbc04c7d9c/src/main/java/io/github/apace100/origins/mixin/LikeWaterMixin.java#L23

I really do love this mod especially with the fishing (I have fished 2832 times in my survival server) and I nearly have the full set of tools and armor, but I'm a bit sad to see the leggings not doing anything special.

**Comment by GirafiStudios** [comment]
What version are you on?
They for sure made you drop a lot slow er at one point, could of course have broken since.

**Comment by Flyvee** [comment]
I'm using the latest one on 2.4.14
