### ISSUE TITLE
1.18.2 Can't catch Neptne's Bounty?

### ISSUE THREAD

**Issue by Snowballniubi** [TeamMetallurgy/Aquaculture#403]
I've been fishing for a long time but I can't catch it Neptne's Bounty 

Here are the mods I installed
Doesn't matter if it's solo or server
Also try with enchanted book
Sorry, I use GOOGLE translation
![mods](https://github.com/TeamMetallurgy/Aquaculture/assets/133849254/c66a9321-09d1-4b21-a05c-984d44c54f17)

**Comment by GirafiStudios** [comment]
Make sure you fish in "open water" (Google the definition, it's vanilla behaviour for all treasure).

**Comment by Snowballniubi** [comment]
> 確保你在“開闊水域”釣魚（谷歌定義，這是所有寶藏的普通行為）。

Does open water mean where there is no land in sight? Or just out to sea?

I've tried all kinds of waters and caught different kinds of fish
but i still don't see Neptne's Bounty

**Comment by GirafiStudios** [comment]
Out to sea would work, but it's not quite that difficult of a requirement.

You can read more about it here:
https://technical-minecraft.fandom.com/wiki/Fishing

**Comment by Snowballniubi** [comment]
> 出海是可行的，但要求並不那麼困難。
> 
> 您可以在這裡閱讀更多相關信息： [https ://technical-minecraft.fandom.com/wiki/Fishing](https://technical-minecraft.fandom.com/wiki/Fishing)


ok i'll try it out thank you!
