### ISSUE TITLE
Rainbow Trout

### ISSUE THREAD

**Issue by Teralitha** [TeamMetallurgy/Aquaculture#407]
Is a freshwater fish but you have it spawning in the ocean.

**Comment by GirafiStudios** [comment]
No it´s not. It´s native to the pacific ocean.

**Comment by Teralitha** [comment]
That is incorrect.  It is native to freshwater rivers and lakes, but is known to migrate into saltwater.  Plenty of info on this found on google.  So technically it does exist in saltwater, but its primarily a freshwater species.

**Comment by Shadowclaimer** [comment]
They are correct Girafi it is a freshwater fish.

Its traditionally from tributaries of the Pacific Ocean but that just means rivers that branch and head to it.

**Comment by Teralitha** [comment]
Its ok.  I dont want to make a big deal out of it.  They technically exist in both fresh and salt water.  But they are only in saltwater in this mod, which is something that nags at me in my mind.  Would be nice to see them in freshwater too in this mod.  Or add a different type of rainbow trout to rivers.

I would suggest Steelhead rainbow trout for oceans, and just rainbow trout for rivers/lakes

**Comment by Shadowclaimer** [comment]
> Its ok. I dont want to make a big deal out of it. They technically exist in both fresh and salt water. But they are only in saltwater in this mod, which is something that nags at me in my mind. Would be nice to see them in freshwater too in this mod. Or add a different type of rainbow trout to rivers.
> 
> I would suggest Steelhead rainbow trout for oceans, and just rainbow trout for rivers/lakes

Yep was thinking about this actually. Eventually I'll add a distinguishing difference, for now they'll just be in both.

Also there's a few subtypes of Rainbow Trout which muddled this discussion as well. Its not a big deal, its an interesting discussion and I always like learning things.
