### ISSUE TITLE
Tools missing from forge tags on 1.19.2 Plus

### ISSUE THREAD

**Issue by ModernGamingWorld** [TeamMetallurgy/Aquaculture#409]
Hoes missing from forge:tools/hoes & forge:hoes tag
Pickaxes missing from forge:tools/pickaxes & forge:pickaxes tag
Shovel missing from forge:tools/shovels & forge:shovels tag
Axes missing from forge:tools/axes & forge:axes tag
Swords missing from forge:tools/swords & forge:swords tag

This would allow your recipes to work with other mods that use these tags and save us Modpack developers having to add them ourselves

**Comment by GirafiStudios** [comment]
It´ve been added to the latest 1.19.4 release. Why are you on 1.19.2?
