### ISSUE TITLE
Neptune's Bounty chest does not drop loot. 1.19.4, (FORGE 45.1.2)

### ISSUE THREAD

**Issue by LoquendoCrack** [TeamMetallurgy/Aquaculture#411]
When I fish for Neptune's Bounty and open it, I am surprised that it is empty, it contains nothing.

It should be noted that I am on a server with more than one player, and more than one of the players tells me that
Neptune's Bounty gives them nothing.

I hope you can help me thanks.

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 and Minecraft Forge are you using?

**Comment by LoquendoCrack** [comment]
- Aquaculture-1.19.4-2.4.16
- Forge 45.1.2

**Comment by GirafiStudios** [comment]
Are you using just normal Forge on the server, or some sort of Forge/Bukkit hybrid to run the server?

**Comment by LoquendoCrack** [comment]
I use Mohist 1.19.4 that include the forge 45.1.2.

**Comment by GirafiStudios** [comment]
This is a problem with Mohist. What adds the loot to Neptune's Bounty is a vanilla loot table function.
That is for some reason broken with Mohist.

**Comment by LoquendoCrack** [comment]
thanks
