### ISSUE TITLE
Suggestion: Option to allow for "sunny fishing" (no rain needed for faster casts)

### ISSUE THREAD

**Issue by Bronski** [TeamMetallurgy/Aquaculture#413]
I do a lot of fishing when I play MC. I'd love to be able to enjoy the sunshine while doing it. Please consider adding an option so you're not penalized with slower fishing for doing that.

Thanks.

**Comment by GirafiStudios** [comment]
There is no penalty for fishing in the sun, not quite sure what you´re talking about!

**Comment by Bronski** [comment]
From the WIKI:

> Once the bobber hits water, the wait time is determined, and the player must wait for a random period between 5 and 30 seconds (100 to 600 [ticks](https://minecraft.fandom.com/wiki/Tick) at 20 ticks per second) before the hook catches something.
> 
> If the bobber's block is being rained on, the wait time is reduced by approximately 1⁄4 (each tick has a 25% chance of counting down 2 instead of 1). The bobber must be located in a [biome](https://minecraft.fandom.com/wiki/Biome) where it is currently raining and all blocks above it must not block movement (e.g. [torch](https://minecraft.fandom.com/wiki/Torch), [tripwire](https://minecraft.fandom.com/wiki/Tripwire)).

https://minecraft.fandom.com/wiki/Fishing#Catching_fish

**Comment by GirafiStudios** [comment]
Well there is functionality in AQ2 that already allows reduced the wait time. Such as the gold hook & diamond hook

**Comment by Bronski** [comment]
Indeed, but someone fishing in the sun will always be penalized.

It was just an idea. 😛

**Comment by GirafiStudios** [comment]
We can´t actually add an option to increase it more, as it would either break vanilla or break other functionaility in AQ2. At a certain point vanilla just crashes, when increasing the value that controls it too much!
