### ISSUE TITLE
Life in the Village 3

### ISSUE THREAD

**Issue by Kaiiiiiiiiii** [TeamMetallurgy/Aquaculture#415]
I am running a Minecraft Server with the modpack "life in the village 3 (LITV3-1.19.2-2.0)".

Version: Aquaculture-1.19.2-2.4.8

The problem with the aquaculture mod is that i cant catch any modrelated fish. I see the items in NEI and i can also craft them and use the rods, but i only catch vanilla fish or croptopia fish.

- i tested it for 2h and got 1000 non related fish
- i used different rods from the aquaculture mod

I also checked the server folders: [
![Screenshot_1](https://github.com/TeamMetallurgy/Aquaculture/assets/57196684/4f7eced2-4f8a-48ad-bea6-586d68c77ef1)
](url)

**Comment by GirafiStudios** [comment]
What Aquaculture 2 version are you on?

**Comment by Kaiiiiiiiiii** [comment]
Aquaculture-1.19.2-2.4.8.jar

**Comment by GirafiStudios** [comment]
It´s most likely another mod breaking modded fishing - happens sometimes..
Probably croptopia, as you can catch fish from that mod.

Could you try Aquaculture 2 on its own & see if you get fish from AQ2 then?
If you do, then try adding croptopia & see what happens :)

**Comment by Kaiiiiiiiiii** [comment]
Tried both right now, "sadly" they work together. So i guess it has to be another mod. :(

**Comment by DoctorMage** [comment]
This one is completely on us
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/85318453/e607d135-80f9-4bf8-95ab-5b1d8b549576)
had a datapack that was modifying loot tables but forgot to add aquaculture fish to it

**Comment by GirafiStudios** [comment]
That would explain things, thanks!
