### ISSUE TITLE
Aquaculture 2 crashes.

### ISSUE THREAD

**Issue by TITUXS** [TeamMetallurgy/Aquaculture#416]
I made a server in 1.19 with aquaculture 2, and when joining it, minecraft crashes. I attached a crash report to it. Please fix it.
[crash-2023-09-15_20.57.55-client.txt](https://github.com/TeamMetallurgy/Aquaculture/files/12622431/crash-2023-09-15_20.57.55-client.txt)

**Comment by DeliciousBread481** [comment]
wait I encountered the same problem. Could you tell me how you solved it?
