### ISSUE TITLE
Loot was empty in Biome: terralith:alpine_highlands

### ISSUE THREAD

**Issue by RaidenKoizuma** [TeamMetallurgy/Aquaculture#418]
Running 1.20.1, getting this spammed in server console.
[22:49:50] [Server thread/ERROR] [aquaculture/]: Loot was empty in Biome: terralith:alpine_highlands. Please report on Github

If you need a full log or modlist (assuming you don't), let me know!

**Comment by catter1** [comment]
Hi, Terralith dev here. Alpine Highlands indeed has biome tags. This includes the `minecraft`, `terralith`, `c`, and `forge` namespaces. Image (and link) provided below for example.

[![image](https://github.com/TeamMetallurgy/Aquaculture/assets/63272345/96cc4ef1-d080-443f-97f9-cf39aad337ea)](https://github.com/search?q=repo%3AStardust-Labs-MC%2FTerralith%20terralith%3Aalpine_highlands&type=code)

**Comment by GirafiStudios** [comment]
Thanks @catter1! 

What version of Minecraft Forge are you on @RaidenKoizuma?

**Comment by SiverDX** [comment]
same issue here on 1.19.2, 43.3.2

**Comment by GirafiStudios** [comment]
> same issue here on 1.19.2, 43.3.2

Also for terralith:alpine_highlands?

**Comment by SiverDX** [comment]
yes

**Comment by GirafiStudios** [comment]
> yes was initially confused why sometimes there was no loot

Is this also on a server?
I´m unable to reproduce in singleplayer at least.

**Comment by SiverDX** [comment]
Yeah it's multiplayer, no LAN or Essential mod etc.
