### ISSUE TITLE
[Suggestion] Datapack support for baits

### ISSUE THREAD

**Issue by Le6barbare** [TeamMetallurgy/Aquaculture#420]
Hello !

Having the possibility to make datapack to add items as baits would be a great addition to Aquaculture
So by using Json files, people would be able to add support for items from other mods with custom chances of catching a fish
thus allowing better integration of Aquaculture in modpacks

I don't know how much work is needed to make baits data-driven, but I hope it is feasible

**Comment by GirafiStudios** [comment]
Thanks for the suggestion!

That´s not something we´re looking to do atm., as it´s a huge amount of work.

We have support for bait through our API, so a simple mod would be able to do it.
