### ISSUE TITLE
Allow Fish mount to display modded fish

### ISSUE THREAD

**Issue by Ladocterus** [TeamMetallurgy/Aquaculture#421]
Would it be possible to make it so the fish mount is able to display modded fishes too?

**Comment by SoldierBluejay** [comment]
I feel like that would be difficult for them to do, I feel like that'd be something we'd have to do for ourselves because there are so many mods out there, not to mention how many outdated ones (which are still sometimes used) might be missed.

**Comment by Ladocterus** [comment]
> I feel like that would be difficult for them to do, I feel like that'd be something we'd have to do for ourselves because there are so many mods out there, not to mention how many outdated ones (which are still sometimes used) might be missed.

I'm thinking maybe there is an item id tag check solution that makes it possible(?)
like maybe have the mount block check if the fish item has a mob associated with it (tho not a coder, so might have just that pulled that out my butt and that won't work)

**Comment by GirafiStudios** [comment]
The Fish Mounts support all fish, where the item version of the fish & the entity version of the fish share the same name.
It is however required for Fish Data to be added for the fish items, which can either be done through Aquaculture's API by other mods (In-code) or by CraftTweaker by the user/modpack creator.

Documentation on how to do it with CraftTweaker, can be found here:
https://docs.blamejared.com/1.16/en/mods/Aquaculture2/FishData

Note: If you´re on 1.20.1, I still need to reimplement the support there. Will be out later or tomorrow. If you´re on 1.19.4, please make sure you´re on the latest version.
