### ISSUE TITLE
Possible compatibility with Create: Fishing Bobber Detector?

### ISSUE THREAD

**Issue by GwydionJon** [TeamMetallurgy/Aquaculture#422]
Hello there, 
I have a question/ request:
Would it be possible to add compatability with the [ Create: Fishing Bobber Detector](https://www.curseforge.com/minecraft/mc-mods/fishing-bobber-detector) mod?

As far as i can tell the mod already provides the option to integrate other fishing rods by using the forge:bobber tag, however I have absolutly no knowledge of modding with java, so i don't know how easy or complicated this would be.

Thanks in advance :)

**Comment by GirafiStudios** [comment]
You look to be correct, that it checks for that entity tag.
Feel free to make a PR
