### ISSUE TITLE
broken fillet knives tag?

### ISSUE THREAD

**Issue by Aceplante2** [TeamMetallurgy/Aquaculture#423]
For some reason, your mod no longer seems to use the fillet knives tag (and instead uses forge/knives), making your knives redundant when being used with farmers delight, and also makes it impossible to get your fillet cuts from vanilla fish such as cod/salmon

forge 1.20.1

I could solve this with a datapack, but how do I stop your mod from adding your knives to forge/knives without breaking the whole tag?

![uhhm](https://github.com/TeamMetallurgy/Aquaculture/assets/101857505/4647f79b-5144-4d04-bc9e-9f16ac3ecdc5)
![uhm2](https://github.com/TeamMetallurgy/Aquaculture/assets/101857505/f0383f8e-2ad3-4a8f-9c4b-68949afebf3d)
as you can see, I still get farmers delight stuff even when using your fillet knife

**Comment by GirafiStudios** [comment]
Isn't this only a problem when using Farmers Delights Cutting Board?

**Comment by Aceplante2** [comment]
Well I want the fillets to be cut on the board using your knife, but since they are also added to forge/knives (for some reason), yes I have that issue. How would i go about disabling them being added to the forge/knives tag?

**Comment by GirafiStudios** [comment]
Just to make sure - it works with a vanilla crafting table?

You could create a tag json file, only including the items you want to have the tag (If any), under the Forge namespace.

**Comment by Aceplante2** [comment]
well I didnt want to overwrite other mods that use it, such as FD and all its compats, I want to exclude your knives, not have to manually include all the ones I do

**Comment by Aceplante2** [comment]
When having this file in forge>tags>items>tools>[fillet_knife.json](https://github.com/TeamMetallurgy/Aquaculture/files/13781862/fillet_knife.json)
The tag still says empty in game?

**Comment by GirafiStudios** [comment]
I moved away from using the fillet_knife tag in 1.19, which was only used by me (Or Aquculture 2 rather) & over to the forge:knives tag, to allow other modded knives to cut the Aquaculture fish.

I just tested with Aquaculture 2 and Famers Delight for 1.20.1 & there is no cutting board recipe, that would result in a Fish FIllet from Aquaculture 2. So either you´re adding that yourself or some other mod is.

**Comment by Aceplante2** [comment]
Yes I know. I want to use your fillet knives to cut fish on farmers delights cutting board. Using the fillet knives tag, that was easy. Now that you used the knives tag... I get farmers delight cuts and there appears to be no way to make recipes for you knives specifically.

Why not just have both? Whats wrong with them being tagged as both knives and fillet knives?

**Comment by GirafiStudios** [comment]
There is no real reason to include the tag, when it´s not being used by Aquculture itself or to procide native compatibility with other mods.

You can however easily include it with a datapack of course :)
1.18.2 version of the tag, so you can just copy/paste:
https://github.com/TeamMetallurgy/Aquaculture/blob/AQ2-1.18.2/src/main/resources/data/forge/tags/items/fillet_knife.json

**Comment by Aceplante2** [comment]
I had no issue adding it to 1.18, but I'll have to test if the same format would work for 1.20
