### ISSUE TITLE
Missing items on older game version

### ISSUE THREAD

**Issue by Maestro2442** [TeamMetallurgy/Aquaculture#425]
I am trying to use the mod in a Forge modpack in Minecraft version 1.12.2 using Forge 47.2.0. I have noticed that several items such as tackle box, fillet knives, and hooks do not exist in the Aquaculture-1.12.2-1.6.8.jar version of the mod, as well as the crafting recipes not working. When I tried the version for 1.20.1, the items and recipes were present. Is this an issue? Or do I just have to play new Minecraft versions in order to have access to the material? Seems like a very incomplete experience without them. Other mods I'm running are not available for new versions of the game, which is why I'm trying to get the 1.12.2 version of Aquaculture 2 to work.

**Comment by GirafiStudios** [comment]
Aquaculture 2 is only a thing for 1.14.4+
Before then it was Aquaculture 1, as stated on the CurseForge page - hence why there is a difference in items.
