### ISSUE TITLE
Modrinth release?

### ISSUE THREAD

**Issue by lonevox** [TeamMetallurgy/Aquaculture#426]
Could this be uploaded to Modrinth? It is one of the only mods in my pack that isn't on Modrinth so an upload there would be awesome! If a Modrinth release isn't planned, is it okay to distribute your jars in my pack (the actual jar file, not a link)?

**Comment by GirafiStudios** [comment]
There is currently no plans to release Aquaculture 2 on Modrinth as well.

As stated on the CurseForge page (Near the bottom) you´re very welcome to include Aquaculture 2 in any modpack, as long as you provide a link back to the CurseForge page. That could be in a README, or somewhere similiar that would make sense.
