### ISSUE TITLE
Crash with NeoForge

### ISSUE THREAD

**Issue by Lolothepro** [TeamMetallurgy/Aquaculture#430]
[latest.log](https://github.com/TeamMetallurgy/Aquaculture/files/14320469/latest.log)

**Comment by gekkone** [comment]
Hey @Lolothepro :) I had the same problem and it looks like I was able to fix it. Until the pull request is accepted, you can download the corrected version or build it from [my fork](https://github.com/gekkone/Aquaculture2/tree/2.6.0-fix)
