### ISSUE TITLE
FIshing line always renders on screen when the fishing rod is used by a Create Deployer. 

### ISSUE THREAD

**Issue by Theycallmeaslak** [TeamMetallurgy/Aquaculture#431]
Title.

**Comment by GirafiStudios** [comment]
Does this happen with the vanilla fishing rod?

**Comment by Theycallmeaslak** [comment]
No. Vanilla Rod works fine.

**Comment by GirafiStudios** [comment]
What Minecraft version is this happening on?

**Comment by Theycallmeaslak** [comment]
It was on all the mods 9 so MC 1.20.1

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/TeamMetallurgy/Aquaculture/commit/1c0579ded31d3ea73f81a34b7b2eb2522d9fae31
