### ISSUE TITLE
Reducing or Removing fish spawns in a 1.20.1 Server

### ISSUE THREAD

**Issue by kmkm1234** [TeamMetallurgy/Aquaculture#432]
The server is currently lagging due to entities and mobs, it's not excessive but it does cause the server to crash overtime. We are looking into how to reduce spawns, is there a way to reduce or shut off the mob spawns in Aquaculture? We'd like to not restart the server and remove the mod.

**Comment by GirafiStudios** [comment]
Fish spawns can be altered by a datapack
https://github.com/TeamMetallurgy/Aquaculture/tree/AQ2-1.20.1/src/main/resources/data/aquaculture/forge/biome_modifier

Mods like In Control by McJty can also be used to alter it.
