### ISSUE TITLE
Future plans? (Fabric)

### ISSUE THREAD

**Issue by EfficientStinkbug** [TeamMetallurgy/Aquaculture#435]
First of all, please let me apologize for opening an issue, but the comment section on curseforge is disabled.

Are there any plans to port this incredible mod to Fabric?
I recently switched from Forge to NeoForge and then to Fabric.
Reason being from what I've read is that Forge won't last too long (most of the developers switched to NeoForge). And since NeoForge is still in the early stages, I've noticed that most modders and users are moving to Fabric because of this drama. 

Thanks for your time :)

**Comment by GirafiStudios** [comment]
There have been a 1.20.4 NeoForge version out of AQ2 for months. That should answer your question :)
