### ISSUE TITLE
Fishing line invisible with vivecraft installed

### ISSUE THREAD

**Issue by MeSebi** [TeamMetallurgy/Aquaculture#436]
Having aquaculture 2 with vivecraft installed makes the fishing line and bobber of the mods fishing rods go invisible, vanilla fishing rod is unaffected.
I have tested this in minecraft versions 1.20.1, 1.19.3 and 1.18.2 with latest mod and Forge versions. All have same result.
Problem occurs both on desktop and in vr.

![2024-04-04_20 45 58](https://github.com/TeamMetallurgy/Aquaculture/assets/159568088/e8f15c7e-1471-4ac3-8d43-85a94c386afc)

**Comment by GirafiStudios** [comment]
Do you have Optifine installed by chance?

**Comment by MeSebi** [comment]
nope. only Aquaculture 2 and Vivecraft, nothing else. I'm always creating Profiles through Curseforge, don't know if there is a difference doing it manually.

**Comment by GirafiStudios** [comment]
Just looked into it a bit & looks like we unfortunately can't do anything about it on our end. @fayer3 (Creator of Vivecraft) have opened an issue out it on their own Github repo in 2023. So seems to be a known issue on their end.

https://github.com/Vivecraft/VivecraftMod/issues/114

**Comment by fayer3** [comment]
hm, our thingy should only break in vr though, not non vr. I'll check that

**Comment by fayer3** [comment]
okay I see what's wrong, will at least fix the non vr rendering issue
