### ISSUE TITLE
Fish aren't spawning in 

### ISSUE THREAD

**Issue by MahNemJeff25** [TeamMetallurgy/Aquaculture#438]
I've spent countless hours swimming through the rivers and lakes in my world trying to find any of the new fish that the pack adds and cannot find any. They were spawning in yesterday when I made the world, but now I can't find a single new fish, only water mobs from vanilla minecraft. The mod still works as I can still fish the added mobs up, but I cannot find any of the actual entities spawning in. Does anyone know what is wrong?

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 and Forge version are you using?

**Comment by MahNemJeff25** [comment]
> What version of Aquaculture 2 and Forge version are you using?

I am playing on the most recent version for Minecraft 1.20.4, version 2.6.1 of Aquaculture 2. That being said I'm using Neoforge version 20.4.227

**Comment by GirafiStudios** [comment]
Figured out the cause of the issue. You need to delete your config file & a new correct one will be created on game launch.

Then the fish will start spawning normally again :)

**Comment by MahNemJeff25** [comment]
Thank you so much, I'll give that a try

**Comment by MahNemJeff25** [comment]
> Figured out the cause of the issue. You need to delete your config file & a new correct one will be created on game launch.
> 
> Then the fish will start spawning normally again :)

Hey, I gave this a try and im still not finding any fish spawning in my worlds. I possibly went about deleting my config files in the wrong way, (or deleting the wrong files). Or is it that they wont spawn in any of my previously created worlds? Sorry for all the issues, I'm still a bit new to this

**Comment by GirafiStudios** [comment]
The config file you would need to delete is just the "aquaculture-common.toml" in the config folder :)

**Comment by MahNemJeff25** [comment]
Yep, deleted that one and still no fish spawn:/

> The config file you would need to delete is just the "aquaculture-common.toml" in the config folder :)

**Comment by GirafiStudios** [comment]
Weird!

What modpack are you playing?

**Comment by MahNemJeff25** [comment]
> Weird!
> 
> What modpack are you playing?

Currently Aquaculture 2 is the only mod I'm running

**Comment by GirafiStudios** [comment]
Hmm. What launcher are you using?

**Comment by MahNemJeff25** [comment]
> Hmm. What launcher are you using?

I'm using the microsoft minecraft launcher which has java as well as all the other versions of minecraft. Idk if thats the answer you were looking for, and I apologize for my lack of knowledge

**Comment by MahNemJeff25** [comment]
> > Hmm. What launcher are you using?
> 
> I'm using the microsoft minecraft launcher which has java as well as all the other versions of minecraft. Idk if thats the answer you were looking for, and I apologize for my lack of knowledge

Furthermore, and I believe this is more of a Neoforge issue, but I can't seem to load up modded minecraft atm with the new 1.20.5 version. That being said, I also may have found the issue. I realized that I also had the 2.6.0 version of aquaculture in my mod file, so it was subsequently making a config file for each when I would load up the game. I was gonna test only using one in case they were somehow "competing", but haven't been able to since the update

**Comment by GirafiStudios** [comment]
Aquaculture 2 is not updated to 1.20.5 yet :) (Might not be either, might wait for 1.21)

Could you try the Curseforge Launcher instead by chance? There is sometimes some weirdness going on, when using the default vanilla launcher - for whatever reason.
