### ISSUE TITLE
Incompatibility with BadOptimizations 

### ISSUE THREAD

**Issue by MoonstruckDev** [TeamMetallurgy/Aquaculture#439]
Have the string optimization enabled and the colours/dyes no longer work on the bobber/fishing line

Forge: 47.2.30
Mod Version: 2.5.1
BadOptimizations Version: 2.1.0

`Whether String.format should be redirected to a faster
StringBuilder when calculating the FPS string.
enable_fps_string_optimization: true`

**Comment by GirafiStudios** [comment]
Do you mean in-world or in the inventory?

**Comment by MoonstruckDev** [comment]
In world- when you cast the line looks like a normal string

**Comment by GirafiStudios** [comment]
I was able to reproduce it. There is nothing I can do about it on my end, as they're messing with the rendering.
It would have to be done on their end.

**Comment by ItsThosea** [comment]
I can’t seem to find the conflicting code, can you tell me where it is? (Although I am a little confused on how an fps string optimization conflicts with an entity renderer)

**Comment by GirafiStudios** [comment]
Sure thing!
It´s done in the AquaBobberRenderer, here specifically for the fishing line: (Should hopefully be able to find the bobber overlay in  there as well - I do have things commented for once!)
https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/java/com/teammetallurgy/aquaculture/client/renderer/entity/AquaBobberRenderer.java#L147

**Comment by ItsThosea** [comment]
That's just a vertex renderer-how is it conflicting with the FPS string?! Must be something else.

**Comment by GirafiStudios** [comment]
It could quite well be that it gets the colors from the item line/bobber items, which does extend DyeableLeatherItem.
The line still renders as if though no colors had been applied to the items, when BadOptimizations is installed.

https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/java/com/teammetallurgy/aquaculture/item/DyeableItem.java#L19

**Comment by ItsThosea** [comment]
Sorry for the late response-does disabling entity flag optimizations fix the issue?

**Comment by GirafiStudios** [comment]
All good!
Setting "enable_entity_flag_caching" to false did not fix the issue, no. Left all other configs options as default.

**Comment by ItsThosea** [comment]
Then which config option causes it?

**Comment by ItsThosea** [comment]
[mod.zip](https://github.com/TeamMetallurgy/Aquaculture/files/15284106/mod.zip)
Does this version fix it?

**Comment by GirafiStudios** [comment]
Unfortunately not, no.

**Comment by ItsThosea** [comment]
Well it’s not the fps string optimization, cause that version just plain removes it.

**Comment by GirafiStudios** [comment]
Couldn´t get it to work with either, with just disabling the "fps string optimization" config either. Not sure what it could be!

**Comment by ItsThosea** [comment]
Hm. You could just brute-force every config option until it works.

**Comment by ItsThosea** [comment]
My next idea is maybe it conflicts with the entity renderer optimizations. Can you try that?

**Comment by ItsThosea** [comment]
Called it

**Comment by ItsThosea** [comment]
So uh-I just downloaded the mod. How do you use the bobber? Trying to get more details on this, cause making the entity renderer thing auto-disable with this mod like i did with twilight forest is more of the "destructive last resort" option.

**Comment by GirafiStudios** [comment]
It should be explained on the wiki (Which is at the top here on Github)
Short version:
- You add it on the tackle box (block entity with GUI)
- Put in a fishing rod from AQ2 in the fishing rod slot, to equip the bobber/line
- The bobber and line are items, which can be dyed like leather (Both in-world renders break, with the "enable_entity_renderer_caching" enabled)

**Comment by ItsThosea** [comment]
![2024-05-17_19 20 52](https://github.com/TeamMetallurgy/Aquaculture/assets/104597976/9be31878-0d1d-4111-969a-0182b6ae7620)
What the-how do you activate this?

**Comment by GirafiStudios** [comment]
You take the fishing rod out of the tackle box again :)
You need to dye the fishing line and/or bobber first though, in a crafting table, with any dye.

**Comment by ItsThosea** [comment]
[mod.zip](https://github.com/TeamMetallurgy/Aquaculture/files/15382552/mod.zip)
Uh, messed with some mixins?

**Comment by GirafiStudios** [comment]
No luck unfortunately. Still doesn´t work (With default config)

**Comment by ItsThosea** [comment]
I just tried it with 1.20.4 and it worked fine. Odd. Do you still maintain your 1.20.1 versions?
