### ISSUE TITLE
upgrade_aquatic:entity.perch.ambient

### ISSUE THREAD

**Issue by BlackAures1** [TeamMetallurgy/Aquaculture#440]
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/43911230/ab4f7ba5-39b0-4727-9138-4faf42ae4638)
[2024-05-09-1.log](https://github.com/TeamMetallurgy/Aquaculture/files/15256836/2024-05-09-1.log)
On Aquaculture-1.19.2-2.4.17 appeared a problem with stopping the game (freezing server side). The only thing in the logs is  `Unable to play empty soundEvent: upgrade_aquatic:entity.perch.ambient`. I doubt that client sounds could appear on the server part, but I still think it's necessary to describe it. At the very least fix the problem with the error in the logs :)

**Comment by GirafiStudios** [comment]
That sound is from Upgrade Aquatic, not Aquaculture.
In the log Fancy menu is giving an insane amount of errors.
FTB Quest also a few at the end of the log.

Aquaculture is not mentioned in the log at all.
