### ISSUE TITLE
[1.19.2] Fish Fillet recipe not working with Knife from Tinkers'

### ISSUE THREAD

**Issue by ffuentesm** [TeamMetallurgy/Aquaculture#441]
Forge: 43.3.0
Mods: Aquaculture-1.19.2-2.4.17, tinkers_delight_1.0.0_forge_1.19.2, TConstruct-1.19.2-3.8.3.39, FarmersDelight-1.19.2-1.2.4

Using Tinkers Delight (A Farmer's Delight Add-on), the Daggers from tingers receive the knife and scavange tags, which allows them to be used for crafting, but for some reason they are not working to craft fillets. 
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/ce8c9da2-a081-40a6-81a9-8fb847b0144b)

The daggers are flagged as compatible with the craft on JEI, but not in practice.
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/cc3887dd-b698-47ac-8d37-e0d7cae5afdc)
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/58206eb4-3f30-4c3e-93b5-65b9bc99793c)

Also, the one recipe that the dagger works, it consumes the dagger after the craft. 
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/c8e8235b-d400-4539-87fc-3e0f2801ebdb)
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/631bb9c7-f475-444e-9ea4-b1f41fb29a0c)
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/59f89217-9f28-4ab0-a295-bf32765dd09b)

**Comment by GirafiStudios** [comment]
1.19.2 is no longer supported.
Should work on newer versions
