### ISSUE TITLE
[1.21] [Neoforge] Stone knife broken recipe tag

### ISSUE THREAD

**Issue by ffuentesm** [TeamMetallurgy/Aquaculture#442]
Aquaculture 2.7.0

The neoforge:cobblestone tag does not exist in the neoforge library: [Here](https://github.com/neoforged/NeoForge/tree/1.21.x/src/generated/resources/data/neoforge/tags)
 
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/56ab68d8-69aa-4d5a-a959-1a2c6a05e119)

I would suggest using the vanilla tag "minecraft:stone_tool_material" for this recipe. as it will allow Blackstone, cobblestone, and cobbled deepslate in the crafting. As it's what is used in Vanilla to make stone tools 
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/aed57e5f-1094-427c-92f8-960940ae668d)

**Comment by GirafiStudios** [comment]
Thanks for reporting!
There were a lot of changes to tags since 1.20.4, apparently I missed this one. Good catch!
