### ISSUE TITLE
Fish not spwaning after world creation

### ISSUE THREAD

**Issue by CapitalEleven** [TeamMetallurgy/Aquaculture#444]
Running on Forge 47.2.0, Minecraft 1.20.1, and Aquaculture 1.20.1-2.5.1, custom modpack (can provide list if beneficial), launched through curse forge. When I initially create a world there will be many aquaculture fish in the rivers/oceans, but after playing on the world they eventually stop spawning at all. Can still catch them with fishing rod but no entities spawning. I tried the fix suggested in Issue #438 (deleting config file) but didn't fix the issue of fish spawning in existing worlds :/

**Comment by GirafiStudios** [comment]
It turned out to be a launcher issue in the end actually - config didn´t help.
Have you tried the CurseForge launcher instead?

**Comment by CapitalEleven** [comment]
I think I'm using the curseforge launcher? (Sorry not 100% sure, - I'm going to the curseforge app on my desktop and clicking play by the modpack - it then opens the minecraft launcher where I go to installations and click play on the modpack)

**Comment by GirafiStudios** [comment]
Could you please try updating Forge to 47.3.0 first also?

**Comment by CapitalEleven** [comment]
Updated to Forge 47.3.0, didn't seem to fix it. Here's the mod list:

Bookshelf (1.20.1-20.1.10)
Botany Pots (1.20.1-13.0.30)
Collective (1.20.1-7.60)
Collector's Reap (1.20.1-1.3)
Delightful (1.20.1-3.5.5)
Explorify – Dungeons & Structures (v1.4.0)
GeckoLib (1.20.1-4.4.6)
Just Enough Items (JEI) (1.20.1-forge-15.3.0.4)
Macaw's Doors (1.1.0)
Macaw's Fences and Walls (1.1.1)
ModernFix (5.17.0)
Puzzles Lib [Forge & Fabric] (v8.1.20-1.20.1)
The Twilight Forest (1.20.1-4.3.2145-universal)
Xaero's Minimap (24.1.1)
Xaero's World Map (1.38.4)
Alex's Caves (1.1.4)
Alex's Delight (1.5)
Alex's Mobs (1.22.8)
Ambient Additions (1.20.1-1.0.0)
Aquaculture 2 (1.20.1-2.5.1)
Aquaculture Delight (A Farmer's Delight Add-on) (1.0.0)
Athena (1.20.1-3.1.2)
Better Archeology (1.1.9-1.20.1)
Caged Mobs (1.20.1-forge-2.0.5)
Chipped (1.20.1-3.0.6)
Citadel (2.5.4-1.20.1)
Conduits Prevent Drowned (1.20.1-3.6)
Corpse (1.20.1-1.0.12)
Craftable Horse Armour & Saddle [CHA&S] (1.20)
Critters and Companions (1.20.1-2.1.6)
Croptopia (1.20.1-FORGE-3.0.4)
Croptopia Delight (1.20.1_1.2.2)
Curios API (Forge/NeoForge) (5.9.1+1.20.1)
EpheroLib (1.20.1-FORGE-1.2.0)
Farmer's Delight (1.20.1-1.2.4)
FerriteCore ((Neo)Forge) (6.0.1)
Full Brightness Toggle (1.20.1-4.0)
Jade (11.9.2)
Just Another Rotten Flesh to Leather Mod (1.6.0)
Just Enough Resources (JER) (1.4.0.247)
Macaw's Paintings (1.0.5)
Macaw's Paths and Pavings (1.0.5)
Macaw's Windows (2.2.1)
Miner's Delight + (1.2.3)
Mob Lassos [Forge & Fabric] (v8.0.1)
Name Tag Tweaks (3.3)
Nether's Delight (4.0)
Ocean's Delight (1.0.2)
Overworld Piglins (1.4)
Resourceful Config (2.1.2)
Resourceful Lib (2.1.25)
Simple Hats (0.3.0)
Sneaky Tree Growing [Forge] (1.20.x-1.10.0)
Sophisticated Core (0.6.22.611)
Sophisticated Storage (0.10.25.804)
Terralith (v2.5.1)
Traveler's Backpack (9.1.14)
Tree Harvester (8.7)
Twilight's Flavors & Delight (2.0.11)
Vein Mining (Fabric/Forge/Quilt) (1.4.1+1.20.1)
YUNG's API (Forge) (4.0.5)
YUNG's Better Desert Temples (Forge) (1.20-Forge-3.03)
YUNG's Better Dungeons (Forge) (1.20-Forge-4.04)
YUNG's Better Jungle Temples (Forge) (1.20-Forge-2.0.5)
YUNG's Better Mineshafts (Forge) (1.20-Forge-4.0.4)
YUNG's Better Nether Fortresses (Forge) (1.20-Forge-2.0.6)
YUNG's Better Strongholds (Forge) (1.20-Forge-4.0.3)

**Comment by GirafiStudios** [comment]
Any chance I could get you to export your CurseForge modpack (Right-click it -> Export profile) & include your world as well?

**Comment by CapitalEleven** [comment]
I've exported it but the files too large to add here (1.49 GB) - anything I can leave out of the export?

**Comment by GirafiStudios** [comment]
Could you upload it to something like Dropbox, Google Drive - anything like that & link a download link here? :)

**Comment by CapitalEleven** [comment]
Here's the link to the file on google drive :) https://drive.google.com/file/d/19XfbM54SVBeDaZfXBLaNfC19_4F96r0c/view?usp=sharing

**Comment by GirafiStudios** [comment]
The file is private unfortunately, could you please make it public? :)

**Comment by CapitalEleven** [comment]
Sorry! Just made it public :) https://drive.google.com/file/d/19XfbM54SVBeDaZfXBLaNfC19_4F96r0c/view?usp=drivesdk

**Comment by GirafiStudios** [comment]
Finally got around to take a look at this. You´re right, they don´t seem to spawn. However vanilla fish are not spawning at all either.

Have you added any mods, after you first started playing?

**Comment by GirafiStudios** [comment]
Figured out a solution. It´s the aquatic mobs t hat have reached the cap in your world somehow. No sure if you have a lot of fish you have placed from buckets, or something similiar?

What I did was:
0. Make a backup of your world (Optional but probably a good idea)
0.5. Put all your items away you have on you (Optional)
1. Open to lan & allow cheats
2. Used /tp @p 10000 100 10000 (Took a while to teleport me there) - To not affect the mobs at your base
3. Use /kill @e

This should get rid of the water animals preventing the fish from spawning, while still keeping your animals at your base alive.

![image](https://github.com/TeamMetallurgy/Aquaculture/assets/6305377/f303a2d9-23ff-4260-9283-6c85375b4054)

**Comment by CapitalEleven** [comment]
Thanks so much!! I had added mods after I initially started playing, didn't know it could affect things like that. Also hadn't manually placed any fish from buckets so unsure what was capping the aquatic mobs out, but your solution worked great! Thank you again :)!
