### ISSUE TITLE
[Suggestion] Copper Tier Knife and other tags

### ISSUE THREAD

**Issue by ffuentesm** [TeamMetallurgy/Aquaculture#445]
Just thinking that would be nice to add a Copper Knife and Fishing Rod. 
For the Knife, I was thinking of having a damage of 3 and durability just a little better than the gold knife. 

Here's an example of the texture.
![copper_fillet_knife](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/4def009d-802c-4aa3-a2e4-2cfda40a0bd4)

**Comment by ffuentesm** [comment]
Also, as an addition, could you add the tags to the fish fillet to be compatible with other food mods? 
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/757e82c5-c1ab-4233-9bd6-3023181c9768)

As well as these tags for the raw fish fillet
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/d3b10bc0-7d6c-49e7-8cde-f4a416b5c240)

**Comment by GirafiStudios** [comment]
What tags are you referring to exactly? You´re only showing what tags it does already have.

**Comment by ffuentesm** [comment]
@GirafiStudios I am actually not. I am showing the tags found in a Raw Cod and a Cooked Cod. 
The Raw Fillet and Cooked FIllet have no tags to them.

**Comment by GirafiStudios** [comment]
Oh. In that case, could you sreenshot what the fish fillets tags are currently? Both cooked and raw.

**Comment by ffuentesm** [comment]
@GirafiStudios I already sent it. There is nothing there. 
The image has what both Cod and Fillet contain, and the only one with tags was the cod.

**Comment by GirafiStudios** [comment]
Added raw fish fillet to the cat_food, oceloot_food & foods tag. And cooked fish fillet to the foods tag.
Since it has been cut, it´s no longer a fish really - so the other tags don´t really apply.

As regarding a copper fillet knife, we have no plans for this currently, as we want to follow the vanilla tier progression.
