### ISSUE TITLE
[1.21] [Neoforge] Game Crashes when I try to Fish using modded Fishing Rod 

### ISSUE THREAD

**Issue by ffuentesm** [TeamMetallurgy/Aquaculture#446]
Aquaculture-1.21-2.7.2.jar 
Neoforge: 21.0.42

Crashlog: https://pastebin.com/LptNpi3y

I used an Iron Fishing Rod with a Gold Hook, and when I casted the line it crashed the game.

**Comment by thatkiddie** [comment]
Have a similar problem, a diamond fishing rod with a gold hook on 1.21, if that matters. Similar error code.

**Comment by GirafiStudios** [comment]
Fixed in Dev already. Waiting for a fix in NeoForge, related to an other issue.
Use NeoForge version 21.0.38 for now, or grab the latest AQ2 build from my Jenkins :)

**Comment by ffuentesm** [comment]
Yeah, can't really use .38 other mods I am using are coded for .40 and up. 😂

**Comment by GirafiStudios** [comment]
Use the Jenkins build for now then :)
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.21/

**Comment by GirafiStudios** [comment]
AQ2 version 2.7.3 with the fix, is now available on CurseForge.
