### ISSUE TITLE
[1.21] [Neoforge] MIssing Fish Fillet recipes on JEI/EMI/REI

### ISSUE THREAD

**Issue by ffuentesm** [TeamMetallurgy/Aquaculture#447]
Aquaculture-1.21-2.7.2.jar
Neoforge: 21.0.42

I noticed that the Recipe for the fish fillet are missing
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/d3010c74-7a57-4228-aa06-f9a3e9557c3d)

**Comment by GirafiStudios** [comment]
Unable to reproduce with JEI

![image](https://github.com/TeamMetallurgy/Aquaculture/assets/6305377/ef1b1eac-11ae-4719-8613-6807e118ae2d)

**Comment by ffuentesm** [comment]
@GirafiStudios Is not the knife recipe, is the Knife + Fish = Fillet
I wrote in the title the missing Fish Filet recipe. 
As JEI only shows the knife repair craft instead of also having the knife + fish tab craft

**Comment by GirafiStudios** [comment]
Also not able to reproduce with JEI :) 

![image](https://github.com/TeamMetallurgy/Aquaculture/assets/6305377/3276ca01-2798-495d-b4b5-cd3314d54640)

**Comment by ffuentesm** [comment]
Could you try also with EMI + JEI installed? It's what I am using.

**Comment by GirafiStudios** [comment]
It works with EMI 1.1.7, but not EMI 1.1.8.
So they must have broken something in their latest version

**Comment by GirafiStudios** [comment]
It does not work with EMI installed, no.
