### ISSUE TITLE
[1.21] Neptunian Gear not enchantable

### ISSUE THREAD

**Issue by ffuentesm** [TeamMetallurgy/Aquaculture#448]
I've been wondering if this is a feature or a bug since the Armor and knife are not enchantable
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/00bc9149-6080-45c7-8911-ee6416e36295)
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/bfb3e633-7de2-40db-afbf-a573f81bd59e)

While the tools are enchantable 
![image](https://github.com/TeamMetallurgy/Aquaculture/assets/44974827/9b3c322b-1806-40ce-9e52-b9beae1d477b)

**Comment by GirafiStudios** [comment]
It was indeed a bug, that the armor was not enchantable - good catch! :)
It is intended that knifes aren´t
