### ISSUE TITLE
Empty Neptune's Bounty

### ISSUE THREAD

**Issue by NoChildHood** [TeamMetallurgy/Aquaculture#449]
Hello, I got 2 Neptune's Bounties and they were all empty. Am I having bad luck or are there any bugs?

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 are you using?

Also is this on a server running sort sort of Forge/Bukkit hybrid?

**Comment by NoChildHood** [comment]
I am using the latest version of 1.19.2 (1.19.2-2.4.17)
And no it is only Forge.

**Comment by GirafiStudios** [comment]
I´m unable to reproduce unfortunately. It´s most likely some sort of mod compatibilty issue.

AQ2 for 1.19.2 also won´t receive anymore updates going forward.

**Comment by NoChildHood** [comment]
I see. Thank you for your help!

**Comment by NoChildHood** [comment]
Also do you know any other mods that can cause mod compatibilty issues with Aquaculture 2? Or do you know how to check incompabilities?

**Comment by NoChildHood** [comment]
I see, thank you very much for your help!

**Comment by DaniloNocete** [comment]
Hi, I'm experiencing the same issue. Every Neptune Chest is empty, even using the /loot command.
Using 1.20.1-2.5.2, on a singleplayer world.
