### ISSUE TITLE
[1.19.2] crash occurs after getting neptunium fillet knife

### ISSUE THREAD

**Issue by GodPestilence** [TeamMetallurgy/Aquaculture#455]
after getting the fillet knife from neptunes bounty, my game crashed and cannot successfully be relaunched
![Screenshot 2024-07-20 164508](https://github.com/user-attachments/assets/e0ba7208-6801-4b6d-b903-0b8f897baafb)
i know its the fillet knife, as this occurred right after pulling from the chests inventory.

**Comment by GirafiStudios** [comment]
What Aquaculture 2 and Forge/NeoForge version are you on?
Also is this on a server?

**Comment by GodPestilence** [comment]
> What Aquaculture 2 and Forge/NeoForge version are you on? Also is this on a server?
Forge 1.19.2, not a server, singleplayer world

**Comment by GirafiStudios** [comment]
What specific version of Forge and Aquaculture 2 are you using?

**Comment by GodPestilence** [comment]
Forge 43.3.5, Aquaculture 2.4.17

**Comment by GirafiStudios** [comment]
Same as https://github.com/TeamMetallurgy/Aquaculture/issues/400

I was (& still am) unable to reproduce it. It's caused by some sort of mod incompatibility. Unless you're willing to put in the time & work to figure out what other mod is causing it, I'm afraid I can't do much.
