### ISSUE TITLE
[Idea] Add Saddled bichirs

### ISSUE THREAD

**Issue by vinnyg0621** [TeamMetallurgy/Aquaculture#456]
I've noticed this mod doesn't have bichirs. one of 'em to add would be the one that's in Animal Crossing New Horizons - the Saddled Bichir.
here's a picture:
https://static.wikia.nocookie.net/animalcrossing/images/d/d3/Saddled_Bichir.jpg/revision/latest?cb=20200605001423

**Comment by GirafiStudios** [comment]
Thanks for the suggestion!
We're always considering new fish to potientially add for the future eventually, but there is many we're considering.
We´ll keep this one in mind though :)

**Comment by vinnyg0621** [comment]
np at all!
