### ISSUE TITLE
[1.19.2] Multiple lines connecting several rods

### ISSUE THREAD

**Issue by nul666lun** [TeamMetallurgy/Aquaculture#457]
Not running any shaders or Opti.. sodium is a yes.. everytime i fish with my wife we can both see lines connecting every rod to every bobber to every pole... its mass of tangles distracting lines..

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 are you using?

**Comment by nul666lun** [comment]
> What version of Aquaculture 2 are you using?

Aquaculture-1.19.2-2.4.17

**Comment by GirafiStudios** [comment]
Would you happen to be playing on a LAN servers?

**Comment by nul666lun** [comment]
> Would you happen to be playing on a LAN server?

yes

**Comment by GirafiStudios** [comment]
LAN servers often have issues with Forge. Not anything we really can do about it unfortunately.

I would recommend running a server on your own computer instead with the same world - would cause way less issues :)
