### ISSUE TITLE
[1.21] Fillet recipes are all missing in EMI

### ISSUE THREAD

**Issue by MuteTiefling** [TeamMetallurgy/Aquaculture#459]
Version: Aquaculture-1.21-2.7.7

Latest log: [latest.log](https://github.com/user-attachments/files/16401625/latest.log)

There are no recipes for obtaining fish fillets
![image](https://github.com/user-attachments/assets/4eb794e8-b987-41b4-964d-8ba2e49c8362)

**Comment by GirafiStudios** [comment]
Looks like you're using EMI, if I'm not mistaken?

They show up just fine with just JEI installed, but EMI somehow breaks it. I'll have to look into if it's something on EMI side that breaks it, or if we have to add specific support for EMI.

**Comment by MuteTiefling** [comment]
Yep, we are using EMI with JEI underneath. This allows EMI to pull from JEI for mods that don't support it directly. 

Direct support for EMI would be a nice addition, however.

**Comment by GirafiStudios** [comment]
EMI Supported added in https://github.com/TeamMetallurgy/Aquaculture/commit/81db864f6b5a942a50c8150bb71b1ef96fe06953 :)
