### ISSUE TITLE
No Treasure Chests

### ISSUE THREAD

**Issue by MuteTiefling** [TeamMetallurgy/Aquaculture#460]
Version: Aquaculture-1.21-2.7.7

Treasure boxes don't appear to be dropping. I've been fishing for a while now and have gotten one Neptune's Bounty, but not a single Box, Lockbox, or Treasure Chest. This seems at odds with prior experience in 1.16 where those treasure boxes were somewhat common.

**Comment by GirafiStudios** [comment]
Would you happen to be fishing with a fishing rod with Luck of the Sea?
Boxes, Lockboxes and Treasure Chests is actually considered junk, meaning if you're using Luck of the Sea, they're quite unlikely to appear much.
Treasure Chests is however the rarest of the 3 :)

![image](https://github.com/user-attachments/assets/8657f022-db5c-400d-aec0-475e46cb1fe4)

**Comment by MuteTiefling** [comment]
Odd, with the loot in the treasure chest I wouldn't consider it junk :D But I guess that's fair enough. I do have Luck of the Sea on there.
