### ISSUE TITLE
Neptunium Hoe doesn't work with Farmer's Delight 'Rich Soil'

### ISSUE THREAD

**Issue by The-Lone-Potato** [TeamMetallurgy/Aquaculture#462]
The neptunium hoe cannot hoe/till the rich soil from Farmer's Delight and also therefore cannot be used to keep soil permanently moistursied.

**Comment by GirafiStudios** [comment]
Rich Soil is already a farmland. Hoes only turn dirt/dirt variations into a custom farmland, that's permanently moisturised.

We (Or Farmers Delight I guess) would have to add a custom Rich Soil block, which stays permanently moisturised, which is not something we're looking to do.
