### ISSUE TITLE
[1.21]FishingOverhaul compatibility?

### ISSUE THREAD

**Issue by FrogThai** [TeamMetallurgy/Aquaculture#464]
When I installed FishingOverhaul and this mod as well as I enable the weight configuration,I found that the fish I caught had no weight information.As soon as I removed FishingOverhaul,it became normal.So I'd like to know if you are willing to manage to find time to consider the compatibility between the two mods?Thank you very much.
Aquaculture 2 mod version1.21-2.7.8
FishingOverhaul mod version1.21.0-1.0.0
Neoforge version 21.0.148

**Comment by GirafiStudios** [comment]
There is no way to do that on Aquaculture's end unfortunately.
Fishing Overhaul is cancelling the ItemFishedEvent without any checks, meaning any other mod that uses that event will NOT have their code called. The priority of the event in Fishing Overhaul is event set to HIGHEST, meaning I can't even make sure our code is called before theirs.
https://github.com/pitbox46/FishingOverhaul/blob/502d79da3e68f88f50851def17ec75eef0492d76/src/main/java/github/pitbox46/fishingoverhaul/FishingOverhaul.java#L52
