### ISSUE TITLE
[1.21][Neoforege] Neptunium legging effect triggers outside water 

### ISSUE THREAD

**Issue by ffuentesm** [TeamMetallurgy/Aquaculture#465]
Neoforged  21.0.150
Aquaculture-1.21-2.7.8

When I leave the water sometimes or log into the game, it causes the "weightless" effect of the leggings to apply to my character, acting as if I am hovering in the hair, and unable to go up and down. The only way to fix this in the game is to kill myself or go back into the water and remove the leggings before leaving the water.

**Comment by GirafiStudios** [comment]
While I could not replicate your exact issue, with it making you hover in the air on land, the implementation of it was indeed faulty! 
Should be fixed in 2.7.9
