### ISSUE TITLE
Fish not spawning

### ISSUE THREAD

**Issue by TheLotlaxo** [TeamMetallurgy/Aquaculture#466]
Whenever I change the config to any mod, the fish within this mod stop spawning. I'm using several other mods on version 1.20.1

**Comment by GirafiStudios** [comment]
What version of Aquaculture 2 are you using?

**Comment by HowDareYouIAmGoose** [comment]
I am also having this issue, I am using the latest version (2.5.2 for minecraft 1.20.1). I changed the spawn rates of Alex mob's mod and the fishes from Aquaculture 2 stopped spawning afterwards.

**Comment by GirafiStudios** [comment]
Have you tried deleting your Aquculture config, to see if that fixes it?

If that doesn't help, could you please provide your whole instance + world? :) (If you're using CurseForge a profile export would be the best way to go)

**Comment by HowDareYouIAmGoose** [comment]
I'll try deleting the config, I have like 53 mods so it'll take a few minutes to reload XD

**Comment by HowDareYouIAmGoose** [comment]
Alright thanks I think that did it! I don't know why I didn't think of deleting the config file when I upgraded the but but hey, now I have jellyfish and I saw some atlantic herrings as well. It worked. Thank you, that was fast :9

**Comment by GirafiStudios** [comment]
No problem! Glad that was all that caused it :)
