### ISSUE TITLE
Constant Disconnect

### ISSUE THREAD

**Issue by ItzHonu** [TeamMetallurgy/Aquaculture#467]
I recently found Neptunes Bounty on a friend's server and found a dagger. The moment I put the dagger into my inventory, I now cannot enter the server. Every time I try to, the screen is black and then it disconnects me.

**Comment by GirafiStudios** [comment]
What version of Minecraft, Forge/NeoForge & Aquaculture are you using?

**Comment by GirafiStudios** [comment]
I´ll just assume you're on Minecraft 1.19.2, where I in that case can't really help you as it's a compatibility issues with another mod.
Unless you're willing to put in the same to issolate what other mod is causing it, I can't attempt to fix it.

See other report of the same problem:
https://github.com/TeamMetallurgy/Aquaculture/issues/455
