### ISSUE TITLE
Enchanted Rods in Tackle Box

### ISSUE THREAD

**Issue by dragonfire0612** [TeamMetallurgy/Aquaculture#468]
I'm unsure if this is a bug or if it is intended behavior, but no one on the server I host is able to place an enchanted rod in the fishing rod slot of a tackle box.

**Comment by GirafiStudios** [comment]
Is it an Aquaculture fishing rod?

**Comment by dragonfire0612** [comment]
No, it's a vanilla fishing rod, but I didn't think that would matter.

**Comment by GirafiStudios** [comment]
Only fishing rods added by Aquaculture works with the tackle box :)
