### ISSUE TITLE
[Suggestion] Add a Tag for Hooks

### ISSUE THREAD

**Issue by TheBedrockMaster** [TeamMetallurgy/Aquaculture#469]
Suggestion: Add all Hooks to an item tag like `aquaculture:hooks`, or something similar.

**Comment by GirafiStudios** [comment]
Sure! Do you have a specific reason why you want it added?

**Comment by TheBedrockMaster** [comment]
I want to make something that requires you to get any hook and I think it would be cool for this to be built into the mod.

**Comment by GirafiStudios** [comment]
For a mod or a modpack? Not that it matters, just curious :)

**Comment by GirafiStudios** [comment]
Build with the tag, can be found here: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.21/35/

**Comment by TheBedrockMaster** [comment]
> For a mod or a modpack? Not that it matters, just curious :)

Modpack (All The Mods), thanks.
