### ISSUE TITLE
Data Pack Not Applying on Server

### ISSUE THREAD

**Issue by kk7146** [TeamMetallurgy/Aquaculture#470]
Hi,

I’m experiencing an issue where the data pack is not applying correctly on my server. I’ve followed the instructions to install and enable the data pack, but it doesn’t seem to take effect. Here’s a summary of what I’ve done:

Uploaded the data pack to the datapacks folder.
Used /reload commands to ensure it was loaded.
Restarted the server.
However, the features provided by the data pack are not appearing in the game. There are no errors in the server logs, and the data pack shows up in the list as enabled.

Despite these steps, the fish are not being caught in all biomes as intended, and the data pack doesn’t seem to be working.

Could you please help me troubleshoot this issue?

Thank you for your assistance!

Minecraft Version: 1.20.1
Forge Version: 47.3.0
Mod Version: 1.20.1-2.5.2

[data.zip](https://github.com/user-attachments/files/16736270/data.zip)

**Comment by GirafiStudios** [comment]
I'm not quite sure what you're trying to do here!

Are you saying the attached data pack is not being applied?

Since it's on a server do you have it in world/datapacks/ ?

Also what instructions are you referring to exactly? You're writing it like it's some instructions we've written?

**Comment by GirafiStudios** [comment]
Also the path is wrong in the data pack you attatched. It should be loot_table, not loot_tables

**Comment by GirafiStudios** [comment]
Hopefully that helps!

If not, then please ask in the Aquaculture channel on our Discord server, as Github is not the place for general help only bug reports :)

Our Discord can be found here: https://discord.com/invite/TuJXw7V
