### ISSUE TITLE
Bobbers must be dyeable, (inconvenient for making addons)

### ISSUE THREAD

**Issue by BrownBear85** [TeamMetallurgy/Aquaculture#475]
I am the developer of the mod "Stardew Fishing" which brings the fishing minigame from the game "Stardew Valley" to minecraft. We are adding several bobber items which will be able to be applied as Aquaculture bobbers (similar to how fishing rods in Stardew Valley can have bobbers applied), but are running into an issue.

The `aquaculture:bobber` item tag seems to exist to control which items can be used as bobbers on a fishing rod, but only items that extend `DyeableLeatherItem` with this tag can be placed in the slot. Forcing non-dyeable items into the slot doesn't break anything, so why the requirement? 

With this current restriction, making bobber items will be more complicated (for anyone wanting to make an Aquaculture addon with bobbers), so I'd like you to consider removing the dyeable item requirement for the bobber slot. Thanks!

**Comment by GirafiStudios** [comment]
Sorry for not getting to this before now - haven´t been home.

Should no longer have a requirement for the item to be dyeable. Please do let me know if you encounter any issues!
