### ISSUE TITLE
Publish to `/releases`?

### ISSUE THREAD

**Issue by RokeJulianLockhart** [TeamMetallurgy/Aquaculture#477]
I imagine you use GitHub CI, so it shouldn't be difficult.

**Comment by GirafiStudios** [comment]
I don´t use Github CI. I have a Jenkins, if that´s what you´re after?

**Comment by GirafiStudios** [comment]
https://jenkins.girafi.dk/

**Comment by RokeJulianLockhart** [comment]
> https://github.com/TeamMetallurgy/Aquaculture/issues/477#issuecomment-2380600776

Thanks, @GirafiStudios. Jenkins is good. Perhaps mention it in https://github.com/TeamMetallurgy/Aquaculture/blob/9862098aa7969b98064a1517990e0bddbead9998/README.md#aquaculture-2, since https://github.com/TeamMetallurgy/Aquaculture/releases is empty without any explanation.

ALternatively, I imagine it wouldn't be difficult to hook Jenkins into publishing releases to GH, but I understand if that's undesirable because it's another point of maintenance. Consequently, I'll close the issue as invalid.
