### ISSUE TITLE
Fish not spawning on 1.20.1 after changing the config

### ISSUE THREAD

**Issue by Maltshakes** [TeamMetallurgy/Aquaculture#479]
Hello, I'm playing with version 1.20.1-2.5.2. I am having a recurring issue of fish spawns stopping. I saw there was a previous issue submitted that recommended the config be deleted to fix this problem. It works temporarily until I change the config back to my preferred settings, then fish spawns break again. All I'm doing is enabling fish weight (as I plan to have a fishing competition) but doing that stops the Aquaculture fish spawns entirely. I have noticed that the ""How many blocks below sea level Aquaculture fish can spawn"" setting seems to be changing itself as well.

**Comment by GirafiStudios** [comment]
Thanks for reporting!

Will be fixed in a new build shortly.
