### ISSUE TITLE
High level Short Cast casts further than low level

### ISSUE THREAD

**Issue by Lykrast** [TeamMetallurgy/Aquaculture#48]
Unintuitively, Short Cast I casts the shortest, while Short Cast V cast much further than Short Cast I (but still lower than no Short Cast). It would seem more logical to have higher levels of Short Cast have a stronger effect on the rod (as in cast it shorter with a higher level) instead of the opposite.

**Comment by GirafiStudios** [comment]
Thanks for your suggestion!
It is done this way to stay true to hoe Enchantments work in vanilla Minecraft. For example Sharpness - Sharpness I increases the damage a little, while Sharpness IV increases the damage a lot.

**Comment by Lykrast** [comment]
This is just my opinion on it, but since Short Cast is an enchantment having your cast launched shorter sounds like it's considered like a positive thing, so having the effect lessen with each level is weird in that regard.

So like having Short Cast I shorten it a little and Short Cast IV shorten it a lot would also be valid.
