### ISSUE TITLE
Neptunium Knife is taking damage when using it with Farmer's Delight

### ISSUE THREAD

**Issue by MuteTiefling** [TeamMetallurgy/Aquaculture#484]
![image](https://github.com/user-attachments/assets/2b06b799-e44e-4d28-bc77-1af0e8537eeb)

![image](https://github.com/user-attachments/assets/e0e9bcee-e4be-4455-aa3c-7ac4fdfe4cba)

Currently using it to chop rice to straw. The knife, despite saying it is unbreakable, is very much taking damage.

**Comment by MuteTiefling** [comment]
Are you not using the standard unbreakable component? If I give myself a knife with that, it works fine and never breaks on the cutting board: 

`/give MuteTiefling aquaculture:neptunium_fillet_knife[minecraft:unbreakable={show_in_tooltip:true}]`

**Comment by GirafiStudios** [comment]
Excellent call with the vanilla "Unreakable" component. Wasn't a thing when the Neptunium Fillet Knife was originally designed.
I'll release a fix shortly
