### ISSUE TITLE
Fish Fillet

### ISSUE THREAD

**Issue by guitarist4hire** [TeamMetallurgy/Aquaculture#487]
the fish fillet, in both cooked, and raw form, do not count as meat.

in medieval origins revival, if you pick a race that is strictly a carnivore, you can't eat the fish.

**Comment by GirafiStudios** [comment]
It's a modpack, it would be on them to fix it.

It is in the appropriate food tags.

**Comment by guitarist4hire** [comment]
it is not a mod pack, it is a single mod.

food from other mods show up just fine in the appropriate food categories. the food in this mod is the only one that doesn't behave as it should.

ill contact the devs for the other mod.

**Comment by ExpensiveKoala** [comment]
Origins mod carnivore uses the meat item tag.
https://github.com/apace100/origins-fabric/blob/1.20/src/main/resources/data/origins/tags/items/meat.json

Adding support would be as simple as adding the items to the item tag. https://minecraft.wiki/w/Tag#Item_tags
