### ISSUE TITLE
Modded Biome Support

### ISSUE THREAD

**Issue by zauberparacelsus** [TeamMetallurgy/Aquaculture#53]
Would it be possible to add support for modded biomes, such as those added by Traverse or Biomes o Plenty?  Right now, you -can- catch Aquaculture's fish in modded biomes, but only freshwater fish will show up, rather than saltwater fish, desert fish, etc.

**Comment by GirafiStudios** [comment]
Duplicate of https://github.com/TeamMetallurgy/Aquaculture/issues/26
