### ISSUE TITLE
Neptunium armor/tools cannot be repaired

### ISSUE THREAD

**Issue by Shivaxi** [TeamMetallurgy/Aquaculture#55]
As subject says, neptunium armor and tools cannot be repaired with neptunium ingots unfortunately. latest version for 1.12.2

**Comment by GirafiStudios** [comment]
Will be fixed in Aquaculture 2 for 1.14.4 :)

**Comment by Shivaxi** [comment]
Well I run a modpack called RLCraft with over a million downloads using Aqua Culture for 1.12.2.  If possible I'd need an update for this version and for 1.12.2 as it would be impossible to convert RLCraft to 1.14 as 90% of the mods used have no 1.14 yet, and with 1.15 already on the way it's likely 1.14 will never have all of the mods updated to that version, so RLCraft will probably remain on 1.12.2 for a good year or so.
