### ISSUE TITLE
Knife Recipe Issues

### ISSUE THREAD

**Issue by pandory-network** [TeamMetallurgy/Aquaculture#66]
Hello, 

s there a way to change the recipe for the knife?
This is in conflict with the mod: [TrinityWeapons](https://www.curseforge.com/minecraft/mc-mods/trinityweapons)

Or is it possible to change this self?

**Comment by GirafiStudios** [comment]
Thanks for your report!
Unfortunately there will always be recipes that conflicts in modded Minecraft, that's just the nature of things.
You have two options to change the recipes yourself to your liking though.
Option 1: Use CraftTweaker, learn more and download the mod here: https://www.curseforge.com/minecraft/mc-mods/crafttweaker
Option 2: Use a vanilla ResourcePack to override our recipes, read more here https://minecraft.gamepedia.com/Tutorials/Creating_a_data_pack
