### ISSUE TITLE
Tackle Box dupe on LAN server

### ISSUE THREAD

**Issue by ArtixAllMighty** [TeamMetallurgy/Aquaculture#67]
When opening the Tacklebox on LAN with my friend, I managed to see his fishing rod, and I could upgrade it. 

This has also allowed me to dupe a hook i placed into the tacklebox, by picking it up, and placing it down in the upgrade slot. I cannot really tell if my friend clicked the slot at the same time or so, but I ended up with 2 instances of the hook, and it wasn't  a client dupe. after restarting we still had 2 hooks.

Maybe have the upgrade container only be accessible on a per client base ? like the crafting table. 
The storage space could still be used as a chest and as a 'view for all'.

**Comment by GirafiStudios** [comment]
The dupe was not reliably reproducible.
