### ISSUE TITLE
Neptunium hoe problem

### ISSUE THREAD

**Issue by CastleUnion** [TeamMetallurgy/Aquaculture#69]
The problem I have encountered was that whenever I went to till the land with the hoe, I was unable to plant seeds on the tilled land. Can anyone show me a solution?

**Comment by CastleUnion** [comment]
So I understand you corrected the bug, but how will I implement the fix into my game, If at all?

**Comment by lclc98** [comment]
Hi @CastleUnion, there will be a new release on CurseForge in the next few weeks or less with the fix. Girafi can probably give a better time frame about this.

**Comment by CastleUnion** [comment]
That is all I needed to know, keep up the great work.
