### ISSUE TITLE
Aquaculture fish not counted for "Fishy Business" advancement

### ISSUE THREAD

**Issue by laserlemons** [TeamMetallurgy/Aquaculture#73]
It took until I came across a vanilla fish before I got the fishy business advancement.

**Comment by laserlemons** [comment]
Also the advancement "Tactical Fishing"

**Comment by GirafiStudios** [comment]
There is no way to add support without overwriting the vanilla advancements. If I can make the advancement overwriting configurable I'll implement it, otherwise there is not much I can do.

**Comment by GirafiStudios** [comment]
Yea no way to make it configurable.
You can use this for "fixing" the Fishy Business advancement with a resourcepack:
https://gist.github.com/GirafiStudios/e3871bced3c48de1ab550958d5a6b625

**Comment by laserlemons** [comment]
So the advancement json files overwrite the vanilla ones instead of just adding more conditions? So if two mods were to mess with the same advancement one would be overwritten?

**Comment by GirafiStudios** [comment]
Exactly, which is why I don't want to add it directly to Aquaculture 2.
