### ISSUE TITLE
Loottables not accessable in 1.12.2

### ISSUE THREAD

**Issue by Excederus** [TeamMetallurgy/Aquaculture#76]
I would like to change the loottable of neptunes bounty. But apparently Aquaculture 1.12.2 doesn't have a single loottable so that is not possible.

**Comment by GirafiStudios** [comment]
Correct. Which is why the whole system got scrapped in Aquaculture 2 (For 1.13+) to allow for more customizing by the users of the mod.

**Comment by Excederus** [comment]
Well I mean this wasn't really a "yeah this is how your mod works" more like a request of adding that to the 1.12.2 version if that wouldn't be too much work.

**Comment by GirafiStudios** [comment]
And I'm saying that the whole mod had to be rewritten to allow for that, hence Aquaculture 2.
