### ISSUE TITLE
Can't craft the fishing rods

### ISSUE THREAD

**Issue by Pbshiver** [TeamMetallurgy/Aquaculture#77]
When I put driftwood in to the table, it makes the planks. But when I try to craft any of the fishing rods, nothing comes up 
![image](https://user-images.githubusercontent.com/47580914/71708457-83b67e00-2dbf-11ea-9d54-1215155daf09.png)

**Comment by GirafiStudios** [comment]
That is not the fishing rod recipe. Please check on CurseForge or use JEI to look the recipe up.

**Comment by Azuriuz** [comment]
This is the crafting recipe listed on curseforge

https://i.imgur.com/6PZoJnv.png

**Comment by GirafiStudios** [comment]
Oh CurseForge is wrong then.
This is the recipe:
https://i.imgur.com/nOYgc1U.png
