### ISSUE TITLE
Neptune's Bounty using Neptunium Block break particle

### ISSUE THREAD

**Issue by HeresHavi** [TeamMetallurgy/Aquaculture#78]
Neptune's Bounty is using the Neptunium Block break particle.

The solution would be just to apply the break particle from the regular Minecraft Vanilla chest

![image](https://user-images.githubusercontent.com/39027816/71740257-04c35300-2e5c-11ea-92de-03731e0e0dfe.png)

**Comment by GirafiStudios** [comment]
That's intended.
The vanilla chest is using Oak Planks as the breaking particle nowadays.
