### ISSUE TITLE
Suggestion: AppleCore support

### ISSUE THREAD

**Issue by Sunconure11** [TeamMetallurgy/Aquaculture#8]
This mod should add support for AppleCore, so mods like Spice of Life can use diminishing returns on the items.

https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore

**Comment by Glassmaker** [comment]
![2015-02-19_09 34 53](https://cloud.githubusercontent.com/assets/5352172/6262778/450e387e-b81b-11e4-8d2f-7d1d9ebbcad8.png)

:)

**Comment by enkryptor** [comment]
nice!
