### ISSUE TITLE
Vanilla fish weights are a bit ... off

### ISSUE THREAD

**Issue by VallenFrostweaver** [TeamMetallurgy/Aquaculture#81]
Minecraft version: 1.14.4
Mod version: Aquaculture 1.14.4-2.0.3
Forge version: 28.1.111

Issue: When turning on the config to have fish weights they work fine for Aquaculture fish but not for vanilla ones. My Cod are over 130 lbs and puffers are around 16 lbs for examples. Perhaps a misplaced decimal?

**Comment by GirafiStudios** [comment]
Can you provide a screenshot?

**Comment by VallenFrostweaver** [comment]
I did a lot of fishing and kept everything. It was in a river. All weights seem ok for all but Cod. The puffer I had before I think just was a "one of" as they ar between 3-8lbs now. Below are images of some of the Cod. They start at 40.3lbs as a "small" type and top out at 201lbs as a "large" type and are averaging over 100lbs.
![fish](https://user-images.githubusercontent.com/13642054/71916663-5a5a7100-3176-11ea-89c1-a648b588072c.png)
![massive](https://user-images.githubusercontent.com/13642054/71916722-7827d600-3176-11ea-813f-fdd722f3ca25.png)
![small](https://user-images.githubusercontent.com/13642054/71916766-92fa4a80-3176-11ea-996a-a9f5801757e3.png)

**Comment by GirafiStudios** [comment]
Actually they're both correct. They just weigh that much. Cod varies a lot though, which is why it might seem weird.
Pufferfish can be up to 30lbs, it's maxed out at 25lbs in Aquaculture though.

**Comment by GirafiStudios** [comment]
Look here for what weights the fish can have: https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/java/com/teammetallurgy/aquaculture/loot/FishWeightHandler.java#L169
(The last number is the amount of fillets a fish will be cut in to, but it only applies to when you don't have the weight config on, so ignore that.

**Comment by VallenFrostweaver** [comment]
Well TIL
Thank you and sorry for the pings.
