### ISSUE TITLE
Version 1.15.1 recipe unlocking

### ISSUE THREAD

**Issue by Duappy** [TeamMetallurgy/Aquaculture#83]
I'm currently using the version for 1.15.1, so I'm unsure if this is the case for other versions. The recipes don't unlock until after I've already crafted the item. Is there a way that can unlock recipes before, such as when you catch the fish, for filets, or when you get the material the recipe uses for the knives and rods, for example cobblestone or iron etc? Thank you.

**Comment by GirafiStudios** [comment]
Unfortunately there is not anything I can do about when recipes get unlocked in the recipe book. There is a few mods out there that unlocks all recipe by default, but I'm not sure if they're on 1.15 yet.
