### ISSUE TITLE
Modded bow enchantments

### ISSUE THREAD

**Issue by phyne** [TeamMetallurgy/Aquaculture#84]
Modded enchantments, such as those from [Ensorcellation](https://www.curseforge.com/minecraft/mc-mods/ensorcellation), can't be put onto the neptunium bow. I asked the [COFH](https://discord.gg/uRKrnbH) folks about it:

```
Phyne_: It seems that the bow enchantments from Ensorcellation cant be put on
modded bows (aquacultures neptunium bow). If this is a problem with that
bow specifically, I'll head over to their issue tracker instead, I'm just not sure
myself.

King Lemming: Intended. Bows need to add a capability for it.
King Lemming: I might be able to invert that behavior...will look into it
```

Figured I'd put this here in hopes that it's an easy addition for you. If not I guess there might be a fix coming from their side.

**Comment by GirafiStudios** [comment]
Since the mod in mention is closed source, I would have no clue what capability that is being referred to.

**Comment by phyne** [comment]
Well I'm sorry for linking to essentially the wrong place, but COFH isn't actually closed source. Apparently this is the place to look: https://github.com/KingLemming/1.14/blob/master/CoFHCore/src/main/java/cofh/lib/capability/CapabilityArchery.java
