### ISSUE TITLE
Error with AC2 and Forge 1.15.1 - 30.0.51

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [TeamMetallurgy/Aquaculture#85]
Getting this error while running Forge 1.15.1 - 30.0.51 with AC2

<a href="https://ibb.co/W3cMLKx"><img src="https://i.ibb.co/W3cMLKx/Error-Aquaculture.png" alt="Error-Aquaculture" border="0"></a>

**Comment by Arishant** [comment]
I'm getting the same error as well, with the same version of forge. Maybe something wrong with compatibility?
