### ISSUE TITLE
[1.15.2] Mod loads default config file but corrects 3 values

### ISSUE THREAD

**Issue by realTIMematrix** [TeamMetallurgy/Aquaculture#87]
Hi,

I recognized that your mod creates at the first start aquaculture-common.toml which is fine.
When I move this file from the config folder to the defaultconfig folder the file was loaded, but it corrects three values which make no sense because this is exact the file which was generated at the first start.
I expect that all predefined values are correct but it seems that it cannot handle empty values which you can see in the logfile.

I'm using:

Minecraft: 1.15.2
Forge: 31.0.16
Aquaculture: 

`[03Feb2020 18:47:16.785] [Server-Worker-2/INFO] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Loading default config file from path C:\Users\Username\Documents\Minecraft\Modpacks\1.15.2\Test Pack\defaultconfigs\aquaculture-common.toml`

`[03Feb2020 18:47:16.806] [Server-Worker-2/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file C:\Users\Username\Documents\Minecraft\Modpacks\1.15.2\Test Pack\config\aquaculture-common.toml is not correct. Correcting`

`[03Feb2020 18:47:16.807] [Server-Worker-2/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn options.box_turtle.exclude was corrected from [] to []`

`[03Feb2020 18:47:16.807] [Server-Worker-2/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn options.arrau_turtle.exclude was corrected from [] to []`

`[03Feb2020 18:47:16.807] [Server-Worker-2/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key spawn options.starshell_turtle.exclude was corrected from [] to []`

**Comment by GirafiStudios** [comment]
That is just Forge being weird, because the value is empty as you said. Nothing I can do about it, and it's not breaking anything - Just a warning in the log.

**Comment by realTIMematrix** [comment]
And what values can be entered?

**Comment by GirafiStudios** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L45
