### ISSUE TITLE
Hooks disappear

### ISSUE THREAD

**Issue by Shuazijun** [TeamMetallurgy/Aquaculture#89]
In the server core "catserver-abd368c-async. Jar", the hook of fishing rod will disappear. The console reports the error message: "defineid called for: class net. Minecraft. Entity. Projectile. Entityfishhook from class com. Teammetallurgy. Aquaculture. Handlers. Entitycustomfishhook"
Server Core Link:"https://github.com/luohuayu/catserver"

**Comment by GirafiStudios** [comment]
Sounds like an issue on their side.
