### ISSUE TITLE
[Feature] Horse Armour

### ISSUE THREAD

**Issue by MasterSloth1** [TeamMetallurgy/Aquaculture#91]
what do you recon about neptunium horse armour???
(also dont press shift enter when making these github issues sorry for all the notifications lol)

**Comment by GirafiStudios** [comment]
Thank you for your suggestion!
We do not aim to add Neptunium variants for every kind of metal-like object that already exists in vanilla - and horses don't really have much to do with fishing :)
Also don't worry about "messing up" when you opened the issue, I only got one notification.
