### ISSUE TITLE
Aquaculture not working

### ISSUE THREAD

**Issue by ladyvalmar** [TeamMetallurgy/Aquaculture#92]
I put the .jar file into my mods folder. I have fabric and it works fine. When I load in I tried to craft the diamond rod and iron rod but it doesn't work. Also how do I know if this mod is working? The game isn't crashing so that's good but I don't see any mob eggs for the fish either.

**Comment by sscards55** [comment]
Aquaculture is a forge mod, if you are trying to load it with a different Modloader it won't work.

**Comment by GirafiStudios** [comment]
As sscards said, Aquaculture is a Forge mod, so it won't work with Fabric.
