### ISSUE TITLE
Neptunium Block Tags

### ISSUE THREAD

**Issue by NillerMedDild** [TeamMetallurgy/Aquaculture#94]
Hello o/

A Storage Block made from Ingots typically has these tags:
`forge:storage_blocks`
`forge:storage_blocks/neptunium`

Would you mind adding them to Neptunium? :)

**Comment by GirafiStudios** [comment]
Sure I'll get around to it soon.
forge:storage_blocks wasn't a thing when I originally added tags for Aquaculture 2, which is why it's missing.

**Comment by NillerMedDild** [comment]
Ah that explains it, thanks!
