### ISSUE TITLE
Loot was empty

### ISSUE THREAD

**Issue by TonioBeh** [TeamMetallurgy/Aquaculture#99]
Hey,

I have a warn in my console : 

[Server thread/ERROR] [aquaculture/]: Loot was empty in Biome: net.minecraft.world.biome.PlainsBiome@2cf88901.

I'm here if you need more informations.

**Comment by GirafiStudios** [comment]
Thanks for the report!
What version of Aquaculture 2 are you using?

**Comment by TonioBeh** [comment]
I'm using the latest ( Aquaculture-1.15.2-2.0.11.jar ), I installed it for the first time ;)

**Comment by GirafiStudios** [comment]
Thanks. That's very interesting, should not be able to happen.
You were just fishing normally, nothing doing anything weird?
Also, are you only using Aquaculture 2?

**Comment by TonioBeh** [comment]
Oh, I thank that is was my fault but that was my friend. He was in AFK farm fishing, I don't know if it changes something.

In this sort of mod, yes. I show you my other mods.
![image](https://user-images.githubusercontent.com/36343285/77216081-2ad1c880-6b18-11ea-8692-a46593e3c010.png)

**Comment by TonioBeh** [comment]
I'm glad that you found the issue, but for the moment we can't (almost) use the fishing rod because it said always that, how can we do ?

**Comment by GirafiStudios** [comment]
Wait you had it happen most of the time? Interesting.
Could you try the latest Jenkins build (Jenkins22) from here: https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Aquaculture/job/Aquaculture%202%201.15/ ?

**Comment by TonioBeh** [comment]
Yes we had it almost everytime (IMG : 
![image](https://user-images.githubusercontent.com/36343285/77216795-894d7580-6b1d-11ea-90ea-98c8434d3777.png)
)

With that version that's perfect ! :) Can we continue to use it ?

**Comment by GirafiStudios** [comment]
Yea sure, go ahead :)
